// Code generated by ent, DO NOT EDIT.

package erpbankreceipt

import (
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldCode, v))
}

// RegisterDate applies equality check predicate on the "register_date" field. It's identical to RegisterDateEQ.
func RegisterDate(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldRegisterDate, v))
}

// FundType applies equality check predicate on the "fund_type" field. It's identical to FundTypeEQ.
func FundType(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldFundType, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldCurrency, v))
}

// ReceivedAmount applies equality check predicate on the "received_amount" field. It's identical to ReceivedAmountEQ.
func ReceivedAmount(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldReceivedAmount, v))
}

// BankFee applies equality check predicate on the "bank_fee" field. It's identical to BankFeeEQ.
func BankFee(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldBankFee, v))
}

// NetAmount applies equality check predicate on the "net_amount" field. It's identical to NetAmountEQ.
func NetAmount(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldNetAmount, v))
}

// RefNo applies equality check predicate on the "ref_no" field. It's identical to RefNoEQ.
func RefNo(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldRefNo, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldStatus, v))
}

// CreatedByAdminID applies equality check predicate on the "created_by_admin_id" field. It's identical to CreatedByAdminIDEQ.
func CreatedByAdminID(v int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldCreatedByAdminID, v))
}

// UpdatedByAdminID applies equality check predicate on the "updated_by_admin_id" field. It's identical to UpdatedByAdminIDEQ.
func UpdatedByAdminID(v int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldUpdatedByAdminID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldContainsFold(FieldCode, v))
}

// RegisterDateEQ applies the EQ predicate on the "register_date" field.
func RegisterDateEQ(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldRegisterDate, v))
}

// RegisterDateNEQ applies the NEQ predicate on the "register_date" field.
func RegisterDateNEQ(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNEQ(FieldRegisterDate, v))
}

// RegisterDateIn applies the In predicate on the "register_date" field.
func RegisterDateIn(vs ...time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIn(FieldRegisterDate, vs...))
}

// RegisterDateNotIn applies the NotIn predicate on the "register_date" field.
func RegisterDateNotIn(vs ...time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotIn(FieldRegisterDate, vs...))
}

// RegisterDateGT applies the GT predicate on the "register_date" field.
func RegisterDateGT(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGT(FieldRegisterDate, v))
}

// RegisterDateGTE applies the GTE predicate on the "register_date" field.
func RegisterDateGTE(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGTE(FieldRegisterDate, v))
}

// RegisterDateLT applies the LT predicate on the "register_date" field.
func RegisterDateLT(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLT(FieldRegisterDate, v))
}

// RegisterDateLTE applies the LTE predicate on the "register_date" field.
func RegisterDateLTE(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLTE(FieldRegisterDate, v))
}

// FundTypeEQ applies the EQ predicate on the "fund_type" field.
func FundTypeEQ(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldFundType, v))
}

// FundTypeNEQ applies the NEQ predicate on the "fund_type" field.
func FundTypeNEQ(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNEQ(FieldFundType, v))
}

// FundTypeIn applies the In predicate on the "fund_type" field.
func FundTypeIn(vs ...string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIn(FieldFundType, vs...))
}

// FundTypeNotIn applies the NotIn predicate on the "fund_type" field.
func FundTypeNotIn(vs ...string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotIn(FieldFundType, vs...))
}

// FundTypeGT applies the GT predicate on the "fund_type" field.
func FundTypeGT(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGT(FieldFundType, v))
}

// FundTypeGTE applies the GTE predicate on the "fund_type" field.
func FundTypeGTE(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGTE(FieldFundType, v))
}

// FundTypeLT applies the LT predicate on the "fund_type" field.
func FundTypeLT(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLT(FieldFundType, v))
}

// FundTypeLTE applies the LTE predicate on the "fund_type" field.
func FundTypeLTE(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLTE(FieldFundType, v))
}

// FundTypeContains applies the Contains predicate on the "fund_type" field.
func FundTypeContains(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldContains(FieldFundType, v))
}

// FundTypeHasPrefix applies the HasPrefix predicate on the "fund_type" field.
func FundTypeHasPrefix(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldHasPrefix(FieldFundType, v))
}

// FundTypeHasSuffix applies the HasSuffix predicate on the "fund_type" field.
func FundTypeHasSuffix(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldHasSuffix(FieldFundType, v))
}

// FundTypeEqualFold applies the EqualFold predicate on the "fund_type" field.
func FundTypeEqualFold(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEqualFold(FieldFundType, v))
}

// FundTypeContainsFold applies the ContainsFold predicate on the "fund_type" field.
func FundTypeContainsFold(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldContainsFold(FieldFundType, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldContainsFold(FieldCurrency, v))
}

// ReceivedAmountEQ applies the EQ predicate on the "received_amount" field.
func ReceivedAmountEQ(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldReceivedAmount, v))
}

// ReceivedAmountNEQ applies the NEQ predicate on the "received_amount" field.
func ReceivedAmountNEQ(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNEQ(FieldReceivedAmount, v))
}

// ReceivedAmountIn applies the In predicate on the "received_amount" field.
func ReceivedAmountIn(vs ...float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIn(FieldReceivedAmount, vs...))
}

// ReceivedAmountNotIn applies the NotIn predicate on the "received_amount" field.
func ReceivedAmountNotIn(vs ...float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotIn(FieldReceivedAmount, vs...))
}

// ReceivedAmountGT applies the GT predicate on the "received_amount" field.
func ReceivedAmountGT(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGT(FieldReceivedAmount, v))
}

// ReceivedAmountGTE applies the GTE predicate on the "received_amount" field.
func ReceivedAmountGTE(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGTE(FieldReceivedAmount, v))
}

// ReceivedAmountLT applies the LT predicate on the "received_amount" field.
func ReceivedAmountLT(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLT(FieldReceivedAmount, v))
}

// ReceivedAmountLTE applies the LTE predicate on the "received_amount" field.
func ReceivedAmountLTE(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLTE(FieldReceivedAmount, v))
}

// BankFeeEQ applies the EQ predicate on the "bank_fee" field.
func BankFeeEQ(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldBankFee, v))
}

// BankFeeNEQ applies the NEQ predicate on the "bank_fee" field.
func BankFeeNEQ(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNEQ(FieldBankFee, v))
}

// BankFeeIn applies the In predicate on the "bank_fee" field.
func BankFeeIn(vs ...float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIn(FieldBankFee, vs...))
}

// BankFeeNotIn applies the NotIn predicate on the "bank_fee" field.
func BankFeeNotIn(vs ...float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotIn(FieldBankFee, vs...))
}

// BankFeeGT applies the GT predicate on the "bank_fee" field.
func BankFeeGT(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGT(FieldBankFee, v))
}

// BankFeeGTE applies the GTE predicate on the "bank_fee" field.
func BankFeeGTE(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGTE(FieldBankFee, v))
}

// BankFeeLT applies the LT predicate on the "bank_fee" field.
func BankFeeLT(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLT(FieldBankFee, v))
}

// BankFeeLTE applies the LTE predicate on the "bank_fee" field.
func BankFeeLTE(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLTE(FieldBankFee, v))
}

// NetAmountEQ applies the EQ predicate on the "net_amount" field.
func NetAmountEQ(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldNetAmount, v))
}

// NetAmountNEQ applies the NEQ predicate on the "net_amount" field.
func NetAmountNEQ(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNEQ(FieldNetAmount, v))
}

// NetAmountIn applies the In predicate on the "net_amount" field.
func NetAmountIn(vs ...float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIn(FieldNetAmount, vs...))
}

// NetAmountNotIn applies the NotIn predicate on the "net_amount" field.
func NetAmountNotIn(vs ...float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotIn(FieldNetAmount, vs...))
}

// NetAmountGT applies the GT predicate on the "net_amount" field.
func NetAmountGT(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGT(FieldNetAmount, v))
}

// NetAmountGTE applies the GTE predicate on the "net_amount" field.
func NetAmountGTE(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGTE(FieldNetAmount, v))
}

// NetAmountLT applies the LT predicate on the "net_amount" field.
func NetAmountLT(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLT(FieldNetAmount, v))
}

// NetAmountLTE applies the LTE predicate on the "net_amount" field.
func NetAmountLTE(v float64) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLTE(FieldNetAmount, v))
}

// RefNoEQ applies the EQ predicate on the "ref_no" field.
func RefNoEQ(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldRefNo, v))
}

// RefNoNEQ applies the NEQ predicate on the "ref_no" field.
func RefNoNEQ(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNEQ(FieldRefNo, v))
}

// RefNoIn applies the In predicate on the "ref_no" field.
func RefNoIn(vs ...string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIn(FieldRefNo, vs...))
}

// RefNoNotIn applies the NotIn predicate on the "ref_no" field.
func RefNoNotIn(vs ...string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotIn(FieldRefNo, vs...))
}

// RefNoGT applies the GT predicate on the "ref_no" field.
func RefNoGT(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGT(FieldRefNo, v))
}

// RefNoGTE applies the GTE predicate on the "ref_no" field.
func RefNoGTE(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGTE(FieldRefNo, v))
}

// RefNoLT applies the LT predicate on the "ref_no" field.
func RefNoLT(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLT(FieldRefNo, v))
}

// RefNoLTE applies the LTE predicate on the "ref_no" field.
func RefNoLTE(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLTE(FieldRefNo, v))
}

// RefNoContains applies the Contains predicate on the "ref_no" field.
func RefNoContains(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldContains(FieldRefNo, v))
}

// RefNoHasPrefix applies the HasPrefix predicate on the "ref_no" field.
func RefNoHasPrefix(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldHasPrefix(FieldRefNo, v))
}

// RefNoHasSuffix applies the HasSuffix predicate on the "ref_no" field.
func RefNoHasSuffix(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldHasSuffix(FieldRefNo, v))
}

// RefNoIsNil applies the IsNil predicate on the "ref_no" field.
func RefNoIsNil() predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIsNull(FieldRefNo))
}

// RefNoNotNil applies the NotNil predicate on the "ref_no" field.
func RefNoNotNil() predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotNull(FieldRefNo))
}

// RefNoEqualFold applies the EqualFold predicate on the "ref_no" field.
func RefNoEqualFold(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEqualFold(FieldRefNo, v))
}

// RefNoContainsFold applies the ContainsFold predicate on the "ref_no" field.
func RefNoContainsFold(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldContainsFold(FieldRefNo, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedByAdminIDEQ applies the EQ predicate on the "created_by_admin_id" field.
func CreatedByAdminIDEQ(v int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDNEQ applies the NEQ predicate on the "created_by_admin_id" field.
func CreatedByAdminIDNEQ(v int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNEQ(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDIn applies the In predicate on the "created_by_admin_id" field.
func CreatedByAdminIDIn(vs ...int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIn(FieldCreatedByAdminID, vs...))
}

// CreatedByAdminIDNotIn applies the NotIn predicate on the "created_by_admin_id" field.
func CreatedByAdminIDNotIn(vs ...int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotIn(FieldCreatedByAdminID, vs...))
}

// CreatedByAdminIDGT applies the GT predicate on the "created_by_admin_id" field.
func CreatedByAdminIDGT(v int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGT(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDGTE applies the GTE predicate on the "created_by_admin_id" field.
func CreatedByAdminIDGTE(v int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGTE(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDLT applies the LT predicate on the "created_by_admin_id" field.
func CreatedByAdminIDLT(v int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLT(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDLTE applies the LTE predicate on the "created_by_admin_id" field.
func CreatedByAdminIDLTE(v int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLTE(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDIsNil applies the IsNil predicate on the "created_by_admin_id" field.
func CreatedByAdminIDIsNil() predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIsNull(FieldCreatedByAdminID))
}

// CreatedByAdminIDNotNil applies the NotNil predicate on the "created_by_admin_id" field.
func CreatedByAdminIDNotNil() predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotNull(FieldCreatedByAdminID))
}

// UpdatedByAdminIDEQ applies the EQ predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDEQ(v int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldUpdatedByAdminID, v))
}

// UpdatedByAdminIDNEQ applies the NEQ predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDNEQ(v int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNEQ(FieldUpdatedByAdminID, v))
}

// UpdatedByAdminIDIn applies the In predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDIn(vs ...int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIn(FieldUpdatedByAdminID, vs...))
}

// UpdatedByAdminIDNotIn applies the NotIn predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDNotIn(vs ...int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotIn(FieldUpdatedByAdminID, vs...))
}

// UpdatedByAdminIDGT applies the GT predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDGT(v int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGT(FieldUpdatedByAdminID, v))
}

// UpdatedByAdminIDGTE applies the GTE predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDGTE(v int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGTE(FieldUpdatedByAdminID, v))
}

// UpdatedByAdminIDLT applies the LT predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDLT(v int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLT(FieldUpdatedByAdminID, v))
}

// UpdatedByAdminIDLTE applies the LTE predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDLTE(v int) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLTE(FieldUpdatedByAdminID, v))
}

// UpdatedByAdminIDIsNil applies the IsNil predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDIsNil() predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIsNull(FieldUpdatedByAdminID))
}

// UpdatedByAdminIDNotNil applies the NotNil predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDNotNil() predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotNull(FieldUpdatedByAdminID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ERPBankReceipt) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ERPBankReceipt) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ERPBankReceipt) predicate.ERPBankReceipt {
	return predicate.ERPBankReceipt(sql.NotPredicates(p))
}
