// Code generated by ent, DO NOT EDIT.

package erpstocktransaction

import (
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLTE(FieldID, id))
}

// BizType applies equality check predicate on the "biz_type" field. It's identical to BizTypeEQ.
func BizType(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldBizType, v))
}

// BizCode applies equality check predicate on the "biz_code" field. It's identical to BizCodeEQ.
func BizCode(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldBizCode, v))
}

// BizLineNo applies equality check predicate on the "biz_line_no" field. It's identical to BizLineNoEQ.
func BizLineNo(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldBizLineNo, v))
}

// ProductCode applies equality check predicate on the "product_code" field. It's identical to ProductCodeEQ.
func ProductCode(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldProductCode, v))
}

// WarehouseID applies equality check predicate on the "warehouse_id" field. It's identical to WarehouseIDEQ.
func WarehouseID(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldWarehouseID, v))
}

// LocationID applies equality check predicate on the "location_id" field. It's identical to LocationIDEQ.
func LocationID(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldLocationID, v))
}

// LotNo applies equality check predicate on the "lot_no" field. It's identical to LotNoEQ.
func LotNo(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldLotNo, v))
}

// DeltaQty applies equality check predicate on the "delta_qty" field. It's identical to DeltaQtyEQ.
func DeltaQty(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldDeltaQty, v))
}

// BeforeAvailableQty applies equality check predicate on the "before_available_qty" field. It's identical to BeforeAvailableQtyEQ.
func BeforeAvailableQty(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldBeforeAvailableQty, v))
}

// AfterAvailableQty applies equality check predicate on the "after_available_qty" field. It's identical to AfterAvailableQtyEQ.
func AfterAvailableQty(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldAfterAvailableQty, v))
}

// OperatorAdminID applies equality check predicate on the "operator_admin_id" field. It's identical to OperatorAdminIDEQ.
func OperatorAdminID(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldOperatorAdminID, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldOccurredAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// BizTypeEQ applies the EQ predicate on the "biz_type" field.
func BizTypeEQ(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldBizType, v))
}

// BizTypeNEQ applies the NEQ predicate on the "biz_type" field.
func BizTypeNEQ(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNEQ(FieldBizType, v))
}

// BizTypeIn applies the In predicate on the "biz_type" field.
func BizTypeIn(vs ...string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIn(FieldBizType, vs...))
}

// BizTypeNotIn applies the NotIn predicate on the "biz_type" field.
func BizTypeNotIn(vs ...string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotIn(FieldBizType, vs...))
}

// BizTypeGT applies the GT predicate on the "biz_type" field.
func BizTypeGT(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGT(FieldBizType, v))
}

// BizTypeGTE applies the GTE predicate on the "biz_type" field.
func BizTypeGTE(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGTE(FieldBizType, v))
}

// BizTypeLT applies the LT predicate on the "biz_type" field.
func BizTypeLT(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLT(FieldBizType, v))
}

// BizTypeLTE applies the LTE predicate on the "biz_type" field.
func BizTypeLTE(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLTE(FieldBizType, v))
}

// BizTypeContains applies the Contains predicate on the "biz_type" field.
func BizTypeContains(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldContains(FieldBizType, v))
}

// BizTypeHasPrefix applies the HasPrefix predicate on the "biz_type" field.
func BizTypeHasPrefix(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldHasPrefix(FieldBizType, v))
}

// BizTypeHasSuffix applies the HasSuffix predicate on the "biz_type" field.
func BizTypeHasSuffix(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldHasSuffix(FieldBizType, v))
}

// BizTypeEqualFold applies the EqualFold predicate on the "biz_type" field.
func BizTypeEqualFold(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEqualFold(FieldBizType, v))
}

// BizTypeContainsFold applies the ContainsFold predicate on the "biz_type" field.
func BizTypeContainsFold(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldContainsFold(FieldBizType, v))
}

// BizCodeEQ applies the EQ predicate on the "biz_code" field.
func BizCodeEQ(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldBizCode, v))
}

// BizCodeNEQ applies the NEQ predicate on the "biz_code" field.
func BizCodeNEQ(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNEQ(FieldBizCode, v))
}

// BizCodeIn applies the In predicate on the "biz_code" field.
func BizCodeIn(vs ...string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIn(FieldBizCode, vs...))
}

// BizCodeNotIn applies the NotIn predicate on the "biz_code" field.
func BizCodeNotIn(vs ...string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotIn(FieldBizCode, vs...))
}

// BizCodeGT applies the GT predicate on the "biz_code" field.
func BizCodeGT(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGT(FieldBizCode, v))
}

// BizCodeGTE applies the GTE predicate on the "biz_code" field.
func BizCodeGTE(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGTE(FieldBizCode, v))
}

// BizCodeLT applies the LT predicate on the "biz_code" field.
func BizCodeLT(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLT(FieldBizCode, v))
}

// BizCodeLTE applies the LTE predicate on the "biz_code" field.
func BizCodeLTE(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLTE(FieldBizCode, v))
}

// BizCodeContains applies the Contains predicate on the "biz_code" field.
func BizCodeContains(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldContains(FieldBizCode, v))
}

// BizCodeHasPrefix applies the HasPrefix predicate on the "biz_code" field.
func BizCodeHasPrefix(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldHasPrefix(FieldBizCode, v))
}

// BizCodeHasSuffix applies the HasSuffix predicate on the "biz_code" field.
func BizCodeHasSuffix(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldHasSuffix(FieldBizCode, v))
}

// BizCodeEqualFold applies the EqualFold predicate on the "biz_code" field.
func BizCodeEqualFold(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEqualFold(FieldBizCode, v))
}

// BizCodeContainsFold applies the ContainsFold predicate on the "biz_code" field.
func BizCodeContainsFold(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldContainsFold(FieldBizCode, v))
}

// BizLineNoEQ applies the EQ predicate on the "biz_line_no" field.
func BizLineNoEQ(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldBizLineNo, v))
}

// BizLineNoNEQ applies the NEQ predicate on the "biz_line_no" field.
func BizLineNoNEQ(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNEQ(FieldBizLineNo, v))
}

// BizLineNoIn applies the In predicate on the "biz_line_no" field.
func BizLineNoIn(vs ...int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIn(FieldBizLineNo, vs...))
}

// BizLineNoNotIn applies the NotIn predicate on the "biz_line_no" field.
func BizLineNoNotIn(vs ...int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotIn(FieldBizLineNo, vs...))
}

// BizLineNoGT applies the GT predicate on the "biz_line_no" field.
func BizLineNoGT(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGT(FieldBizLineNo, v))
}

// BizLineNoGTE applies the GTE predicate on the "biz_line_no" field.
func BizLineNoGTE(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGTE(FieldBizLineNo, v))
}

// BizLineNoLT applies the LT predicate on the "biz_line_no" field.
func BizLineNoLT(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLT(FieldBizLineNo, v))
}

// BizLineNoLTE applies the LTE predicate on the "biz_line_no" field.
func BizLineNoLTE(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLTE(FieldBizLineNo, v))
}

// ProductCodeEQ applies the EQ predicate on the "product_code" field.
func ProductCodeEQ(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldProductCode, v))
}

// ProductCodeNEQ applies the NEQ predicate on the "product_code" field.
func ProductCodeNEQ(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNEQ(FieldProductCode, v))
}

// ProductCodeIn applies the In predicate on the "product_code" field.
func ProductCodeIn(vs ...string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIn(FieldProductCode, vs...))
}

// ProductCodeNotIn applies the NotIn predicate on the "product_code" field.
func ProductCodeNotIn(vs ...string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotIn(FieldProductCode, vs...))
}

// ProductCodeGT applies the GT predicate on the "product_code" field.
func ProductCodeGT(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGT(FieldProductCode, v))
}

// ProductCodeGTE applies the GTE predicate on the "product_code" field.
func ProductCodeGTE(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGTE(FieldProductCode, v))
}

// ProductCodeLT applies the LT predicate on the "product_code" field.
func ProductCodeLT(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLT(FieldProductCode, v))
}

// ProductCodeLTE applies the LTE predicate on the "product_code" field.
func ProductCodeLTE(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLTE(FieldProductCode, v))
}

// ProductCodeContains applies the Contains predicate on the "product_code" field.
func ProductCodeContains(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldContains(FieldProductCode, v))
}

// ProductCodeHasPrefix applies the HasPrefix predicate on the "product_code" field.
func ProductCodeHasPrefix(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldHasPrefix(FieldProductCode, v))
}

// ProductCodeHasSuffix applies the HasSuffix predicate on the "product_code" field.
func ProductCodeHasSuffix(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldHasSuffix(FieldProductCode, v))
}

// ProductCodeEqualFold applies the EqualFold predicate on the "product_code" field.
func ProductCodeEqualFold(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEqualFold(FieldProductCode, v))
}

// ProductCodeContainsFold applies the ContainsFold predicate on the "product_code" field.
func ProductCodeContainsFold(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldContainsFold(FieldProductCode, v))
}

// WarehouseIDEQ applies the EQ predicate on the "warehouse_id" field.
func WarehouseIDEQ(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldWarehouseID, v))
}

// WarehouseIDNEQ applies the NEQ predicate on the "warehouse_id" field.
func WarehouseIDNEQ(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNEQ(FieldWarehouseID, v))
}

// WarehouseIDIn applies the In predicate on the "warehouse_id" field.
func WarehouseIDIn(vs ...int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIn(FieldWarehouseID, vs...))
}

// WarehouseIDNotIn applies the NotIn predicate on the "warehouse_id" field.
func WarehouseIDNotIn(vs ...int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotIn(FieldWarehouseID, vs...))
}

// WarehouseIDGT applies the GT predicate on the "warehouse_id" field.
func WarehouseIDGT(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGT(FieldWarehouseID, v))
}

// WarehouseIDGTE applies the GTE predicate on the "warehouse_id" field.
func WarehouseIDGTE(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGTE(FieldWarehouseID, v))
}

// WarehouseIDLT applies the LT predicate on the "warehouse_id" field.
func WarehouseIDLT(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLT(FieldWarehouseID, v))
}

// WarehouseIDLTE applies the LTE predicate on the "warehouse_id" field.
func WarehouseIDLTE(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLTE(FieldWarehouseID, v))
}

// LocationIDEQ applies the EQ predicate on the "location_id" field.
func LocationIDEQ(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldLocationID, v))
}

// LocationIDNEQ applies the NEQ predicate on the "location_id" field.
func LocationIDNEQ(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNEQ(FieldLocationID, v))
}

// LocationIDIn applies the In predicate on the "location_id" field.
func LocationIDIn(vs ...int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIn(FieldLocationID, vs...))
}

// LocationIDNotIn applies the NotIn predicate on the "location_id" field.
func LocationIDNotIn(vs ...int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotIn(FieldLocationID, vs...))
}

// LocationIDGT applies the GT predicate on the "location_id" field.
func LocationIDGT(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGT(FieldLocationID, v))
}

// LocationIDGTE applies the GTE predicate on the "location_id" field.
func LocationIDGTE(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGTE(FieldLocationID, v))
}

// LocationIDLT applies the LT predicate on the "location_id" field.
func LocationIDLT(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLT(FieldLocationID, v))
}

// LocationIDLTE applies the LTE predicate on the "location_id" field.
func LocationIDLTE(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLTE(FieldLocationID, v))
}

// LotNoEQ applies the EQ predicate on the "lot_no" field.
func LotNoEQ(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldLotNo, v))
}

// LotNoNEQ applies the NEQ predicate on the "lot_no" field.
func LotNoNEQ(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNEQ(FieldLotNo, v))
}

// LotNoIn applies the In predicate on the "lot_no" field.
func LotNoIn(vs ...string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIn(FieldLotNo, vs...))
}

// LotNoNotIn applies the NotIn predicate on the "lot_no" field.
func LotNoNotIn(vs ...string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotIn(FieldLotNo, vs...))
}

// LotNoGT applies the GT predicate on the "lot_no" field.
func LotNoGT(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGT(FieldLotNo, v))
}

// LotNoGTE applies the GTE predicate on the "lot_no" field.
func LotNoGTE(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGTE(FieldLotNo, v))
}

// LotNoLT applies the LT predicate on the "lot_no" field.
func LotNoLT(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLT(FieldLotNo, v))
}

// LotNoLTE applies the LTE predicate on the "lot_no" field.
func LotNoLTE(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLTE(FieldLotNo, v))
}

// LotNoContains applies the Contains predicate on the "lot_no" field.
func LotNoContains(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldContains(FieldLotNo, v))
}

// LotNoHasPrefix applies the HasPrefix predicate on the "lot_no" field.
func LotNoHasPrefix(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldHasPrefix(FieldLotNo, v))
}

// LotNoHasSuffix applies the HasSuffix predicate on the "lot_no" field.
func LotNoHasSuffix(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldHasSuffix(FieldLotNo, v))
}

// LotNoEqualFold applies the EqualFold predicate on the "lot_no" field.
func LotNoEqualFold(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEqualFold(FieldLotNo, v))
}

// LotNoContainsFold applies the ContainsFold predicate on the "lot_no" field.
func LotNoContainsFold(v string) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldContainsFold(FieldLotNo, v))
}

// DeltaQtyEQ applies the EQ predicate on the "delta_qty" field.
func DeltaQtyEQ(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldDeltaQty, v))
}

// DeltaQtyNEQ applies the NEQ predicate on the "delta_qty" field.
func DeltaQtyNEQ(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNEQ(FieldDeltaQty, v))
}

// DeltaQtyIn applies the In predicate on the "delta_qty" field.
func DeltaQtyIn(vs ...float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIn(FieldDeltaQty, vs...))
}

// DeltaQtyNotIn applies the NotIn predicate on the "delta_qty" field.
func DeltaQtyNotIn(vs ...float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotIn(FieldDeltaQty, vs...))
}

// DeltaQtyGT applies the GT predicate on the "delta_qty" field.
func DeltaQtyGT(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGT(FieldDeltaQty, v))
}

// DeltaQtyGTE applies the GTE predicate on the "delta_qty" field.
func DeltaQtyGTE(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGTE(FieldDeltaQty, v))
}

// DeltaQtyLT applies the LT predicate on the "delta_qty" field.
func DeltaQtyLT(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLT(FieldDeltaQty, v))
}

// DeltaQtyLTE applies the LTE predicate on the "delta_qty" field.
func DeltaQtyLTE(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLTE(FieldDeltaQty, v))
}

// BeforeAvailableQtyEQ applies the EQ predicate on the "before_available_qty" field.
func BeforeAvailableQtyEQ(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldBeforeAvailableQty, v))
}

// BeforeAvailableQtyNEQ applies the NEQ predicate on the "before_available_qty" field.
func BeforeAvailableQtyNEQ(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNEQ(FieldBeforeAvailableQty, v))
}

// BeforeAvailableQtyIn applies the In predicate on the "before_available_qty" field.
func BeforeAvailableQtyIn(vs ...float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIn(FieldBeforeAvailableQty, vs...))
}

// BeforeAvailableQtyNotIn applies the NotIn predicate on the "before_available_qty" field.
func BeforeAvailableQtyNotIn(vs ...float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotIn(FieldBeforeAvailableQty, vs...))
}

// BeforeAvailableQtyGT applies the GT predicate on the "before_available_qty" field.
func BeforeAvailableQtyGT(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGT(FieldBeforeAvailableQty, v))
}

// BeforeAvailableQtyGTE applies the GTE predicate on the "before_available_qty" field.
func BeforeAvailableQtyGTE(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGTE(FieldBeforeAvailableQty, v))
}

// BeforeAvailableQtyLT applies the LT predicate on the "before_available_qty" field.
func BeforeAvailableQtyLT(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLT(FieldBeforeAvailableQty, v))
}

// BeforeAvailableQtyLTE applies the LTE predicate on the "before_available_qty" field.
func BeforeAvailableQtyLTE(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLTE(FieldBeforeAvailableQty, v))
}

// AfterAvailableQtyEQ applies the EQ predicate on the "after_available_qty" field.
func AfterAvailableQtyEQ(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldAfterAvailableQty, v))
}

// AfterAvailableQtyNEQ applies the NEQ predicate on the "after_available_qty" field.
func AfterAvailableQtyNEQ(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNEQ(FieldAfterAvailableQty, v))
}

// AfterAvailableQtyIn applies the In predicate on the "after_available_qty" field.
func AfterAvailableQtyIn(vs ...float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIn(FieldAfterAvailableQty, vs...))
}

// AfterAvailableQtyNotIn applies the NotIn predicate on the "after_available_qty" field.
func AfterAvailableQtyNotIn(vs ...float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotIn(FieldAfterAvailableQty, vs...))
}

// AfterAvailableQtyGT applies the GT predicate on the "after_available_qty" field.
func AfterAvailableQtyGT(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGT(FieldAfterAvailableQty, v))
}

// AfterAvailableQtyGTE applies the GTE predicate on the "after_available_qty" field.
func AfterAvailableQtyGTE(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGTE(FieldAfterAvailableQty, v))
}

// AfterAvailableQtyLT applies the LT predicate on the "after_available_qty" field.
func AfterAvailableQtyLT(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLT(FieldAfterAvailableQty, v))
}

// AfterAvailableQtyLTE applies the LTE predicate on the "after_available_qty" field.
func AfterAvailableQtyLTE(v float64) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLTE(FieldAfterAvailableQty, v))
}

// OperatorAdminIDEQ applies the EQ predicate on the "operator_admin_id" field.
func OperatorAdminIDEQ(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldOperatorAdminID, v))
}

// OperatorAdminIDNEQ applies the NEQ predicate on the "operator_admin_id" field.
func OperatorAdminIDNEQ(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNEQ(FieldOperatorAdminID, v))
}

// OperatorAdminIDIn applies the In predicate on the "operator_admin_id" field.
func OperatorAdminIDIn(vs ...int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIn(FieldOperatorAdminID, vs...))
}

// OperatorAdminIDNotIn applies the NotIn predicate on the "operator_admin_id" field.
func OperatorAdminIDNotIn(vs ...int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotIn(FieldOperatorAdminID, vs...))
}

// OperatorAdminIDGT applies the GT predicate on the "operator_admin_id" field.
func OperatorAdminIDGT(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGT(FieldOperatorAdminID, v))
}

// OperatorAdminIDGTE applies the GTE predicate on the "operator_admin_id" field.
func OperatorAdminIDGTE(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGTE(FieldOperatorAdminID, v))
}

// OperatorAdminIDLT applies the LT predicate on the "operator_admin_id" field.
func OperatorAdminIDLT(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLT(FieldOperatorAdminID, v))
}

// OperatorAdminIDLTE applies the LTE predicate on the "operator_admin_id" field.
func OperatorAdminIDLTE(v int) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLTE(FieldOperatorAdminID, v))
}

// OperatorAdminIDIsNil applies the IsNil predicate on the "operator_admin_id" field.
func OperatorAdminIDIsNil() predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIsNull(FieldOperatorAdminID))
}

// OperatorAdminIDNotNil applies the NotNil predicate on the "operator_admin_id" field.
func OperatorAdminIDNotNil() predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotNull(FieldOperatorAdminID))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLTE(FieldOccurredAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ERPStockTransaction) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ERPStockTransaction) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ERPStockTransaction) predicate.ERPStockTransaction {
	return predicate.ERPStockTransaction(sql.NotPredicates(p))
}
