import { BOX_STATUS } from '../constants/workflow'
import { calcReceivableDate } from '../utils/finance'

const yesNoOptions = [
  { label: '是', value: '是' },
  { label: '否', value: '否' },
]

const transportOptions = [
  { label: '海运', value: '海运' },
  { label: '空运', value: '空运' },
  { label: '快递', value: '快递' },
]

export const moduleDefinitions = [
  {
    key: 'partners',
    title: '客户/供应商',
    path: '/master/partners',
    section: 'master',
    codePrefix: 'CS',
    defaultStatus: BOX_STATUS.AUTO,
    description: '客户/供应商建档，支持自动编码与发票地址管理。',
    columns: [
      { title: '代码', dataIndex: 'code' },
      { title: '类型', dataIndex: 'partnerType' },
      { title: '名称', dataIndex: 'name' },
      { title: '付款周期(天)', dataIndex: 'paymentCycleDays' },
      { title: '联系人', dataIndex: 'contact' },
      { title: '联系方式', dataIndex: 'contactPhone' },
    ],
    formFields: [
      {
        name: 'partnerType',
        label: '客户类型',
        type: 'select',
        required: true,
        options: [
          { label: '合作客户', value: '合作客户' },
          { label: '潜在客户', value: '潜在客户' },
          { label: '合作供应商', value: '合作供应商' },
        ],
      },
      { name: 'name', label: '客户/供应商名称', type: 'input', required: true },
      { name: 'address', label: '发票地址', type: 'textarea', required: true },
      { name: 'contact', label: '联系人', type: 'input', required: true },
      { name: 'contactPhone', label: '联系方式', type: 'input', required: true },
      { name: 'taxNo', label: '税号', type: 'input' },
      { name: 'paymentCycleDays', label: '付款周期(天)', type: 'number', required: true },
    ],
    seed: [
      {
        code: 'CS-20260209-0001',
        partnerType: '合作客户',
        name: '杭州科森磁材有限公司',
        address: '浙江省杭州市余杭区文一西路 998 号',
        contact: '王敏',
        contactPhone: '13800000000',
        taxNo: '9133010XXXXXXX',
        paymentCycleDays: 45,
        box: BOX_STATUS.AUTO,
      },
    ],
  },
  {
    key: 'products',
    title: '产品',
    path: '/master/products',
    section: 'master',
    codePrefix: 'PD',
    defaultStatus: BOX_STATUS.AUTO,
    description: '维护产品编码、海关编码、规格与中英文描述。',
    columns: [
      { title: '产品编码', dataIndex: 'code' },
      { title: '海关编码', dataIndex: 'hsCode' },
      { title: '规格编码/图号', dataIndex: 'specCode' },
      { title: '中文描述', dataIndex: 'cnDesc' },
      { title: '英文描述', dataIndex: 'enDesc' },
    ],
    formFields: [
      { name: 'hsCode', label: '海关编码', type: 'input', required: true },
      { name: 'specCode', label: '规格编码/图号', type: 'input', required: true },
      { name: 'cnDesc', label: '中文描述', type: 'input', required: true },
      { name: 'enDesc', label: '英文描述', type: 'input', required: true },
      { name: 'attachment', label: '附件说明', type: 'textarea' },
    ],
    seed: [
      {
        code: 'PD-20260209-0001',
        hsCode: '85051110',
        specCode: 'KS-MAG-001',
        cnDesc: '钕铁硼磁材组件',
        enDesc: 'Neodymium magnet assembly',
        attachment: '图纸 Rev.B',
        box: BOX_STATUS.AUTO,
      },
    ],
  },
  {
    key: 'quotations',
    title: '报价单（可选）',
    path: '/sales/quotations',
    section: 'sales',
    codePrefix: 'QT',
    defaultStatus: BOX_STATUS.DRAFT,
    description: '录入报价与产品明细，可打印报价单与 PI。',
    columns: [
      { title: '报价单编码', dataIndex: 'code' },
      { title: '客户', dataIndex: 'customerName' },
      { title: '产品', dataIndex: 'productName' },
      { title: '数量', dataIndex: 'quantity' },
      { title: '单价(USD)', dataIndex: 'unitPrice' },
      { title: '币种', dataIndex: 'currency' },
    ],
    formFields: [
      { name: 'customerName', label: '客户名称', type: 'input', required: true },
      { name: 'productName', label: '产品名称', type: 'input', required: true },
      { name: 'quantity', label: '数量', type: 'number', required: true },
      { name: 'unitPrice', label: '单价(USD)', type: 'number', required: true },
      {
        name: 'currency',
        label: '币种',
        type: 'select',
        required: true,
        options: [
          { label: 'USD', value: 'USD' },
          { label: 'EUR', value: 'EUR' },
          { label: 'CNY', value: 'CNY' },
        ],
      },
      { name: 'remark', label: '备注', type: 'textarea' },
    ],
    seed: [
      {
        code: 'QT-20260209-0001',
        customerName: 'Kosen Magnet Europe GmbH',
        productName: 'Neodymium magnet assembly',
        quantity: 1200,
        unitPrice: 5.6,
        currency: 'USD',
        remark: '交期 30 天',
        box: BOX_STATUS.DRAFT,
      },
    ],
  },
  {
    key: 'exportSales',
    title: '外销',
    path: '/sales/export',
    section: 'sales',
    codePrefix: 'XS',
    defaultStatus: BOX_STATUS.DRAFT,
    description: '维护外销合同信息，支持 PI/生产加工申请单打印与审批。',
    columns: [
      { title: '合同编号', dataIndex: 'code' },
      { title: '客户合同号', dataIndex: 'customerContractNo' },
      { title: '客户名称', dataIndex: 'customerName' },
      { title: '签约日期', dataIndex: 'signDate' },
      { title: '备货期限', dataIndex: 'deliveryDate' },
      { title: '运输方式', dataIndex: 'transportType' },
    ],
    formFields: [
      { name: 'customerName', label: '客户名称', type: 'input', required: true },
      { name: 'customerContractNo', label: '客户合同号', type: 'input', required: true },
      { name: 'signDate', label: '签约日期', type: 'date', required: true },
      { name: 'deliveryDate', label: '备货期限', type: 'date', required: true },
      { name: 'transportType', label: '运输方式', type: 'select', options: transportOptions, required: true },
      { name: 'prepayRatio', label: '预收款比例(%)', type: 'number' },
      {
        name: 'orderFlow',
        label: '订单流向',
        type: 'select',
        options: [
          { label: '成品采购', value: '成品采购' },
          { label: '内部生产', value: '内部生产' },
        ],
        required: true,
      },
      { name: 'remark', label: '备注', type: 'textarea' },
    ],
    seed: [
      {
        code: 'XS-20260209-0001',
        customerContractNo: 'KSE-2026-PO01',
        customerName: 'Kosen Magnet Europe GmbH',
        signDate: '2026-02-09',
        deliveryDate: '2026-03-10',
        transportType: '海运',
        prepayRatio: 30,
        orderFlow: '成品采购',
        remark: '木箱包装',
        box: BOX_STATUS.PENDING,
      },
    ],
  },
  {
    key: 'purchaseContracts',
    title: '采购（采购合同）',
    path: '/purchase/contracts',
    section: 'purchase',
    codePrefix: 'CG',
    defaultStatus: BOX_STATUS.DRAFT,
    description: '从外销导入产品，自动生成采购合同号并输出固定模板。',
    columns: [
      { title: '采购合同号', dataIndex: 'code' },
      { title: '供应商', dataIndex: 'supplierName' },
      { title: '签约日期', dataIndex: 'signDate' },
      { title: '交货日期', dataIndex: 'deliveryDate' },
      { title: '交货地点', dataIndex: 'deliveryAddress' },
      { title: '开票与否', dataIndex: 'invoiceRequired' },
    ],
    formFields: [
      { name: 'supplierName', label: '供应商', type: 'input', required: true },
      { name: 'signDate', label: '签约日期', type: 'date', required: true },
      { name: 'deliveryDate', label: '交货日期', type: 'date', required: true },
      { name: 'deliveryAddress', label: '交货地点', type: 'input', required: true },
      { name: 'follower', label: '跟单员', type: 'input' },
      { name: 'buyer', label: '采购业务员', type: 'input' },
      { name: 'invoiceRequired', label: '开票与否', type: 'select', options: yesNoOptions, required: true },
      { name: 'remark', label: '备注', type: 'textarea' },
    ],
    seed: [
      {
        code: 'CG-20260209-0001',
        supplierName: '宁波新磁科技有限公司',
        signDate: '2026-02-10',
        deliveryDate: '2026-03-01',
        deliveryAddress: '杭州临平仓',
        follower: '周婷',
        buyer: '李杰',
        invoiceRequired: '是',
        remark: '附图纸 Rev.B',
        box: BOX_STATUS.DRAFT,
      },
    ],
  },
  {
    key: 'inbound',
    title: '入库通知/检验/入库',
    path: '/warehouse/inbound',
    section: 'warehouse',
    codePrefix: 'RK',
    defaultStatus: BOX_STATUS.DRAFT,
    description: '采购到货后生成入库通知，质检通过后允许入库。',
    columns: [
      { title: '入库通知单号', dataIndex: 'code' },
      { title: '采购合同号', dataIndex: 'purchaseCode' },
      { title: '货位', dataIndex: 'location' },
      { title: '质检状态', dataIndex: 'qcStatus' },
      { title: '数量', dataIndex: 'quantity' },
      { title: '检测报告', dataIndex: 'qcAttachment' },
    ],
    formFields: [
      { name: 'purchaseCode', label: '采购合同号', type: 'input', required: true },
      { name: 'location', label: '货位', type: 'input', required: true },
      {
        name: 'qcStatus',
        label: '质检状态',
        type: 'select',
        options: [
          { label: '待检验', value: '待检验' },
          { label: '检验合格', value: '检验合格' },
          { label: '检验不合格', value: '检验不合格' },
        ],
        required: true,
      },
      { name: 'quantity', label: '数量', type: 'number', required: true },
      { name: 'qcAttachment', label: '检测报告附件', type: 'input' },
      { name: 'remark', label: '备注（装箱明细）', type: 'textarea' },
    ],
    seed: [
      {
        code: 'RK-20260209-0001',
        purchaseCode: 'CG-20260209-0001',
        location: 'A-01-03',
        qcStatus: '待检验',
        quantity: 1200,
        qcAttachment: '待上传',
        remark: '40 箱',
        box: BOX_STATUS.DRAFT,
      },
    ],
  },
  {
    key: 'inventory',
    title: '库存',
    path: '/warehouse/inventory',
    section: 'warehouse',
    codePrefix: 'KC',
    defaultStatus: BOX_STATUS.AUTO,
    description: '单仓库+货位实时库存，入库增加、出库扣减联动。',
    columns: [
      { title: '库存编码', dataIndex: 'code' },
      { title: '产品名称', dataIndex: 'productName' },
      { title: '仓库', dataIndex: 'warehouseName' },
      { title: '货位', dataIndex: 'location' },
      { title: '可用数量', dataIndex: 'availableQty' },
      { title: '锁定数量', dataIndex: 'lockedQty' },
    ],
    formFields: [
      { name: 'productName', label: '产品名称', type: 'input', required: true },
      { name: 'warehouseName', label: '仓库名称', type: 'input', required: true },
      { name: 'location', label: '货位', type: 'input', required: true },
      { name: 'availableQty', label: '可用数量', type: 'number', required: true },
      { name: 'lockedQty', label: '锁定数量', type: 'number', required: true },
    ],
    seed: [
      {
        code: 'KC-20260209-0001',
        productName: 'Neodymium magnet assembly',
        warehouseName: '杭州一号仓',
        location: 'A-01-03',
        availableQty: 1200,
        lockedQty: 100,
        box: BOX_STATUS.AUTO,
      },
    ],
  },
  {
    key: 'shipmentDetails',
    title: '出运明细',
    path: '/shipping/details',
    section: 'sales',
    codePrefix: 'CY',
    defaultStatus: BOX_STATUS.DRAFT,
    description: '导入外销明细，提交审批并输出发票/箱单/送货单模板。',
    columns: [
      { title: '发票号', dataIndex: 'code' },
      { title: '起运地', dataIndex: 'startPort' },
      { title: '目的地', dataIndex: 'destPort' },
      { title: '运输方式', dataIndex: 'transportType' },
      { title: '总件数', dataIndex: 'totalPackages' },
      { title: '业务员', dataIndex: 'salesOwner' },
    ],
    formFields: [
      { name: 'startPort', label: '起运地', type: 'input', required: true },
      { name: 'destPort', label: '目的地', type: 'input', required: true },
      { name: 'shipToAddress', label: 'SHIP TO 地址', type: 'textarea', required: true },
      { name: 'transportType', label: '运输方式', type: 'select', options: transportOptions, required: true },
      { name: 'arriveCountry', label: '运抵国', type: 'input', required: true },
      { name: 'salesOwner', label: '业务员', type: 'input', required: true },
      { name: 'totalPackages', label: '总件数', type: 'number', required: true },
      { name: 'marking', label: '唛头', type: 'textarea' },
      { name: 'remark', label: '备注', type: 'textarea' },
    ],
    seed: [
      {
        code: 'CY-20260209-0001',
        startPort: '宁波港',
        destPort: '汉堡港',
        shipToAddress: 'Germany Hamburg Logistics Center',
        transportType: '海运',
        arriveCountry: 'Germany',
        salesOwner: '赵琳',
        totalPackages: 40,
        marking: 'KOSEN/PO01/NO.1-40',
        remark: '附进仓通知',
        box: BOX_STATUS.PENDING,
      },
    ],
  },
  {
    key: 'outbound',
    title: '出库',
    path: '/warehouse/outbound',
    section: 'warehouse',
    codePrefix: 'CK',
    defaultStatus: BOX_STATUS.AUTO,
    description: '导入已完结出运明细，保存并免批，自动扣减库存。',
    columns: [
      { title: '出库单号', dataIndex: 'code' },
      { title: '关联发票号', dataIndex: 'shipmentCode' },
      { title: '产品', dataIndex: 'productName' },
      { title: '数量', dataIndex: 'quantity' },
      { title: '仓库', dataIndex: 'warehouseName' },
      { title: '货位', dataIndex: 'location' },
    ],
    formFields: [
      { name: 'shipmentCode', label: '关联发票号', type: 'input', required: true },
      { name: 'productName', label: '产品', type: 'input', required: true },
      { name: 'quantity', label: '数量', type: 'number', required: true },
      { name: 'warehouseName', label: '仓库', type: 'input', required: true },
      { name: 'location', label: '货位', type: 'input', required: true },
      { name: 'remark', label: '备注', type: 'textarea' },
    ],
    seed: [
      {
        code: 'CK-20260209-0001',
        shipmentCode: 'CY-20260209-0001',
        productName: 'Neodymium magnet assembly',
        quantity: 1100,
        warehouseName: '杭州一号仓',
        location: 'A-01-03',
        remark: '销售出库',
        box: BOX_STATUS.AUTO,
      },
    ],
  },
  {
    key: 'settlements',
    title: '结汇',
    path: '/finance/settlements',
    section: 'finance',
    codePrefix: 'JH',
    defaultStatus: BOX_STATUS.AUTO,
    description: '按发票号导入出运并根据付款周期自动计算应收日期。',
    columns: [
      { title: '结汇单号', dataIndex: 'code' },
      { title: '发票号', dataIndex: 'invoiceNo' },
      { title: '发货日期', dataIndex: 'shipDate' },
      { title: '付款周期(天)', dataIndex: 'paymentCycleDays' },
      { title: '预计收汇日期', dataIndex: 'receivableDate' },
      { title: '金额(USD)', dataIndex: 'amount' },
    ],
    formFields: [
      { name: 'invoiceNo', label: '发票号', type: 'input', required: true },
      { name: 'shipDate', label: '发货日期', type: 'date', required: true },
      { name: 'paymentCycleDays', label: '付款周期(天)', type: 'number', required: true },
      { name: 'amount', label: '金额(USD)', type: 'number', required: true },
      { name: 'remark', label: '备注', type: 'textarea' },
    ],
    beforeSave: (values) => ({
      ...values,
      receivableDate: calcReceivableDate(values.shipDate, values.paymentCycleDays),
    }),
    seed: [
      {
        code: 'JH-20260209-0001',
        invoiceNo: 'CY-20260209-0001',
        shipDate: '2026-02-09',
        paymentCycleDays: 45,
        receivableDate: '2026-03-26',
        amount: 6720,
        remark: '免批入账',
        box: BOX_STATUS.AUTO,
      },
    ],
  },
  {
    key: 'bankReceipts',
    title: '水单→招领→认领确认',
    path: '/finance/bank-receipts',
    section: 'finance',
    codePrefix: 'SD',
    defaultStatus: BOX_STATUS.CLAIM,
    description: '财务登记水单后进入招领箱，业务认领确认后进入确认箱。',
    columns: [
      { title: '水单号', dataIndex: 'code' },
      { title: '款项类型', dataIndex: 'fundType' },
      { title: '关联单号', dataIndex: 'refNo' },
      { title: '收汇金额', dataIndex: 'receivedAmount' },
      { title: '银行扣费', dataIndex: 'bankFee' },
      { title: '登记日期', dataIndex: 'registerDate' },
    ],
    formFields: [
      {
        name: 'fundType',
        label: '款项类型',
        type: 'select',
        required: true,
        options: [
          { label: '预收客户货款', value: '预收客户货款' },
          { label: '客户货款尾款', value: '客户货款尾款' },
        ],
      },
      { name: 'refNo', label: '关联 PI/发票号', type: 'input', required: true },
      { name: 'receivedAmount', label: '收汇金额', type: 'number', required: true },
      { name: 'bankFee', label: '银行扣费', type: 'number', required: true },
      { name: 'registerDate', label: '登记日期', type: 'date', required: true },
      { name: 'remark', label: '备注', type: 'textarea' },
    ],
    seed: [
      {
        code: 'SD-20260209-0001',
        fundType: '预收客户货款',
        refNo: 'QT-20260209-0001',
        receivedAmount: 2000,
        bankFee: 20,
        registerDate: '2026-02-09',
        remark: '待业务认领',
        box: BOX_STATUS.CLAIM,
      },
    ],
  },
]

export const menuSections = [
  {
    key: 'overview',
    title: '总览',
    items: [{ key: '/dashboard', label: '业务看板', moduleKey: 'dashboard' }],
  },
  {
    key: 'master',
    title: '基础资料',
    items: moduleDefinitions
      .filter((moduleItem) => moduleItem.section === 'master')
      .map((moduleItem) => ({ key: moduleItem.path, label: moduleItem.title, moduleKey: moduleItem.key })),
  },
  {
    key: 'sales',
    title: '销售链路',
    items: moduleDefinitions
      .filter((moduleItem) => moduleItem.section === 'sales')
      .map((moduleItem) => ({ key: moduleItem.path, label: moduleItem.title, moduleKey: moduleItem.key })),
  },
  {
    key: 'purchase',
    title: '采购/仓储',
    items: moduleDefinitions
      .filter((moduleItem) => moduleItem.section === 'purchase' || moduleItem.section === 'warehouse')
      .map((moduleItem) => ({ key: moduleItem.path, label: moduleItem.title, moduleKey: moduleItem.key })),
  },
  {
    key: 'finance',
    title: '财务环节',
    items: moduleDefinitions
      .filter((moduleItem) => moduleItem.section === 'finance')
      .map((moduleItem) => ({ key: moduleItem.path, label: moduleItem.title, moduleKey: moduleItem.key })),
  },
  {
    key: 'documents',
    title: '单据模板',
    items: [{ key: '/docs/print-center', label: '打印模板中心', moduleKey: 'print-center' }],
  },
]

export const moduleMap = moduleDefinitions.reduce((acc, current) => {
  acc[current.key] = current
  return acc
}, {})
