// Code generated by ent, DO NOT EDIT.

package erpinboundnotice

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the erpinboundnotice type in the database.
	Label = "erp_inbound_notice"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldPurchaseContractID holds the string denoting the purchase_contract_id field in the database.
	FieldPurchaseContractID = "purchase_contract_id"
	// FieldSourcePurchaseCode holds the string denoting the source_purchase_code field in the database.
	FieldSourcePurchaseCode = "source_purchase_code"
	// FieldEntryNo holds the string denoting the entry_no field in the database.
	FieldEntryNo = "entry_no"
	// FieldWarehouseID holds the string denoting the warehouse_id field in the database.
	FieldWarehouseID = "warehouse_id"
	// FieldLocationID holds the string denoting the location_id field in the database.
	FieldLocationID = "location_id"
	// FieldQcStatus holds the string denoting the qc_status field in the database.
	FieldQcStatus = "qc_status"
	// FieldInboundStatus holds the string denoting the inbound_status field in the database.
	FieldInboundStatus = "inbound_status"
	// FieldAllowInboundAt holds the string denoting the allow_inbound_at field in the database.
	FieldAllowInboundAt = "allow_inbound_at"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldCreatedByAdminID holds the string denoting the created_by_admin_id field in the database.
	FieldCreatedByAdminID = "created_by_admin_id"
	// FieldUpdatedByAdminID holds the string denoting the updated_by_admin_id field in the database.
	FieldUpdatedByAdminID = "updated_by_admin_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the erpinboundnotice in the database.
	Table = "erp_inbound_notices"
)

// Columns holds all SQL columns for erpinboundnotice fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldPurchaseContractID,
	FieldSourcePurchaseCode,
	FieldEntryNo,
	FieldWarehouseID,
	FieldLocationID,
	FieldQcStatus,
	FieldInboundStatus,
	FieldAllowInboundAt,
	FieldRemark,
	FieldCreatedByAdminID,
	FieldUpdatedByAdminID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// SourcePurchaseCodeValidator is a validator for the "source_purchase_code" field. It is called by the builders before save.
	SourcePurchaseCodeValidator func(string) error
	// EntryNoValidator is a validator for the "entry_no" field. It is called by the builders before save.
	EntryNoValidator func(string) error
	// DefaultQcStatus holds the default value on creation for the "qc_status" field.
	DefaultQcStatus string
	// QcStatusValidator is a validator for the "qc_status" field. It is called by the builders before save.
	QcStatusValidator func(string) error
	// DefaultInboundStatus holds the default value on creation for the "inbound_status" field.
	DefaultInboundStatus string
	// InboundStatusValidator is a validator for the "inbound_status" field. It is called by the builders before save.
	InboundStatusValidator func(string) error
	// RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	RemarkValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ERPInboundNotice queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByPurchaseContractID orders the results by the purchase_contract_id field.
func ByPurchaseContractID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurchaseContractID, opts...).ToFunc()
}

// BySourcePurchaseCode orders the results by the source_purchase_code field.
func BySourcePurchaseCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourcePurchaseCode, opts...).ToFunc()
}

// ByEntryNo orders the results by the entry_no field.
func ByEntryNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryNo, opts...).ToFunc()
}

// ByWarehouseID orders the results by the warehouse_id field.
func ByWarehouseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWarehouseID, opts...).ToFunc()
}

// ByLocationID orders the results by the location_id field.
func ByLocationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocationID, opts...).ToFunc()
}

// ByQcStatus orders the results by the qc_status field.
func ByQcStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQcStatus, opts...).ToFunc()
}

// ByInboundStatus orders the results by the inbound_status field.
func ByInboundStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInboundStatus, opts...).ToFunc()
}

// ByAllowInboundAt orders the results by the allow_inbound_at field.
func ByAllowInboundAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowInboundAt, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByCreatedByAdminID orders the results by the created_by_admin_id field.
func ByCreatedByAdminID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByAdminID, opts...).ToFunc()
}

// ByUpdatedByAdminID orders the results by the updated_by_admin_id field.
func ByUpdatedByAdminID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedByAdminID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
