// Code generated by ent, DO NOT EDIT.

package erpinboundnotice

import (
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldCode, v))
}

// PurchaseContractID applies equality check predicate on the "purchase_contract_id" field. It's identical to PurchaseContractIDEQ.
func PurchaseContractID(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldPurchaseContractID, v))
}

// SourcePurchaseCode applies equality check predicate on the "source_purchase_code" field. It's identical to SourcePurchaseCodeEQ.
func SourcePurchaseCode(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldSourcePurchaseCode, v))
}

// EntryNo applies equality check predicate on the "entry_no" field. It's identical to EntryNoEQ.
func EntryNo(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldEntryNo, v))
}

// WarehouseID applies equality check predicate on the "warehouse_id" field. It's identical to WarehouseIDEQ.
func WarehouseID(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldWarehouseID, v))
}

// LocationID applies equality check predicate on the "location_id" field. It's identical to LocationIDEQ.
func LocationID(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldLocationID, v))
}

// QcStatus applies equality check predicate on the "qc_status" field. It's identical to QcStatusEQ.
func QcStatus(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldQcStatus, v))
}

// InboundStatus applies equality check predicate on the "inbound_status" field. It's identical to InboundStatusEQ.
func InboundStatus(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldInboundStatus, v))
}

// AllowInboundAt applies equality check predicate on the "allow_inbound_at" field. It's identical to AllowInboundAtEQ.
func AllowInboundAt(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldAllowInboundAt, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldRemark, v))
}

// CreatedByAdminID applies equality check predicate on the "created_by_admin_id" field. It's identical to CreatedByAdminIDEQ.
func CreatedByAdminID(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldCreatedByAdminID, v))
}

// UpdatedByAdminID applies equality check predicate on the "updated_by_admin_id" field. It's identical to UpdatedByAdminIDEQ.
func UpdatedByAdminID(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldUpdatedByAdminID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldContainsFold(FieldCode, v))
}

// PurchaseContractIDEQ applies the EQ predicate on the "purchase_contract_id" field.
func PurchaseContractIDEQ(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldPurchaseContractID, v))
}

// PurchaseContractIDNEQ applies the NEQ predicate on the "purchase_contract_id" field.
func PurchaseContractIDNEQ(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldPurchaseContractID, v))
}

// PurchaseContractIDIn applies the In predicate on the "purchase_contract_id" field.
func PurchaseContractIDIn(vs ...int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldPurchaseContractID, vs...))
}

// PurchaseContractIDNotIn applies the NotIn predicate on the "purchase_contract_id" field.
func PurchaseContractIDNotIn(vs ...int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldPurchaseContractID, vs...))
}

// PurchaseContractIDGT applies the GT predicate on the "purchase_contract_id" field.
func PurchaseContractIDGT(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldPurchaseContractID, v))
}

// PurchaseContractIDGTE applies the GTE predicate on the "purchase_contract_id" field.
func PurchaseContractIDGTE(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldPurchaseContractID, v))
}

// PurchaseContractIDLT applies the LT predicate on the "purchase_contract_id" field.
func PurchaseContractIDLT(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldPurchaseContractID, v))
}

// PurchaseContractIDLTE applies the LTE predicate on the "purchase_contract_id" field.
func PurchaseContractIDLTE(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldPurchaseContractID, v))
}

// PurchaseContractIDIsNil applies the IsNil predicate on the "purchase_contract_id" field.
func PurchaseContractIDIsNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIsNull(FieldPurchaseContractID))
}

// PurchaseContractIDNotNil applies the NotNil predicate on the "purchase_contract_id" field.
func PurchaseContractIDNotNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotNull(FieldPurchaseContractID))
}

// SourcePurchaseCodeEQ applies the EQ predicate on the "source_purchase_code" field.
func SourcePurchaseCodeEQ(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldSourcePurchaseCode, v))
}

// SourcePurchaseCodeNEQ applies the NEQ predicate on the "source_purchase_code" field.
func SourcePurchaseCodeNEQ(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldSourcePurchaseCode, v))
}

// SourcePurchaseCodeIn applies the In predicate on the "source_purchase_code" field.
func SourcePurchaseCodeIn(vs ...string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldSourcePurchaseCode, vs...))
}

// SourcePurchaseCodeNotIn applies the NotIn predicate on the "source_purchase_code" field.
func SourcePurchaseCodeNotIn(vs ...string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldSourcePurchaseCode, vs...))
}

// SourcePurchaseCodeGT applies the GT predicate on the "source_purchase_code" field.
func SourcePurchaseCodeGT(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldSourcePurchaseCode, v))
}

// SourcePurchaseCodeGTE applies the GTE predicate on the "source_purchase_code" field.
func SourcePurchaseCodeGTE(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldSourcePurchaseCode, v))
}

// SourcePurchaseCodeLT applies the LT predicate on the "source_purchase_code" field.
func SourcePurchaseCodeLT(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldSourcePurchaseCode, v))
}

// SourcePurchaseCodeLTE applies the LTE predicate on the "source_purchase_code" field.
func SourcePurchaseCodeLTE(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldSourcePurchaseCode, v))
}

// SourcePurchaseCodeContains applies the Contains predicate on the "source_purchase_code" field.
func SourcePurchaseCodeContains(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldContains(FieldSourcePurchaseCode, v))
}

// SourcePurchaseCodeHasPrefix applies the HasPrefix predicate on the "source_purchase_code" field.
func SourcePurchaseCodeHasPrefix(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldHasPrefix(FieldSourcePurchaseCode, v))
}

// SourcePurchaseCodeHasSuffix applies the HasSuffix predicate on the "source_purchase_code" field.
func SourcePurchaseCodeHasSuffix(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldHasSuffix(FieldSourcePurchaseCode, v))
}

// SourcePurchaseCodeIsNil applies the IsNil predicate on the "source_purchase_code" field.
func SourcePurchaseCodeIsNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIsNull(FieldSourcePurchaseCode))
}

// SourcePurchaseCodeNotNil applies the NotNil predicate on the "source_purchase_code" field.
func SourcePurchaseCodeNotNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotNull(FieldSourcePurchaseCode))
}

// SourcePurchaseCodeEqualFold applies the EqualFold predicate on the "source_purchase_code" field.
func SourcePurchaseCodeEqualFold(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEqualFold(FieldSourcePurchaseCode, v))
}

// SourcePurchaseCodeContainsFold applies the ContainsFold predicate on the "source_purchase_code" field.
func SourcePurchaseCodeContainsFold(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldContainsFold(FieldSourcePurchaseCode, v))
}

// EntryNoEQ applies the EQ predicate on the "entry_no" field.
func EntryNoEQ(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldEntryNo, v))
}

// EntryNoNEQ applies the NEQ predicate on the "entry_no" field.
func EntryNoNEQ(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldEntryNo, v))
}

// EntryNoIn applies the In predicate on the "entry_no" field.
func EntryNoIn(vs ...string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldEntryNo, vs...))
}

// EntryNoNotIn applies the NotIn predicate on the "entry_no" field.
func EntryNoNotIn(vs ...string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldEntryNo, vs...))
}

// EntryNoGT applies the GT predicate on the "entry_no" field.
func EntryNoGT(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldEntryNo, v))
}

// EntryNoGTE applies the GTE predicate on the "entry_no" field.
func EntryNoGTE(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldEntryNo, v))
}

// EntryNoLT applies the LT predicate on the "entry_no" field.
func EntryNoLT(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldEntryNo, v))
}

// EntryNoLTE applies the LTE predicate on the "entry_no" field.
func EntryNoLTE(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldEntryNo, v))
}

// EntryNoContains applies the Contains predicate on the "entry_no" field.
func EntryNoContains(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldContains(FieldEntryNo, v))
}

// EntryNoHasPrefix applies the HasPrefix predicate on the "entry_no" field.
func EntryNoHasPrefix(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldHasPrefix(FieldEntryNo, v))
}

// EntryNoHasSuffix applies the HasSuffix predicate on the "entry_no" field.
func EntryNoHasSuffix(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldHasSuffix(FieldEntryNo, v))
}

// EntryNoIsNil applies the IsNil predicate on the "entry_no" field.
func EntryNoIsNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIsNull(FieldEntryNo))
}

// EntryNoNotNil applies the NotNil predicate on the "entry_no" field.
func EntryNoNotNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotNull(FieldEntryNo))
}

// EntryNoEqualFold applies the EqualFold predicate on the "entry_no" field.
func EntryNoEqualFold(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEqualFold(FieldEntryNo, v))
}

// EntryNoContainsFold applies the ContainsFold predicate on the "entry_no" field.
func EntryNoContainsFold(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldContainsFold(FieldEntryNo, v))
}

// WarehouseIDEQ applies the EQ predicate on the "warehouse_id" field.
func WarehouseIDEQ(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldWarehouseID, v))
}

// WarehouseIDNEQ applies the NEQ predicate on the "warehouse_id" field.
func WarehouseIDNEQ(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldWarehouseID, v))
}

// WarehouseIDIn applies the In predicate on the "warehouse_id" field.
func WarehouseIDIn(vs ...int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldWarehouseID, vs...))
}

// WarehouseIDNotIn applies the NotIn predicate on the "warehouse_id" field.
func WarehouseIDNotIn(vs ...int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldWarehouseID, vs...))
}

// WarehouseIDGT applies the GT predicate on the "warehouse_id" field.
func WarehouseIDGT(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldWarehouseID, v))
}

// WarehouseIDGTE applies the GTE predicate on the "warehouse_id" field.
func WarehouseIDGTE(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldWarehouseID, v))
}

// WarehouseIDLT applies the LT predicate on the "warehouse_id" field.
func WarehouseIDLT(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldWarehouseID, v))
}

// WarehouseIDLTE applies the LTE predicate on the "warehouse_id" field.
func WarehouseIDLTE(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldWarehouseID, v))
}

// WarehouseIDIsNil applies the IsNil predicate on the "warehouse_id" field.
func WarehouseIDIsNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIsNull(FieldWarehouseID))
}

// WarehouseIDNotNil applies the NotNil predicate on the "warehouse_id" field.
func WarehouseIDNotNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotNull(FieldWarehouseID))
}

// LocationIDEQ applies the EQ predicate on the "location_id" field.
func LocationIDEQ(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldLocationID, v))
}

// LocationIDNEQ applies the NEQ predicate on the "location_id" field.
func LocationIDNEQ(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldLocationID, v))
}

// LocationIDIn applies the In predicate on the "location_id" field.
func LocationIDIn(vs ...int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldLocationID, vs...))
}

// LocationIDNotIn applies the NotIn predicate on the "location_id" field.
func LocationIDNotIn(vs ...int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldLocationID, vs...))
}

// LocationIDGT applies the GT predicate on the "location_id" field.
func LocationIDGT(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldLocationID, v))
}

// LocationIDGTE applies the GTE predicate on the "location_id" field.
func LocationIDGTE(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldLocationID, v))
}

// LocationIDLT applies the LT predicate on the "location_id" field.
func LocationIDLT(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldLocationID, v))
}

// LocationIDLTE applies the LTE predicate on the "location_id" field.
func LocationIDLTE(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldLocationID, v))
}

// LocationIDIsNil applies the IsNil predicate on the "location_id" field.
func LocationIDIsNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIsNull(FieldLocationID))
}

// LocationIDNotNil applies the NotNil predicate on the "location_id" field.
func LocationIDNotNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotNull(FieldLocationID))
}

// QcStatusEQ applies the EQ predicate on the "qc_status" field.
func QcStatusEQ(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldQcStatus, v))
}

// QcStatusNEQ applies the NEQ predicate on the "qc_status" field.
func QcStatusNEQ(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldQcStatus, v))
}

// QcStatusIn applies the In predicate on the "qc_status" field.
func QcStatusIn(vs ...string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldQcStatus, vs...))
}

// QcStatusNotIn applies the NotIn predicate on the "qc_status" field.
func QcStatusNotIn(vs ...string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldQcStatus, vs...))
}

// QcStatusGT applies the GT predicate on the "qc_status" field.
func QcStatusGT(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldQcStatus, v))
}

// QcStatusGTE applies the GTE predicate on the "qc_status" field.
func QcStatusGTE(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldQcStatus, v))
}

// QcStatusLT applies the LT predicate on the "qc_status" field.
func QcStatusLT(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldQcStatus, v))
}

// QcStatusLTE applies the LTE predicate on the "qc_status" field.
func QcStatusLTE(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldQcStatus, v))
}

// QcStatusContains applies the Contains predicate on the "qc_status" field.
func QcStatusContains(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldContains(FieldQcStatus, v))
}

// QcStatusHasPrefix applies the HasPrefix predicate on the "qc_status" field.
func QcStatusHasPrefix(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldHasPrefix(FieldQcStatus, v))
}

// QcStatusHasSuffix applies the HasSuffix predicate on the "qc_status" field.
func QcStatusHasSuffix(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldHasSuffix(FieldQcStatus, v))
}

// QcStatusEqualFold applies the EqualFold predicate on the "qc_status" field.
func QcStatusEqualFold(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEqualFold(FieldQcStatus, v))
}

// QcStatusContainsFold applies the ContainsFold predicate on the "qc_status" field.
func QcStatusContainsFold(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldContainsFold(FieldQcStatus, v))
}

// InboundStatusEQ applies the EQ predicate on the "inbound_status" field.
func InboundStatusEQ(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldInboundStatus, v))
}

// InboundStatusNEQ applies the NEQ predicate on the "inbound_status" field.
func InboundStatusNEQ(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldInboundStatus, v))
}

// InboundStatusIn applies the In predicate on the "inbound_status" field.
func InboundStatusIn(vs ...string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldInboundStatus, vs...))
}

// InboundStatusNotIn applies the NotIn predicate on the "inbound_status" field.
func InboundStatusNotIn(vs ...string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldInboundStatus, vs...))
}

// InboundStatusGT applies the GT predicate on the "inbound_status" field.
func InboundStatusGT(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldInboundStatus, v))
}

// InboundStatusGTE applies the GTE predicate on the "inbound_status" field.
func InboundStatusGTE(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldInboundStatus, v))
}

// InboundStatusLT applies the LT predicate on the "inbound_status" field.
func InboundStatusLT(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldInboundStatus, v))
}

// InboundStatusLTE applies the LTE predicate on the "inbound_status" field.
func InboundStatusLTE(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldInboundStatus, v))
}

// InboundStatusContains applies the Contains predicate on the "inbound_status" field.
func InboundStatusContains(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldContains(FieldInboundStatus, v))
}

// InboundStatusHasPrefix applies the HasPrefix predicate on the "inbound_status" field.
func InboundStatusHasPrefix(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldHasPrefix(FieldInboundStatus, v))
}

// InboundStatusHasSuffix applies the HasSuffix predicate on the "inbound_status" field.
func InboundStatusHasSuffix(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldHasSuffix(FieldInboundStatus, v))
}

// InboundStatusEqualFold applies the EqualFold predicate on the "inbound_status" field.
func InboundStatusEqualFold(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEqualFold(FieldInboundStatus, v))
}

// InboundStatusContainsFold applies the ContainsFold predicate on the "inbound_status" field.
func InboundStatusContainsFold(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldContainsFold(FieldInboundStatus, v))
}

// AllowInboundAtEQ applies the EQ predicate on the "allow_inbound_at" field.
func AllowInboundAtEQ(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldAllowInboundAt, v))
}

// AllowInboundAtNEQ applies the NEQ predicate on the "allow_inbound_at" field.
func AllowInboundAtNEQ(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldAllowInboundAt, v))
}

// AllowInboundAtIn applies the In predicate on the "allow_inbound_at" field.
func AllowInboundAtIn(vs ...time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldAllowInboundAt, vs...))
}

// AllowInboundAtNotIn applies the NotIn predicate on the "allow_inbound_at" field.
func AllowInboundAtNotIn(vs ...time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldAllowInboundAt, vs...))
}

// AllowInboundAtGT applies the GT predicate on the "allow_inbound_at" field.
func AllowInboundAtGT(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldAllowInboundAt, v))
}

// AllowInboundAtGTE applies the GTE predicate on the "allow_inbound_at" field.
func AllowInboundAtGTE(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldAllowInboundAt, v))
}

// AllowInboundAtLT applies the LT predicate on the "allow_inbound_at" field.
func AllowInboundAtLT(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldAllowInboundAt, v))
}

// AllowInboundAtLTE applies the LTE predicate on the "allow_inbound_at" field.
func AllowInboundAtLTE(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldAllowInboundAt, v))
}

// AllowInboundAtIsNil applies the IsNil predicate on the "allow_inbound_at" field.
func AllowInboundAtIsNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIsNull(FieldAllowInboundAt))
}

// AllowInboundAtNotNil applies the NotNil predicate on the "allow_inbound_at" field.
func AllowInboundAtNotNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotNull(FieldAllowInboundAt))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldContainsFold(FieldRemark, v))
}

// CreatedByAdminIDEQ applies the EQ predicate on the "created_by_admin_id" field.
func CreatedByAdminIDEQ(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDNEQ applies the NEQ predicate on the "created_by_admin_id" field.
func CreatedByAdminIDNEQ(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDIn applies the In predicate on the "created_by_admin_id" field.
func CreatedByAdminIDIn(vs ...int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldCreatedByAdminID, vs...))
}

// CreatedByAdminIDNotIn applies the NotIn predicate on the "created_by_admin_id" field.
func CreatedByAdminIDNotIn(vs ...int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldCreatedByAdminID, vs...))
}

// CreatedByAdminIDGT applies the GT predicate on the "created_by_admin_id" field.
func CreatedByAdminIDGT(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDGTE applies the GTE predicate on the "created_by_admin_id" field.
func CreatedByAdminIDGTE(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDLT applies the LT predicate on the "created_by_admin_id" field.
func CreatedByAdminIDLT(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDLTE applies the LTE predicate on the "created_by_admin_id" field.
func CreatedByAdminIDLTE(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDIsNil applies the IsNil predicate on the "created_by_admin_id" field.
func CreatedByAdminIDIsNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIsNull(FieldCreatedByAdminID))
}

// CreatedByAdminIDNotNil applies the NotNil predicate on the "created_by_admin_id" field.
func CreatedByAdminIDNotNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotNull(FieldCreatedByAdminID))
}

// UpdatedByAdminIDEQ applies the EQ predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDEQ(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldUpdatedByAdminID, v))
}

// UpdatedByAdminIDNEQ applies the NEQ predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDNEQ(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldUpdatedByAdminID, v))
}

// UpdatedByAdminIDIn applies the In predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDIn(vs ...int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldUpdatedByAdminID, vs...))
}

// UpdatedByAdminIDNotIn applies the NotIn predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDNotIn(vs ...int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldUpdatedByAdminID, vs...))
}

// UpdatedByAdminIDGT applies the GT predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDGT(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldUpdatedByAdminID, v))
}

// UpdatedByAdminIDGTE applies the GTE predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDGTE(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldUpdatedByAdminID, v))
}

// UpdatedByAdminIDLT applies the LT predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDLT(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldUpdatedByAdminID, v))
}

// UpdatedByAdminIDLTE applies the LTE predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDLTE(v int) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldUpdatedByAdminID, v))
}

// UpdatedByAdminIDIsNil applies the IsNil predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDIsNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIsNull(FieldUpdatedByAdminID))
}

// UpdatedByAdminIDNotNil applies the NotNil predicate on the "updated_by_admin_id" field.
func UpdatedByAdminIDNotNil() predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotNull(FieldUpdatedByAdminID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ERPInboundNotice) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ERPInboundNotice) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ERPInboundNotice) predicate.ERPInboundNotice {
	return predicate.ERPInboundNotice(sql.NotPredicates(p))
}
