// Code generated by ent, DO NOT EDIT.

package erppurchasecontractitem

import (
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLTE(FieldID, id))
}

// PurchaseContractID applies equality check predicate on the "purchase_contract_id" field. It's identical to PurchaseContractIDEQ.
func PurchaseContractID(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldPurchaseContractID, v))
}

// LineNo applies equality check predicate on the "line_no" field. It's identical to LineNoEQ.
func LineNo(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldLineNo, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldProductID, v))
}

// ProductCode applies equality check predicate on the "product_code" field. It's identical to ProductCodeEQ.
func ProductCode(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldProductCode, v))
}

// ProductName applies equality check predicate on the "product_name" field. It's identical to ProductNameEQ.
func ProductName(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldProductName, v))
}

// SpecCode applies equality check predicate on the "spec_code" field. It's identical to SpecCodeEQ.
func SpecCode(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldSpecCode, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldQuantity, v))
}

// UnitPrice applies equality check predicate on the "unit_price" field. It's identical to UnitPriceEQ.
func UnitPrice(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldUnitPrice, v))
}

// TotalPrice applies equality check predicate on the "total_price" field. It's identical to TotalPriceEQ.
func TotalPrice(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldTotalPrice, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// PurchaseContractIDEQ applies the EQ predicate on the "purchase_contract_id" field.
func PurchaseContractIDEQ(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldPurchaseContractID, v))
}

// PurchaseContractIDNEQ applies the NEQ predicate on the "purchase_contract_id" field.
func PurchaseContractIDNEQ(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNEQ(FieldPurchaseContractID, v))
}

// PurchaseContractIDIn applies the In predicate on the "purchase_contract_id" field.
func PurchaseContractIDIn(vs ...int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIn(FieldPurchaseContractID, vs...))
}

// PurchaseContractIDNotIn applies the NotIn predicate on the "purchase_contract_id" field.
func PurchaseContractIDNotIn(vs ...int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotIn(FieldPurchaseContractID, vs...))
}

// PurchaseContractIDGT applies the GT predicate on the "purchase_contract_id" field.
func PurchaseContractIDGT(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGT(FieldPurchaseContractID, v))
}

// PurchaseContractIDGTE applies the GTE predicate on the "purchase_contract_id" field.
func PurchaseContractIDGTE(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGTE(FieldPurchaseContractID, v))
}

// PurchaseContractIDLT applies the LT predicate on the "purchase_contract_id" field.
func PurchaseContractIDLT(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLT(FieldPurchaseContractID, v))
}

// PurchaseContractIDLTE applies the LTE predicate on the "purchase_contract_id" field.
func PurchaseContractIDLTE(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLTE(FieldPurchaseContractID, v))
}

// LineNoEQ applies the EQ predicate on the "line_no" field.
func LineNoEQ(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldLineNo, v))
}

// LineNoNEQ applies the NEQ predicate on the "line_no" field.
func LineNoNEQ(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNEQ(FieldLineNo, v))
}

// LineNoIn applies the In predicate on the "line_no" field.
func LineNoIn(vs ...int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIn(FieldLineNo, vs...))
}

// LineNoNotIn applies the NotIn predicate on the "line_no" field.
func LineNoNotIn(vs ...int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotIn(FieldLineNo, vs...))
}

// LineNoGT applies the GT predicate on the "line_no" field.
func LineNoGT(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGT(FieldLineNo, v))
}

// LineNoGTE applies the GTE predicate on the "line_no" field.
func LineNoGTE(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGTE(FieldLineNo, v))
}

// LineNoLT applies the LT predicate on the "line_no" field.
func LineNoLT(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLT(FieldLineNo, v))
}

// LineNoLTE applies the LTE predicate on the "line_no" field.
func LineNoLTE(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLTE(FieldLineNo, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGT(FieldProductID, v))
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGTE(FieldProductID, v))
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLT(FieldProductID, v))
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v int) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLTE(FieldProductID, v))
}

// ProductIDIsNil applies the IsNil predicate on the "product_id" field.
func ProductIDIsNil() predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIsNull(FieldProductID))
}

// ProductIDNotNil applies the NotNil predicate on the "product_id" field.
func ProductIDNotNil() predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotNull(FieldProductID))
}

// ProductCodeEQ applies the EQ predicate on the "product_code" field.
func ProductCodeEQ(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldProductCode, v))
}

// ProductCodeNEQ applies the NEQ predicate on the "product_code" field.
func ProductCodeNEQ(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNEQ(FieldProductCode, v))
}

// ProductCodeIn applies the In predicate on the "product_code" field.
func ProductCodeIn(vs ...string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIn(FieldProductCode, vs...))
}

// ProductCodeNotIn applies the NotIn predicate on the "product_code" field.
func ProductCodeNotIn(vs ...string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotIn(FieldProductCode, vs...))
}

// ProductCodeGT applies the GT predicate on the "product_code" field.
func ProductCodeGT(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGT(FieldProductCode, v))
}

// ProductCodeGTE applies the GTE predicate on the "product_code" field.
func ProductCodeGTE(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGTE(FieldProductCode, v))
}

// ProductCodeLT applies the LT predicate on the "product_code" field.
func ProductCodeLT(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLT(FieldProductCode, v))
}

// ProductCodeLTE applies the LTE predicate on the "product_code" field.
func ProductCodeLTE(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLTE(FieldProductCode, v))
}

// ProductCodeContains applies the Contains predicate on the "product_code" field.
func ProductCodeContains(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldContains(FieldProductCode, v))
}

// ProductCodeHasPrefix applies the HasPrefix predicate on the "product_code" field.
func ProductCodeHasPrefix(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldHasPrefix(FieldProductCode, v))
}

// ProductCodeHasSuffix applies the HasSuffix predicate on the "product_code" field.
func ProductCodeHasSuffix(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldHasSuffix(FieldProductCode, v))
}

// ProductCodeIsNil applies the IsNil predicate on the "product_code" field.
func ProductCodeIsNil() predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIsNull(FieldProductCode))
}

// ProductCodeNotNil applies the NotNil predicate on the "product_code" field.
func ProductCodeNotNil() predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotNull(FieldProductCode))
}

// ProductCodeEqualFold applies the EqualFold predicate on the "product_code" field.
func ProductCodeEqualFold(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEqualFold(FieldProductCode, v))
}

// ProductCodeContainsFold applies the ContainsFold predicate on the "product_code" field.
func ProductCodeContainsFold(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldContainsFold(FieldProductCode, v))
}

// ProductNameEQ applies the EQ predicate on the "product_name" field.
func ProductNameEQ(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldProductName, v))
}

// ProductNameNEQ applies the NEQ predicate on the "product_name" field.
func ProductNameNEQ(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNEQ(FieldProductName, v))
}

// ProductNameIn applies the In predicate on the "product_name" field.
func ProductNameIn(vs ...string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIn(FieldProductName, vs...))
}

// ProductNameNotIn applies the NotIn predicate on the "product_name" field.
func ProductNameNotIn(vs ...string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotIn(FieldProductName, vs...))
}

// ProductNameGT applies the GT predicate on the "product_name" field.
func ProductNameGT(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGT(FieldProductName, v))
}

// ProductNameGTE applies the GTE predicate on the "product_name" field.
func ProductNameGTE(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGTE(FieldProductName, v))
}

// ProductNameLT applies the LT predicate on the "product_name" field.
func ProductNameLT(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLT(FieldProductName, v))
}

// ProductNameLTE applies the LTE predicate on the "product_name" field.
func ProductNameLTE(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLTE(FieldProductName, v))
}

// ProductNameContains applies the Contains predicate on the "product_name" field.
func ProductNameContains(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldContains(FieldProductName, v))
}

// ProductNameHasPrefix applies the HasPrefix predicate on the "product_name" field.
func ProductNameHasPrefix(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldHasPrefix(FieldProductName, v))
}

// ProductNameHasSuffix applies the HasSuffix predicate on the "product_name" field.
func ProductNameHasSuffix(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldHasSuffix(FieldProductName, v))
}

// ProductNameIsNil applies the IsNil predicate on the "product_name" field.
func ProductNameIsNil() predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIsNull(FieldProductName))
}

// ProductNameNotNil applies the NotNil predicate on the "product_name" field.
func ProductNameNotNil() predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotNull(FieldProductName))
}

// ProductNameEqualFold applies the EqualFold predicate on the "product_name" field.
func ProductNameEqualFold(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEqualFold(FieldProductName, v))
}

// ProductNameContainsFold applies the ContainsFold predicate on the "product_name" field.
func ProductNameContainsFold(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldContainsFold(FieldProductName, v))
}

// SpecCodeEQ applies the EQ predicate on the "spec_code" field.
func SpecCodeEQ(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldSpecCode, v))
}

// SpecCodeNEQ applies the NEQ predicate on the "spec_code" field.
func SpecCodeNEQ(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNEQ(FieldSpecCode, v))
}

// SpecCodeIn applies the In predicate on the "spec_code" field.
func SpecCodeIn(vs ...string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIn(FieldSpecCode, vs...))
}

// SpecCodeNotIn applies the NotIn predicate on the "spec_code" field.
func SpecCodeNotIn(vs ...string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotIn(FieldSpecCode, vs...))
}

// SpecCodeGT applies the GT predicate on the "spec_code" field.
func SpecCodeGT(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGT(FieldSpecCode, v))
}

// SpecCodeGTE applies the GTE predicate on the "spec_code" field.
func SpecCodeGTE(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGTE(FieldSpecCode, v))
}

// SpecCodeLT applies the LT predicate on the "spec_code" field.
func SpecCodeLT(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLT(FieldSpecCode, v))
}

// SpecCodeLTE applies the LTE predicate on the "spec_code" field.
func SpecCodeLTE(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLTE(FieldSpecCode, v))
}

// SpecCodeContains applies the Contains predicate on the "spec_code" field.
func SpecCodeContains(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldContains(FieldSpecCode, v))
}

// SpecCodeHasPrefix applies the HasPrefix predicate on the "spec_code" field.
func SpecCodeHasPrefix(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldHasPrefix(FieldSpecCode, v))
}

// SpecCodeHasSuffix applies the HasSuffix predicate on the "spec_code" field.
func SpecCodeHasSuffix(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldHasSuffix(FieldSpecCode, v))
}

// SpecCodeIsNil applies the IsNil predicate on the "spec_code" field.
func SpecCodeIsNil() predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIsNull(FieldSpecCode))
}

// SpecCodeNotNil applies the NotNil predicate on the "spec_code" field.
func SpecCodeNotNil() predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotNull(FieldSpecCode))
}

// SpecCodeEqualFold applies the EqualFold predicate on the "spec_code" field.
func SpecCodeEqualFold(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEqualFold(FieldSpecCode, v))
}

// SpecCodeContainsFold applies the ContainsFold predicate on the "spec_code" field.
func SpecCodeContainsFold(v string) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldContainsFold(FieldSpecCode, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLTE(FieldQuantity, v))
}

// UnitPriceEQ applies the EQ predicate on the "unit_price" field.
func UnitPriceEQ(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldUnitPrice, v))
}

// UnitPriceNEQ applies the NEQ predicate on the "unit_price" field.
func UnitPriceNEQ(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNEQ(FieldUnitPrice, v))
}

// UnitPriceIn applies the In predicate on the "unit_price" field.
func UnitPriceIn(vs ...float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIn(FieldUnitPrice, vs...))
}

// UnitPriceNotIn applies the NotIn predicate on the "unit_price" field.
func UnitPriceNotIn(vs ...float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotIn(FieldUnitPrice, vs...))
}

// UnitPriceGT applies the GT predicate on the "unit_price" field.
func UnitPriceGT(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGT(FieldUnitPrice, v))
}

// UnitPriceGTE applies the GTE predicate on the "unit_price" field.
func UnitPriceGTE(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGTE(FieldUnitPrice, v))
}

// UnitPriceLT applies the LT predicate on the "unit_price" field.
func UnitPriceLT(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLT(FieldUnitPrice, v))
}

// UnitPriceLTE applies the LTE predicate on the "unit_price" field.
func UnitPriceLTE(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLTE(FieldUnitPrice, v))
}

// TotalPriceEQ applies the EQ predicate on the "total_price" field.
func TotalPriceEQ(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldTotalPrice, v))
}

// TotalPriceNEQ applies the NEQ predicate on the "total_price" field.
func TotalPriceNEQ(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNEQ(FieldTotalPrice, v))
}

// TotalPriceIn applies the In predicate on the "total_price" field.
func TotalPriceIn(vs ...float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIn(FieldTotalPrice, vs...))
}

// TotalPriceNotIn applies the NotIn predicate on the "total_price" field.
func TotalPriceNotIn(vs ...float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotIn(FieldTotalPrice, vs...))
}

// TotalPriceGT applies the GT predicate on the "total_price" field.
func TotalPriceGT(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGT(FieldTotalPrice, v))
}

// TotalPriceGTE applies the GTE predicate on the "total_price" field.
func TotalPriceGTE(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGTE(FieldTotalPrice, v))
}

// TotalPriceLT applies the LT predicate on the "total_price" field.
func TotalPriceLT(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLT(FieldTotalPrice, v))
}

// TotalPriceLTE applies the LTE predicate on the "total_price" field.
func TotalPriceLTE(v float64) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLTE(FieldTotalPrice, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ERPPurchaseContractItem) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ERPPurchaseContractItem) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ERPPurchaseContractItem) predicate.ERPPurchaseContractItem {
	return predicate.ERPPurchaseContractItem(sql.NotPredicates(p))
}
