// Code generated by ent, DO NOT EDIT.

package erpquotationitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the erpquotationitem type in the database.
	Label = "erp_quotation_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuotationID holds the string denoting the quotation_id field in the database.
	FieldQuotationID = "quotation_id"
	// FieldLineNo holds the string denoting the line_no field in the database.
	FieldLineNo = "line_no"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldProductCode holds the string denoting the product_code field in the database.
	FieldProductCode = "product_code"
	// FieldProductName holds the string denoting the product_name field in the database.
	FieldProductName = "product_name"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldUnitPrice holds the string denoting the unit_price field in the database.
	FieldUnitPrice = "unit_price"
	// FieldTotalPrice holds the string denoting the total_price field in the database.
	FieldTotalPrice = "total_price"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the erpquotationitem in the database.
	Table = "erp_quotation_items"
)

// Columns holds all SQL columns for erpquotationitem fields.
var Columns = []string{
	FieldID,
	FieldQuotationID,
	FieldLineNo,
	FieldProductID,
	FieldProductCode,
	FieldProductName,
	FieldQuantity,
	FieldUnitPrice,
	FieldTotalPrice,
	FieldRemark,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// QuotationIDValidator is a validator for the "quotation_id" field. It is called by the builders before save.
	QuotationIDValidator func(int) error
	// LineNoValidator is a validator for the "line_no" field. It is called by the builders before save.
	LineNoValidator func(int) error
	// ProductCodeValidator is a validator for the "product_code" field. It is called by the builders before save.
	ProductCodeValidator func(string) error
	// ProductNameValidator is a validator for the "product_name" field. It is called by the builders before save.
	ProductNameValidator func(string) error
	// DefaultQuantity holds the default value on creation for the "quantity" field.
	DefaultQuantity float64
	// DefaultUnitPrice holds the default value on creation for the "unit_price" field.
	DefaultUnitPrice float64
	// DefaultTotalPrice holds the default value on creation for the "total_price" field.
	DefaultTotalPrice float64
	// RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	RemarkValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ERPQuotationItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByQuotationID orders the results by the quotation_id field.
func ByQuotationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotationID, opts...).ToFunc()
}

// ByLineNo orders the results by the line_no field.
func ByLineNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLineNo, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByProductCode orders the results by the product_code field.
func ByProductCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductCode, opts...).ToFunc()
}

// ByProductName orders the results by the product_name field.
func ByProductName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductName, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByUnitPrice orders the results by the unit_price field.
func ByUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitPrice, opts...).ToFunc()
}

// ByTotalPrice orders the results by the total_price field.
func ByTotalPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalPrice, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
