// Code generated by ent, DO NOT EDIT.

package erpoutboundorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the erpoutboundorder type in the database.
	Label = "erp_outbound_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldShipmentDetailID holds the string denoting the shipment_detail_id field in the database.
	FieldShipmentDetailID = "shipment_detail_id"
	// FieldSourceShipmentCode holds the string denoting the source_shipment_code field in the database.
	FieldSourceShipmentCode = "source_shipment_code"
	// FieldWarehouseID holds the string denoting the warehouse_id field in the database.
	FieldWarehouseID = "warehouse_id"
	// FieldLocationID holds the string denoting the location_id field in the database.
	FieldLocationID = "location_id"
	// FieldOutboundDate holds the string denoting the outbound_date field in the database.
	FieldOutboundDate = "outbound_date"
	// FieldTotalQuantity holds the string denoting the total_quantity field in the database.
	FieldTotalQuantity = "total_quantity"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldCreatedByAdminID holds the string denoting the created_by_admin_id field in the database.
	FieldCreatedByAdminID = "created_by_admin_id"
	// FieldUpdatedByAdminID holds the string denoting the updated_by_admin_id field in the database.
	FieldUpdatedByAdminID = "updated_by_admin_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the erpoutboundorder in the database.
	Table = "erp_outbound_orders"
)

// Columns holds all SQL columns for erpoutboundorder fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldShipmentDetailID,
	FieldSourceShipmentCode,
	FieldWarehouseID,
	FieldLocationID,
	FieldOutboundDate,
	FieldTotalQuantity,
	FieldStatus,
	FieldRemark,
	FieldCreatedByAdminID,
	FieldUpdatedByAdminID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// SourceShipmentCodeValidator is a validator for the "source_shipment_code" field. It is called by the builders before save.
	SourceShipmentCodeValidator func(string) error
	// DefaultTotalQuantity holds the default value on creation for the "total_quantity" field.
	DefaultTotalQuantity float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	RemarkValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ERPOutboundOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByShipmentDetailID orders the results by the shipment_detail_id field.
func ByShipmentDetailID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShipmentDetailID, opts...).ToFunc()
}

// BySourceShipmentCode orders the results by the source_shipment_code field.
func BySourceShipmentCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceShipmentCode, opts...).ToFunc()
}

// ByWarehouseID orders the results by the warehouse_id field.
func ByWarehouseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWarehouseID, opts...).ToFunc()
}

// ByLocationID orders the results by the location_id field.
func ByLocationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocationID, opts...).ToFunc()
}

// ByOutboundDate orders the results by the outbound_date field.
func ByOutboundDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutboundDate, opts...).ToFunc()
}

// ByTotalQuantity orders the results by the total_quantity field.
func ByTotalQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalQuantity, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByCreatedByAdminID orders the results by the created_by_admin_id field.
func ByCreatedByAdminID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByAdminID, opts...).ToFunc()
}

// ByUpdatedByAdminID orders the results by the updated_by_admin_id field.
func ByUpdatedByAdminID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedByAdminID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
