// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"server/internal/data/model/ent/erpattachment"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ERPAttachment is the model entity for the ERPAttachment schema.
type ERPAttachment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// BizModule holds the value of the "biz_module" field.
	BizModule string `json:"biz_module,omitempty"`
	// BizCode holds the value of the "biz_code" field.
	BizCode string `json:"biz_code,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName string `json:"file_name,omitempty"`
	// FileURL holds the value of the "file_url" field.
	FileURL string `json:"file_url,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType *string `json:"mime_type,omitempty"`
	// FileSize holds the value of the "file_size" field.
	FileSize int64 `json:"file_size,omitempty"`
	// UploadedByAdminID holds the value of the "uploaded_by_admin_id" field.
	UploadedByAdminID *int `json:"uploaded_by_admin_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ERPAttachment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case erpattachment.FieldID, erpattachment.FieldFileSize, erpattachment.FieldUploadedByAdminID:
			values[i] = new(sql.NullInt64)
		case erpattachment.FieldCategory, erpattachment.FieldBizModule, erpattachment.FieldBizCode, erpattachment.FieldFileName, erpattachment.FieldFileURL, erpattachment.FieldMimeType:
			values[i] = new(sql.NullString)
		case erpattachment.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ERPAttachment fields.
func (_m *ERPAttachment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case erpattachment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case erpattachment.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case erpattachment.FieldBizModule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field biz_module", values[i])
			} else if value.Valid {
				_m.BizModule = value.String
			}
		case erpattachment.FieldBizCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field biz_code", values[i])
			} else if value.Valid {
				_m.BizCode = value.String
			}
		case erpattachment.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				_m.FileName = value.String
			}
		case erpattachment.FieldFileURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_url", values[i])
			} else if value.Valid {
				_m.FileURL = value.String
			}
		case erpattachment.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = new(string)
				*_m.MimeType = value.String
			}
		case erpattachment.FieldFileSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[i])
			} else if value.Valid {
				_m.FileSize = value.Int64
			}
		case erpattachment.FieldUploadedByAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uploaded_by_admin_id", values[i])
			} else if value.Valid {
				_m.UploadedByAdminID = new(int)
				*_m.UploadedByAdminID = int(value.Int64)
			}
		case erpattachment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ERPAttachment.
// This includes values selected through modifiers, order, etc.
func (_m *ERPAttachment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ERPAttachment.
// Note that you need to call ERPAttachment.Unwrap() before calling this method if this ERPAttachment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ERPAttachment) Update() *ERPAttachmentUpdateOne {
	return NewERPAttachmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ERPAttachment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ERPAttachment) Unwrap() *ERPAttachment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ERPAttachment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ERPAttachment) String() string {
	var builder strings.Builder
	builder.WriteString("ERPAttachment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("biz_module=")
	builder.WriteString(_m.BizModule)
	builder.WriteString(", ")
	builder.WriteString("biz_code=")
	builder.WriteString(_m.BizCode)
	builder.WriteString(", ")
	builder.WriteString("file_name=")
	builder.WriteString(_m.FileName)
	builder.WriteString(", ")
	builder.WriteString("file_url=")
	builder.WriteString(_m.FileURL)
	builder.WriteString(", ")
	if v := _m.MimeType; v != nil {
		builder.WriteString("mime_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("file_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSize))
	builder.WriteString(", ")
	if v := _m.UploadedByAdminID; v != nil {
		builder.WriteString("uploaded_by_admin_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ERPAttachments is a parsable slice of ERPAttachment.
type ERPAttachments []*ERPAttachment
