// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/erpattachment"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ERPAttachmentCreate is the builder for creating a ERPAttachment entity.
type ERPAttachmentCreate struct {
	config
	mutation *ERPAttachmentMutation
	hooks    []Hook
}

// SetCategory sets the "category" field.
func (_c *ERPAttachmentCreate) SetCategory(v string) *ERPAttachmentCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *ERPAttachmentCreate) SetNillableCategory(v *string) *ERPAttachmentCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetBizModule sets the "biz_module" field.
func (_c *ERPAttachmentCreate) SetBizModule(v string) *ERPAttachmentCreate {
	_c.mutation.SetBizModule(v)
	return _c
}

// SetBizCode sets the "biz_code" field.
func (_c *ERPAttachmentCreate) SetBizCode(v string) *ERPAttachmentCreate {
	_c.mutation.SetBizCode(v)
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *ERPAttachmentCreate) SetFileName(v string) *ERPAttachmentCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetFileURL sets the "file_url" field.
func (_c *ERPAttachmentCreate) SetFileURL(v string) *ERPAttachmentCreate {
	_c.mutation.SetFileURL(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *ERPAttachmentCreate) SetMimeType(v string) *ERPAttachmentCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_c *ERPAttachmentCreate) SetNillableMimeType(v *string) *ERPAttachmentCreate {
	if v != nil {
		_c.SetMimeType(*v)
	}
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *ERPAttachmentCreate) SetFileSize(v int64) *ERPAttachmentCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_c *ERPAttachmentCreate) SetNillableFileSize(v *int64) *ERPAttachmentCreate {
	if v != nil {
		_c.SetFileSize(*v)
	}
	return _c
}

// SetUploadedByAdminID sets the "uploaded_by_admin_id" field.
func (_c *ERPAttachmentCreate) SetUploadedByAdminID(v int) *ERPAttachmentCreate {
	_c.mutation.SetUploadedByAdminID(v)
	return _c
}

// SetNillableUploadedByAdminID sets the "uploaded_by_admin_id" field if the given value is not nil.
func (_c *ERPAttachmentCreate) SetNillableUploadedByAdminID(v *int) *ERPAttachmentCreate {
	if v != nil {
		_c.SetUploadedByAdminID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ERPAttachmentCreate) SetCreatedAt(v time.Time) *ERPAttachmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ERPAttachmentCreate) SetNillableCreatedAt(v *time.Time) *ERPAttachmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ERPAttachmentMutation object of the builder.
func (_c *ERPAttachmentCreate) Mutation() *ERPAttachmentMutation {
	return _c.mutation
}

// Save creates the ERPAttachment in the database.
func (_c *ERPAttachmentCreate) Save(ctx context.Context) (*ERPAttachment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ERPAttachmentCreate) SaveX(ctx context.Context) *ERPAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ERPAttachmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ERPAttachmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ERPAttachmentCreate) defaults() {
	if _, ok := _c.mutation.Category(); !ok {
		v := erpattachment.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		v := erpattachment.DefaultFileSize
		_c.mutation.SetFileSize(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := erpattachment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ERPAttachmentCreate) check() error {
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "ERPAttachment.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := erpattachment.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BizModule(); !ok {
		return &ValidationError{Name: "biz_module", err: errors.New(`ent: missing required field "ERPAttachment.biz_module"`)}
	}
	if v, ok := _c.mutation.BizModule(); ok {
		if err := erpattachment.BizModuleValidator(v); err != nil {
			return &ValidationError{Name: "biz_module", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.biz_module": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BizCode(); !ok {
		return &ValidationError{Name: "biz_code", err: errors.New(`ent: missing required field "ERPAttachment.biz_code"`)}
	}
	if v, ok := _c.mutation.BizCode(); ok {
		if err := erpattachment.BizCodeValidator(v); err != nil {
			return &ValidationError{Name: "biz_code", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.biz_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "ERPAttachment.file_name"`)}
	}
	if v, ok := _c.mutation.FileName(); ok {
		if err := erpattachment.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.file_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileURL(); !ok {
		return &ValidationError{Name: "file_url", err: errors.New(`ent: missing required field "ERPAttachment.file_url"`)}
	}
	if v, ok := _c.mutation.FileURL(); ok {
		if err := erpattachment.FileURLValidator(v); err != nil {
			return &ValidationError{Name: "file_url", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.file_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := erpattachment.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`ent: missing required field "ERPAttachment.file_size"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ERPAttachment.created_at"`)}
	}
	return nil
}

func (_c *ERPAttachmentCreate) sqlSave(ctx context.Context) (*ERPAttachment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ERPAttachmentCreate) createSpec() (*ERPAttachment, *sqlgraph.CreateSpec) {
	var (
		_node = &ERPAttachment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(erpattachment.Table, sqlgraph.NewFieldSpec(erpattachment.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(erpattachment.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.BizModule(); ok {
		_spec.SetField(erpattachment.FieldBizModule, field.TypeString, value)
		_node.BizModule = value
	}
	if value, ok := _c.mutation.BizCode(); ok {
		_spec.SetField(erpattachment.FieldBizCode, field.TypeString, value)
		_node.BizCode = value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(erpattachment.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.FileURL(); ok {
		_spec.SetField(erpattachment.FieldFileURL, field.TypeString, value)
		_node.FileURL = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(erpattachment.FieldMimeType, field.TypeString, value)
		_node.MimeType = &value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(erpattachment.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.UploadedByAdminID(); ok {
		_spec.SetField(erpattachment.FieldUploadedByAdminID, field.TypeInt, value)
		_node.UploadedByAdminID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(erpattachment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ERPAttachmentCreateBulk is the builder for creating many ERPAttachment entities in bulk.
type ERPAttachmentCreateBulk struct {
	config
	err      error
	builders []*ERPAttachmentCreate
}

// Save creates the ERPAttachment entities in the database.
func (_c *ERPAttachmentCreateBulk) Save(ctx context.Context) ([]*ERPAttachment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ERPAttachment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ERPAttachmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ERPAttachmentCreateBulk) SaveX(ctx context.Context) []*ERPAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ERPAttachmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ERPAttachmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
