// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/erpattachment"
	"server/internal/data/model/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ERPAttachmentUpdate is the builder for updating ERPAttachment entities.
type ERPAttachmentUpdate struct {
	config
	hooks    []Hook
	mutation *ERPAttachmentMutation
}

// Where appends a list predicates to the ERPAttachmentUpdate builder.
func (_u *ERPAttachmentUpdate) Where(ps ...predicate.ERPAttachment) *ERPAttachmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCategory sets the "category" field.
func (_u *ERPAttachmentUpdate) SetCategory(v string) *ERPAttachmentUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ERPAttachmentUpdate) SetNillableCategory(v *string) *ERPAttachmentUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetBizModule sets the "biz_module" field.
func (_u *ERPAttachmentUpdate) SetBizModule(v string) *ERPAttachmentUpdate {
	_u.mutation.SetBizModule(v)
	return _u
}

// SetNillableBizModule sets the "biz_module" field if the given value is not nil.
func (_u *ERPAttachmentUpdate) SetNillableBizModule(v *string) *ERPAttachmentUpdate {
	if v != nil {
		_u.SetBizModule(*v)
	}
	return _u
}

// SetBizCode sets the "biz_code" field.
func (_u *ERPAttachmentUpdate) SetBizCode(v string) *ERPAttachmentUpdate {
	_u.mutation.SetBizCode(v)
	return _u
}

// SetNillableBizCode sets the "biz_code" field if the given value is not nil.
func (_u *ERPAttachmentUpdate) SetNillableBizCode(v *string) *ERPAttachmentUpdate {
	if v != nil {
		_u.SetBizCode(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *ERPAttachmentUpdate) SetFileName(v string) *ERPAttachmentUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *ERPAttachmentUpdate) SetNillableFileName(v *string) *ERPAttachmentUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileURL sets the "file_url" field.
func (_u *ERPAttachmentUpdate) SetFileURL(v string) *ERPAttachmentUpdate {
	_u.mutation.SetFileURL(v)
	return _u
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_u *ERPAttachmentUpdate) SetNillableFileURL(v *string) *ERPAttachmentUpdate {
	if v != nil {
		_u.SetFileURL(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ERPAttachmentUpdate) SetMimeType(v string) *ERPAttachmentUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ERPAttachmentUpdate) SetNillableMimeType(v *string) *ERPAttachmentUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// ClearMimeType clears the value of the "mime_type" field.
func (_u *ERPAttachmentUpdate) ClearMimeType() *ERPAttachmentUpdate {
	_u.mutation.ClearMimeType()
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *ERPAttachmentUpdate) SetFileSize(v int64) *ERPAttachmentUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *ERPAttachmentUpdate) SetNillableFileSize(v *int64) *ERPAttachmentUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *ERPAttachmentUpdate) AddFileSize(v int64) *ERPAttachmentUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetUploadedByAdminID sets the "uploaded_by_admin_id" field.
func (_u *ERPAttachmentUpdate) SetUploadedByAdminID(v int) *ERPAttachmentUpdate {
	_u.mutation.ResetUploadedByAdminID()
	_u.mutation.SetUploadedByAdminID(v)
	return _u
}

// SetNillableUploadedByAdminID sets the "uploaded_by_admin_id" field if the given value is not nil.
func (_u *ERPAttachmentUpdate) SetNillableUploadedByAdminID(v *int) *ERPAttachmentUpdate {
	if v != nil {
		_u.SetUploadedByAdminID(*v)
	}
	return _u
}

// AddUploadedByAdminID adds value to the "uploaded_by_admin_id" field.
func (_u *ERPAttachmentUpdate) AddUploadedByAdminID(v int) *ERPAttachmentUpdate {
	_u.mutation.AddUploadedByAdminID(v)
	return _u
}

// ClearUploadedByAdminID clears the value of the "uploaded_by_admin_id" field.
func (_u *ERPAttachmentUpdate) ClearUploadedByAdminID() *ERPAttachmentUpdate {
	_u.mutation.ClearUploadedByAdminID()
	return _u
}

// Mutation returns the ERPAttachmentMutation object of the builder.
func (_u *ERPAttachmentUpdate) Mutation() *ERPAttachmentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ERPAttachmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ERPAttachmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ERPAttachmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ERPAttachmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ERPAttachmentUpdate) check() error {
	if v, ok := _u.mutation.Category(); ok {
		if err := erpattachment.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BizModule(); ok {
		if err := erpattachment.BizModuleValidator(v); err != nil {
			return &ValidationError{Name: "biz_module", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.biz_module": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BizCode(); ok {
		if err := erpattachment.BizCodeValidator(v); err != nil {
			return &ValidationError{Name: "biz_code", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.biz_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := erpattachment.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileURL(); ok {
		if err := erpattachment.FileURLValidator(v); err != nil {
			return &ValidationError{Name: "file_url", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.file_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := erpattachment.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.mime_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ERPAttachmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(erpattachment.Table, erpattachment.Columns, sqlgraph.NewFieldSpec(erpattachment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(erpattachment.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.BizModule(); ok {
		_spec.SetField(erpattachment.FieldBizModule, field.TypeString, value)
	}
	if value, ok := _u.mutation.BizCode(); ok {
		_spec.SetField(erpattachment.FieldBizCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(erpattachment.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileURL(); ok {
		_spec.SetField(erpattachment.FieldFileURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(erpattachment.FieldMimeType, field.TypeString, value)
	}
	if _u.mutation.MimeTypeCleared() {
		_spec.ClearField(erpattachment.FieldMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(erpattachment.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(erpattachment.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UploadedByAdminID(); ok {
		_spec.SetField(erpattachment.FieldUploadedByAdminID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUploadedByAdminID(); ok {
		_spec.AddField(erpattachment.FieldUploadedByAdminID, field.TypeInt, value)
	}
	if _u.mutation.UploadedByAdminIDCleared() {
		_spec.ClearField(erpattachment.FieldUploadedByAdminID, field.TypeInt)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{erpattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ERPAttachmentUpdateOne is the builder for updating a single ERPAttachment entity.
type ERPAttachmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ERPAttachmentMutation
}

// SetCategory sets the "category" field.
func (_u *ERPAttachmentUpdateOne) SetCategory(v string) *ERPAttachmentUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ERPAttachmentUpdateOne) SetNillableCategory(v *string) *ERPAttachmentUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetBizModule sets the "biz_module" field.
func (_u *ERPAttachmentUpdateOne) SetBizModule(v string) *ERPAttachmentUpdateOne {
	_u.mutation.SetBizModule(v)
	return _u
}

// SetNillableBizModule sets the "biz_module" field if the given value is not nil.
func (_u *ERPAttachmentUpdateOne) SetNillableBizModule(v *string) *ERPAttachmentUpdateOne {
	if v != nil {
		_u.SetBizModule(*v)
	}
	return _u
}

// SetBizCode sets the "biz_code" field.
func (_u *ERPAttachmentUpdateOne) SetBizCode(v string) *ERPAttachmentUpdateOne {
	_u.mutation.SetBizCode(v)
	return _u
}

// SetNillableBizCode sets the "biz_code" field if the given value is not nil.
func (_u *ERPAttachmentUpdateOne) SetNillableBizCode(v *string) *ERPAttachmentUpdateOne {
	if v != nil {
		_u.SetBizCode(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *ERPAttachmentUpdateOne) SetFileName(v string) *ERPAttachmentUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *ERPAttachmentUpdateOne) SetNillableFileName(v *string) *ERPAttachmentUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileURL sets the "file_url" field.
func (_u *ERPAttachmentUpdateOne) SetFileURL(v string) *ERPAttachmentUpdateOne {
	_u.mutation.SetFileURL(v)
	return _u
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_u *ERPAttachmentUpdateOne) SetNillableFileURL(v *string) *ERPAttachmentUpdateOne {
	if v != nil {
		_u.SetFileURL(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ERPAttachmentUpdateOne) SetMimeType(v string) *ERPAttachmentUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ERPAttachmentUpdateOne) SetNillableMimeType(v *string) *ERPAttachmentUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// ClearMimeType clears the value of the "mime_type" field.
func (_u *ERPAttachmentUpdateOne) ClearMimeType() *ERPAttachmentUpdateOne {
	_u.mutation.ClearMimeType()
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *ERPAttachmentUpdateOne) SetFileSize(v int64) *ERPAttachmentUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *ERPAttachmentUpdateOne) SetNillableFileSize(v *int64) *ERPAttachmentUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *ERPAttachmentUpdateOne) AddFileSize(v int64) *ERPAttachmentUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetUploadedByAdminID sets the "uploaded_by_admin_id" field.
func (_u *ERPAttachmentUpdateOne) SetUploadedByAdminID(v int) *ERPAttachmentUpdateOne {
	_u.mutation.ResetUploadedByAdminID()
	_u.mutation.SetUploadedByAdminID(v)
	return _u
}

// SetNillableUploadedByAdminID sets the "uploaded_by_admin_id" field if the given value is not nil.
func (_u *ERPAttachmentUpdateOne) SetNillableUploadedByAdminID(v *int) *ERPAttachmentUpdateOne {
	if v != nil {
		_u.SetUploadedByAdminID(*v)
	}
	return _u
}

// AddUploadedByAdminID adds value to the "uploaded_by_admin_id" field.
func (_u *ERPAttachmentUpdateOne) AddUploadedByAdminID(v int) *ERPAttachmentUpdateOne {
	_u.mutation.AddUploadedByAdminID(v)
	return _u
}

// ClearUploadedByAdminID clears the value of the "uploaded_by_admin_id" field.
func (_u *ERPAttachmentUpdateOne) ClearUploadedByAdminID() *ERPAttachmentUpdateOne {
	_u.mutation.ClearUploadedByAdminID()
	return _u
}

// Mutation returns the ERPAttachmentMutation object of the builder.
func (_u *ERPAttachmentUpdateOne) Mutation() *ERPAttachmentMutation {
	return _u.mutation
}

// Where appends a list predicates to the ERPAttachmentUpdate builder.
func (_u *ERPAttachmentUpdateOne) Where(ps ...predicate.ERPAttachment) *ERPAttachmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ERPAttachmentUpdateOne) Select(field string, fields ...string) *ERPAttachmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ERPAttachment entity.
func (_u *ERPAttachmentUpdateOne) Save(ctx context.Context) (*ERPAttachment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ERPAttachmentUpdateOne) SaveX(ctx context.Context) *ERPAttachment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ERPAttachmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ERPAttachmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ERPAttachmentUpdateOne) check() error {
	if v, ok := _u.mutation.Category(); ok {
		if err := erpattachment.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BizModule(); ok {
		if err := erpattachment.BizModuleValidator(v); err != nil {
			return &ValidationError{Name: "biz_module", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.biz_module": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BizCode(); ok {
		if err := erpattachment.BizCodeValidator(v); err != nil {
			return &ValidationError{Name: "biz_code", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.biz_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := erpattachment.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileURL(); ok {
		if err := erpattachment.FileURLValidator(v); err != nil {
			return &ValidationError{Name: "file_url", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.file_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := erpattachment.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ERPAttachment.mime_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ERPAttachmentUpdateOne) sqlSave(ctx context.Context) (_node *ERPAttachment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(erpattachment.Table, erpattachment.Columns, sqlgraph.NewFieldSpec(erpattachment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ERPAttachment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, erpattachment.FieldID)
		for _, f := range fields {
			if !erpattachment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != erpattachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(erpattachment.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.BizModule(); ok {
		_spec.SetField(erpattachment.FieldBizModule, field.TypeString, value)
	}
	if value, ok := _u.mutation.BizCode(); ok {
		_spec.SetField(erpattachment.FieldBizCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(erpattachment.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileURL(); ok {
		_spec.SetField(erpattachment.FieldFileURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(erpattachment.FieldMimeType, field.TypeString, value)
	}
	if _u.mutation.MimeTypeCleared() {
		_spec.ClearField(erpattachment.FieldMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(erpattachment.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(erpattachment.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UploadedByAdminID(); ok {
		_spec.SetField(erpattachment.FieldUploadedByAdminID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUploadedByAdminID(); ok {
		_spec.AddField(erpattachment.FieldUploadedByAdminID, field.TypeInt, value)
	}
	if _u.mutation.UploadedByAdminIDCleared() {
		_spec.ClearField(erpattachment.FieldUploadedByAdminID, field.TypeInt)
	}
	_node = &ERPAttachment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{erpattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
