// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"server/internal/data/model/ent/erpattachment"
	"server/internal/data/model/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ERPAttachmentDelete is the builder for deleting a ERPAttachment entity.
type ERPAttachmentDelete struct {
	config
	hooks    []Hook
	mutation *ERPAttachmentMutation
}

// Where appends a list predicates to the ERPAttachmentDelete builder.
func (_d *ERPAttachmentDelete) Where(ps ...predicate.ERPAttachment) *ERPAttachmentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ERPAttachmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ERPAttachmentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ERPAttachmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(erpattachment.Table, sqlgraph.NewFieldSpec(erpattachment.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ERPAttachmentDeleteOne is the builder for deleting a single ERPAttachment entity.
type ERPAttachmentDeleteOne struct {
	_d *ERPAttachmentDelete
}

// Where appends a list predicates to the ERPAttachmentDelete builder.
func (_d *ERPAttachmentDeleteOne) Where(ps ...predicate.ERPAttachment) *ERPAttachmentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ERPAttachmentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{erpattachment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ERPAttachmentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
