// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"server/internal/data/model/ent/erpbankreceipt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ERPBankReceipt is the model entity for the ERPBankReceipt schema.
type ERPBankReceipt struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// RegisterDate holds the value of the "register_date" field.
	RegisterDate time.Time `json:"register_date,omitempty"`
	// FundType holds the value of the "fund_type" field.
	FundType string `json:"fund_type,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// ReceivedAmount holds the value of the "received_amount" field.
	ReceivedAmount float64 `json:"received_amount,omitempty"`
	// BankFee holds the value of the "bank_fee" field.
	BankFee float64 `json:"bank_fee,omitempty"`
	// NetAmount holds the value of the "net_amount" field.
	NetAmount float64 `json:"net_amount,omitempty"`
	// RefNo holds the value of the "ref_no" field.
	RefNo *string `json:"ref_no,omitempty"`
	// claim/confirmed/closed
	Status string `json:"status,omitempty"`
	// CreatedByAdminID holds the value of the "created_by_admin_id" field.
	CreatedByAdminID *int `json:"created_by_admin_id,omitempty"`
	// UpdatedByAdminID holds the value of the "updated_by_admin_id" field.
	UpdatedByAdminID *int `json:"updated_by_admin_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ERPBankReceipt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case erpbankreceipt.FieldReceivedAmount, erpbankreceipt.FieldBankFee, erpbankreceipt.FieldNetAmount:
			values[i] = new(sql.NullFloat64)
		case erpbankreceipt.FieldID, erpbankreceipt.FieldCreatedByAdminID, erpbankreceipt.FieldUpdatedByAdminID:
			values[i] = new(sql.NullInt64)
		case erpbankreceipt.FieldCode, erpbankreceipt.FieldFundType, erpbankreceipt.FieldCurrency, erpbankreceipt.FieldRefNo, erpbankreceipt.FieldStatus:
			values[i] = new(sql.NullString)
		case erpbankreceipt.FieldRegisterDate, erpbankreceipt.FieldCreatedAt, erpbankreceipt.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ERPBankReceipt fields.
func (_m *ERPBankReceipt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case erpbankreceipt.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case erpbankreceipt.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case erpbankreceipt.FieldRegisterDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field register_date", values[i])
			} else if value.Valid {
				_m.RegisterDate = value.Time
			}
		case erpbankreceipt.FieldFundType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fund_type", values[i])
			} else if value.Valid {
				_m.FundType = value.String
			}
		case erpbankreceipt.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case erpbankreceipt.FieldReceivedAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field received_amount", values[i])
			} else if value.Valid {
				_m.ReceivedAmount = value.Float64
			}
		case erpbankreceipt.FieldBankFee:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field bank_fee", values[i])
			} else if value.Valid {
				_m.BankFee = value.Float64
			}
		case erpbankreceipt.FieldNetAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field net_amount", values[i])
			} else if value.Valid {
				_m.NetAmount = value.Float64
			}
		case erpbankreceipt.FieldRefNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ref_no", values[i])
			} else if value.Valid {
				_m.RefNo = new(string)
				*_m.RefNo = value.String
			}
		case erpbankreceipt.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case erpbankreceipt.FieldCreatedByAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_admin_id", values[i])
			} else if value.Valid {
				_m.CreatedByAdminID = new(int)
				*_m.CreatedByAdminID = int(value.Int64)
			}
		case erpbankreceipt.FieldUpdatedByAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by_admin_id", values[i])
			} else if value.Valid {
				_m.UpdatedByAdminID = new(int)
				*_m.UpdatedByAdminID = int(value.Int64)
			}
		case erpbankreceipt.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case erpbankreceipt.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ERPBankReceipt.
// This includes values selected through modifiers, order, etc.
func (_m *ERPBankReceipt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ERPBankReceipt.
// Note that you need to call ERPBankReceipt.Unwrap() before calling this method if this ERPBankReceipt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ERPBankReceipt) Update() *ERPBankReceiptUpdateOne {
	return NewERPBankReceiptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ERPBankReceipt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ERPBankReceipt) Unwrap() *ERPBankReceipt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ERPBankReceipt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ERPBankReceipt) String() string {
	var builder strings.Builder
	builder.WriteString("ERPBankReceipt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("register_date=")
	builder.WriteString(_m.RegisterDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("fund_type=")
	builder.WriteString(_m.FundType)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("received_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReceivedAmount))
	builder.WriteString(", ")
	builder.WriteString("bank_fee=")
	builder.WriteString(fmt.Sprintf("%v", _m.BankFee))
	builder.WriteString(", ")
	builder.WriteString("net_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.NetAmount))
	builder.WriteString(", ")
	if v := _m.RefNo; v != nil {
		builder.WriteString("ref_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.CreatedByAdminID; v != nil {
		builder.WriteString("created_by_admin_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedByAdminID; v != nil {
		builder.WriteString("updated_by_admin_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ERPBankReceipts is a parsable slice of ERPBankReceipt.
type ERPBankReceipts []*ERPBankReceipt
