// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/erpbankreceiptclaim"
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ERPBankReceiptClaimUpdate is the builder for updating ERPBankReceiptClaim entities.
type ERPBankReceiptClaimUpdate struct {
	config
	hooks    []Hook
	mutation *ERPBankReceiptClaimMutation
}

// Where appends a list predicates to the ERPBankReceiptClaimUpdate builder.
func (_u *ERPBankReceiptClaimUpdate) Where(ps ...predicate.ERPBankReceiptClaim) *ERPBankReceiptClaimUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetReceiptID sets the "receipt_id" field.
func (_u *ERPBankReceiptClaimUpdate) SetReceiptID(v int) *ERPBankReceiptClaimUpdate {
	_u.mutation.ResetReceiptID()
	_u.mutation.SetReceiptID(v)
	return _u
}

// SetNillableReceiptID sets the "receipt_id" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdate) SetNillableReceiptID(v *int) *ERPBankReceiptClaimUpdate {
	if v != nil {
		_u.SetReceiptID(*v)
	}
	return _u
}

// AddReceiptID adds value to the "receipt_id" field.
func (_u *ERPBankReceiptClaimUpdate) AddReceiptID(v int) *ERPBankReceiptClaimUpdate {
	_u.mutation.AddReceiptID(v)
	return _u
}

// SetSettlementID sets the "settlement_id" field.
func (_u *ERPBankReceiptClaimUpdate) SetSettlementID(v int) *ERPBankReceiptClaimUpdate {
	_u.mutation.ResetSettlementID()
	_u.mutation.SetSettlementID(v)
	return _u
}

// SetNillableSettlementID sets the "settlement_id" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdate) SetNillableSettlementID(v *int) *ERPBankReceiptClaimUpdate {
	if v != nil {
		_u.SetSettlementID(*v)
	}
	return _u
}

// AddSettlementID adds value to the "settlement_id" field.
func (_u *ERPBankReceiptClaimUpdate) AddSettlementID(v int) *ERPBankReceiptClaimUpdate {
	_u.mutation.AddSettlementID(v)
	return _u
}

// ClearSettlementID clears the value of the "settlement_id" field.
func (_u *ERPBankReceiptClaimUpdate) ClearSettlementID() *ERPBankReceiptClaimUpdate {
	_u.mutation.ClearSettlementID()
	return _u
}

// SetClaimType sets the "claim_type" field.
func (_u *ERPBankReceiptClaimUpdate) SetClaimType(v string) *ERPBankReceiptClaimUpdate {
	_u.mutation.SetClaimType(v)
	return _u
}

// SetNillableClaimType sets the "claim_type" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdate) SetNillableClaimType(v *string) *ERPBankReceiptClaimUpdate {
	if v != nil {
		_u.SetClaimType(*v)
	}
	return _u
}

// SetClaimAmount sets the "claim_amount" field.
func (_u *ERPBankReceiptClaimUpdate) SetClaimAmount(v float64) *ERPBankReceiptClaimUpdate {
	_u.mutation.ResetClaimAmount()
	_u.mutation.SetClaimAmount(v)
	return _u
}

// SetNillableClaimAmount sets the "claim_amount" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdate) SetNillableClaimAmount(v *float64) *ERPBankReceiptClaimUpdate {
	if v != nil {
		_u.SetClaimAmount(*v)
	}
	return _u
}

// AddClaimAmount adds value to the "claim_amount" field.
func (_u *ERPBankReceiptClaimUpdate) AddClaimAmount(v float64) *ERPBankReceiptClaimUpdate {
	_u.mutation.AddClaimAmount(v)
	return _u
}

// SetConfirmed sets the "confirmed" field.
func (_u *ERPBankReceiptClaimUpdate) SetConfirmed(v bool) *ERPBankReceiptClaimUpdate {
	_u.mutation.SetConfirmed(v)
	return _u
}

// SetNillableConfirmed sets the "confirmed" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdate) SetNillableConfirmed(v *bool) *ERPBankReceiptClaimUpdate {
	if v != nil {
		_u.SetConfirmed(*v)
	}
	return _u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_u *ERPBankReceiptClaimUpdate) SetConfirmedAt(v time.Time) *ERPBankReceiptClaimUpdate {
	_u.mutation.SetConfirmedAt(v)
	return _u
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdate) SetNillableConfirmedAt(v *time.Time) *ERPBankReceiptClaimUpdate {
	if v != nil {
		_u.SetConfirmedAt(*v)
	}
	return _u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (_u *ERPBankReceiptClaimUpdate) ClearConfirmedAt() *ERPBankReceiptClaimUpdate {
	_u.mutation.ClearConfirmedAt()
	return _u
}

// SetClaimedByAdminID sets the "claimed_by_admin_id" field.
func (_u *ERPBankReceiptClaimUpdate) SetClaimedByAdminID(v int) *ERPBankReceiptClaimUpdate {
	_u.mutation.ResetClaimedByAdminID()
	_u.mutation.SetClaimedByAdminID(v)
	return _u
}

// SetNillableClaimedByAdminID sets the "claimed_by_admin_id" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdate) SetNillableClaimedByAdminID(v *int) *ERPBankReceiptClaimUpdate {
	if v != nil {
		_u.SetClaimedByAdminID(*v)
	}
	return _u
}

// AddClaimedByAdminID adds value to the "claimed_by_admin_id" field.
func (_u *ERPBankReceiptClaimUpdate) AddClaimedByAdminID(v int) *ERPBankReceiptClaimUpdate {
	_u.mutation.AddClaimedByAdminID(v)
	return _u
}

// ClearClaimedByAdminID clears the value of the "claimed_by_admin_id" field.
func (_u *ERPBankReceiptClaimUpdate) ClearClaimedByAdminID() *ERPBankReceiptClaimUpdate {
	_u.mutation.ClearClaimedByAdminID()
	return _u
}

// SetConfirmedByAdminID sets the "confirmed_by_admin_id" field.
func (_u *ERPBankReceiptClaimUpdate) SetConfirmedByAdminID(v int) *ERPBankReceiptClaimUpdate {
	_u.mutation.ResetConfirmedByAdminID()
	_u.mutation.SetConfirmedByAdminID(v)
	return _u
}

// SetNillableConfirmedByAdminID sets the "confirmed_by_admin_id" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdate) SetNillableConfirmedByAdminID(v *int) *ERPBankReceiptClaimUpdate {
	if v != nil {
		_u.SetConfirmedByAdminID(*v)
	}
	return _u
}

// AddConfirmedByAdminID adds value to the "confirmed_by_admin_id" field.
func (_u *ERPBankReceiptClaimUpdate) AddConfirmedByAdminID(v int) *ERPBankReceiptClaimUpdate {
	_u.mutation.AddConfirmedByAdminID(v)
	return _u
}

// ClearConfirmedByAdminID clears the value of the "confirmed_by_admin_id" field.
func (_u *ERPBankReceiptClaimUpdate) ClearConfirmedByAdminID() *ERPBankReceiptClaimUpdate {
	_u.mutation.ClearConfirmedByAdminID()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ERPBankReceiptClaimUpdate) SetRemark(v string) *ERPBankReceiptClaimUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdate) SetNillableRemark(v *string) *ERPBankReceiptClaimUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ERPBankReceiptClaimUpdate) ClearRemark() *ERPBankReceiptClaimUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ERPBankReceiptClaimUpdate) SetUpdatedAt(v time.Time) *ERPBankReceiptClaimUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ERPBankReceiptClaimMutation object of the builder.
func (_u *ERPBankReceiptClaimUpdate) Mutation() *ERPBankReceiptClaimMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ERPBankReceiptClaimUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ERPBankReceiptClaimUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ERPBankReceiptClaimUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ERPBankReceiptClaimUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ERPBankReceiptClaimUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := erpbankreceiptclaim.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ERPBankReceiptClaimUpdate) check() error {
	if v, ok := _u.mutation.ReceiptID(); ok {
		if err := erpbankreceiptclaim.ReceiptIDValidator(v); err != nil {
			return &ValidationError{Name: "receipt_id", err: fmt.Errorf(`ent: validator failed for field "ERPBankReceiptClaim.receipt_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClaimType(); ok {
		if err := erpbankreceiptclaim.ClaimTypeValidator(v); err != nil {
			return &ValidationError{Name: "claim_type", err: fmt.Errorf(`ent: validator failed for field "ERPBankReceiptClaim.claim_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := erpbankreceiptclaim.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "ERPBankReceiptClaim.remark": %w`, err)}
		}
	}
	return nil
}

func (_u *ERPBankReceiptClaimUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(erpbankreceiptclaim.Table, erpbankreceiptclaim.Columns, sqlgraph.NewFieldSpec(erpbankreceiptclaim.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReceiptID(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldReceiptID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReceiptID(); ok {
		_spec.AddField(erpbankreceiptclaim.FieldReceiptID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SettlementID(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldSettlementID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSettlementID(); ok {
		_spec.AddField(erpbankreceiptclaim.FieldSettlementID, field.TypeInt, value)
	}
	if _u.mutation.SettlementIDCleared() {
		_spec.ClearField(erpbankreceiptclaim.FieldSettlementID, field.TypeInt)
	}
	if value, ok := _u.mutation.ClaimType(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldClaimType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClaimAmount(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldClaimAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedClaimAmount(); ok {
		_spec.AddField(erpbankreceiptclaim.FieldClaimAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Confirmed(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldConfirmed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConfirmedAt(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmedAtCleared() {
		_spec.ClearField(erpbankreceiptclaim.FieldConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClaimedByAdminID(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldClaimedByAdminID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClaimedByAdminID(); ok {
		_spec.AddField(erpbankreceiptclaim.FieldClaimedByAdminID, field.TypeInt, value)
	}
	if _u.mutation.ClaimedByAdminIDCleared() {
		_spec.ClearField(erpbankreceiptclaim.FieldClaimedByAdminID, field.TypeInt)
	}
	if value, ok := _u.mutation.ConfirmedByAdminID(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldConfirmedByAdminID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConfirmedByAdminID(); ok {
		_spec.AddField(erpbankreceiptclaim.FieldConfirmedByAdminID, field.TypeInt, value)
	}
	if _u.mutation.ConfirmedByAdminIDCleared() {
		_spec.ClearField(erpbankreceiptclaim.FieldConfirmedByAdminID, field.TypeInt)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(erpbankreceiptclaim.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{erpbankreceiptclaim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ERPBankReceiptClaimUpdateOne is the builder for updating a single ERPBankReceiptClaim entity.
type ERPBankReceiptClaimUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ERPBankReceiptClaimMutation
}

// SetReceiptID sets the "receipt_id" field.
func (_u *ERPBankReceiptClaimUpdateOne) SetReceiptID(v int) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.ResetReceiptID()
	_u.mutation.SetReceiptID(v)
	return _u
}

// SetNillableReceiptID sets the "receipt_id" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdateOne) SetNillableReceiptID(v *int) *ERPBankReceiptClaimUpdateOne {
	if v != nil {
		_u.SetReceiptID(*v)
	}
	return _u
}

// AddReceiptID adds value to the "receipt_id" field.
func (_u *ERPBankReceiptClaimUpdateOne) AddReceiptID(v int) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.AddReceiptID(v)
	return _u
}

// SetSettlementID sets the "settlement_id" field.
func (_u *ERPBankReceiptClaimUpdateOne) SetSettlementID(v int) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.ResetSettlementID()
	_u.mutation.SetSettlementID(v)
	return _u
}

// SetNillableSettlementID sets the "settlement_id" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdateOne) SetNillableSettlementID(v *int) *ERPBankReceiptClaimUpdateOne {
	if v != nil {
		_u.SetSettlementID(*v)
	}
	return _u
}

// AddSettlementID adds value to the "settlement_id" field.
func (_u *ERPBankReceiptClaimUpdateOne) AddSettlementID(v int) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.AddSettlementID(v)
	return _u
}

// ClearSettlementID clears the value of the "settlement_id" field.
func (_u *ERPBankReceiptClaimUpdateOne) ClearSettlementID() *ERPBankReceiptClaimUpdateOne {
	_u.mutation.ClearSettlementID()
	return _u
}

// SetClaimType sets the "claim_type" field.
func (_u *ERPBankReceiptClaimUpdateOne) SetClaimType(v string) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.SetClaimType(v)
	return _u
}

// SetNillableClaimType sets the "claim_type" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdateOne) SetNillableClaimType(v *string) *ERPBankReceiptClaimUpdateOne {
	if v != nil {
		_u.SetClaimType(*v)
	}
	return _u
}

// SetClaimAmount sets the "claim_amount" field.
func (_u *ERPBankReceiptClaimUpdateOne) SetClaimAmount(v float64) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.ResetClaimAmount()
	_u.mutation.SetClaimAmount(v)
	return _u
}

// SetNillableClaimAmount sets the "claim_amount" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdateOne) SetNillableClaimAmount(v *float64) *ERPBankReceiptClaimUpdateOne {
	if v != nil {
		_u.SetClaimAmount(*v)
	}
	return _u
}

// AddClaimAmount adds value to the "claim_amount" field.
func (_u *ERPBankReceiptClaimUpdateOne) AddClaimAmount(v float64) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.AddClaimAmount(v)
	return _u
}

// SetConfirmed sets the "confirmed" field.
func (_u *ERPBankReceiptClaimUpdateOne) SetConfirmed(v bool) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.SetConfirmed(v)
	return _u
}

// SetNillableConfirmed sets the "confirmed" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdateOne) SetNillableConfirmed(v *bool) *ERPBankReceiptClaimUpdateOne {
	if v != nil {
		_u.SetConfirmed(*v)
	}
	return _u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_u *ERPBankReceiptClaimUpdateOne) SetConfirmedAt(v time.Time) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.SetConfirmedAt(v)
	return _u
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdateOne) SetNillableConfirmedAt(v *time.Time) *ERPBankReceiptClaimUpdateOne {
	if v != nil {
		_u.SetConfirmedAt(*v)
	}
	return _u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (_u *ERPBankReceiptClaimUpdateOne) ClearConfirmedAt() *ERPBankReceiptClaimUpdateOne {
	_u.mutation.ClearConfirmedAt()
	return _u
}

// SetClaimedByAdminID sets the "claimed_by_admin_id" field.
func (_u *ERPBankReceiptClaimUpdateOne) SetClaimedByAdminID(v int) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.ResetClaimedByAdminID()
	_u.mutation.SetClaimedByAdminID(v)
	return _u
}

// SetNillableClaimedByAdminID sets the "claimed_by_admin_id" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdateOne) SetNillableClaimedByAdminID(v *int) *ERPBankReceiptClaimUpdateOne {
	if v != nil {
		_u.SetClaimedByAdminID(*v)
	}
	return _u
}

// AddClaimedByAdminID adds value to the "claimed_by_admin_id" field.
func (_u *ERPBankReceiptClaimUpdateOne) AddClaimedByAdminID(v int) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.AddClaimedByAdminID(v)
	return _u
}

// ClearClaimedByAdminID clears the value of the "claimed_by_admin_id" field.
func (_u *ERPBankReceiptClaimUpdateOne) ClearClaimedByAdminID() *ERPBankReceiptClaimUpdateOne {
	_u.mutation.ClearClaimedByAdminID()
	return _u
}

// SetConfirmedByAdminID sets the "confirmed_by_admin_id" field.
func (_u *ERPBankReceiptClaimUpdateOne) SetConfirmedByAdminID(v int) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.ResetConfirmedByAdminID()
	_u.mutation.SetConfirmedByAdminID(v)
	return _u
}

// SetNillableConfirmedByAdminID sets the "confirmed_by_admin_id" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdateOne) SetNillableConfirmedByAdminID(v *int) *ERPBankReceiptClaimUpdateOne {
	if v != nil {
		_u.SetConfirmedByAdminID(*v)
	}
	return _u
}

// AddConfirmedByAdminID adds value to the "confirmed_by_admin_id" field.
func (_u *ERPBankReceiptClaimUpdateOne) AddConfirmedByAdminID(v int) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.AddConfirmedByAdminID(v)
	return _u
}

// ClearConfirmedByAdminID clears the value of the "confirmed_by_admin_id" field.
func (_u *ERPBankReceiptClaimUpdateOne) ClearConfirmedByAdminID() *ERPBankReceiptClaimUpdateOne {
	_u.mutation.ClearConfirmedByAdminID()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ERPBankReceiptClaimUpdateOne) SetRemark(v string) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ERPBankReceiptClaimUpdateOne) SetNillableRemark(v *string) *ERPBankReceiptClaimUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ERPBankReceiptClaimUpdateOne) ClearRemark() *ERPBankReceiptClaimUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ERPBankReceiptClaimUpdateOne) SetUpdatedAt(v time.Time) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ERPBankReceiptClaimMutation object of the builder.
func (_u *ERPBankReceiptClaimUpdateOne) Mutation() *ERPBankReceiptClaimMutation {
	return _u.mutation
}

// Where appends a list predicates to the ERPBankReceiptClaimUpdate builder.
func (_u *ERPBankReceiptClaimUpdateOne) Where(ps ...predicate.ERPBankReceiptClaim) *ERPBankReceiptClaimUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ERPBankReceiptClaimUpdateOne) Select(field string, fields ...string) *ERPBankReceiptClaimUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ERPBankReceiptClaim entity.
func (_u *ERPBankReceiptClaimUpdateOne) Save(ctx context.Context) (*ERPBankReceiptClaim, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ERPBankReceiptClaimUpdateOne) SaveX(ctx context.Context) *ERPBankReceiptClaim {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ERPBankReceiptClaimUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ERPBankReceiptClaimUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ERPBankReceiptClaimUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := erpbankreceiptclaim.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ERPBankReceiptClaimUpdateOne) check() error {
	if v, ok := _u.mutation.ReceiptID(); ok {
		if err := erpbankreceiptclaim.ReceiptIDValidator(v); err != nil {
			return &ValidationError{Name: "receipt_id", err: fmt.Errorf(`ent: validator failed for field "ERPBankReceiptClaim.receipt_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClaimType(); ok {
		if err := erpbankreceiptclaim.ClaimTypeValidator(v); err != nil {
			return &ValidationError{Name: "claim_type", err: fmt.Errorf(`ent: validator failed for field "ERPBankReceiptClaim.claim_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := erpbankreceiptclaim.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "ERPBankReceiptClaim.remark": %w`, err)}
		}
	}
	return nil
}

func (_u *ERPBankReceiptClaimUpdateOne) sqlSave(ctx context.Context) (_node *ERPBankReceiptClaim, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(erpbankreceiptclaim.Table, erpbankreceiptclaim.Columns, sqlgraph.NewFieldSpec(erpbankreceiptclaim.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ERPBankReceiptClaim.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, erpbankreceiptclaim.FieldID)
		for _, f := range fields {
			if !erpbankreceiptclaim.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != erpbankreceiptclaim.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReceiptID(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldReceiptID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReceiptID(); ok {
		_spec.AddField(erpbankreceiptclaim.FieldReceiptID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SettlementID(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldSettlementID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSettlementID(); ok {
		_spec.AddField(erpbankreceiptclaim.FieldSettlementID, field.TypeInt, value)
	}
	if _u.mutation.SettlementIDCleared() {
		_spec.ClearField(erpbankreceiptclaim.FieldSettlementID, field.TypeInt)
	}
	if value, ok := _u.mutation.ClaimType(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldClaimType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClaimAmount(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldClaimAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedClaimAmount(); ok {
		_spec.AddField(erpbankreceiptclaim.FieldClaimAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Confirmed(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldConfirmed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConfirmedAt(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmedAtCleared() {
		_spec.ClearField(erpbankreceiptclaim.FieldConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClaimedByAdminID(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldClaimedByAdminID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClaimedByAdminID(); ok {
		_spec.AddField(erpbankreceiptclaim.FieldClaimedByAdminID, field.TypeInt, value)
	}
	if _u.mutation.ClaimedByAdminIDCleared() {
		_spec.ClearField(erpbankreceiptclaim.FieldClaimedByAdminID, field.TypeInt)
	}
	if value, ok := _u.mutation.ConfirmedByAdminID(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldConfirmedByAdminID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConfirmedByAdminID(); ok {
		_spec.AddField(erpbankreceiptclaim.FieldConfirmedByAdminID, field.TypeInt, value)
	}
	if _u.mutation.ConfirmedByAdminIDCleared() {
		_spec.ClearField(erpbankreceiptclaim.FieldConfirmedByAdminID, field.TypeInt)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(erpbankreceiptclaim.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(erpbankreceiptclaim.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ERPBankReceiptClaim{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{erpbankreceiptclaim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
