// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"server/internal/data/model/ent/erpmodulerecord"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ERPModuleRecord is the model entity for the ERPModuleRecord schema.
type ERPModuleRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ModuleKey holds the value of the "module_key" field.
	ModuleKey string `json:"module_key,omitempty"`
	// Code holds the value of the "code" field.
	Code *string `json:"code,omitempty"`
	// Box holds the value of the "box" field.
	Box *string `json:"box,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload string `json:"payload,omitempty"`
	// CreatedByAdminID holds the value of the "created_by_admin_id" field.
	CreatedByAdminID *int `json:"created_by_admin_id,omitempty"`
	// UpdatedByAdminID holds the value of the "updated_by_admin_id" field.
	UpdatedByAdminID *int `json:"updated_by_admin_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ERPModuleRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case erpmodulerecord.FieldID, erpmodulerecord.FieldCreatedByAdminID, erpmodulerecord.FieldUpdatedByAdminID:
			values[i] = new(sql.NullInt64)
		case erpmodulerecord.FieldModuleKey, erpmodulerecord.FieldCode, erpmodulerecord.FieldBox, erpmodulerecord.FieldPayload:
			values[i] = new(sql.NullString)
		case erpmodulerecord.FieldCreatedAt, erpmodulerecord.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ERPModuleRecord fields.
func (_m *ERPModuleRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case erpmodulerecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case erpmodulerecord.FieldModuleKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field module_key", values[i])
			} else if value.Valid {
				_m.ModuleKey = value.String
			}
		case erpmodulerecord.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = new(string)
				*_m.Code = value.String
			}
		case erpmodulerecord.FieldBox:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field box", values[i])
			} else if value.Valid {
				_m.Box = new(string)
				*_m.Box = value.String
			}
		case erpmodulerecord.FieldPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value.Valid {
				_m.Payload = value.String
			}
		case erpmodulerecord.FieldCreatedByAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_admin_id", values[i])
			} else if value.Valid {
				_m.CreatedByAdminID = new(int)
				*_m.CreatedByAdminID = int(value.Int64)
			}
		case erpmodulerecord.FieldUpdatedByAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by_admin_id", values[i])
			} else if value.Valid {
				_m.UpdatedByAdminID = new(int)
				*_m.UpdatedByAdminID = int(value.Int64)
			}
		case erpmodulerecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case erpmodulerecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ERPModuleRecord.
// This includes values selected through modifiers, order, etc.
func (_m *ERPModuleRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ERPModuleRecord.
// Note that you need to call ERPModuleRecord.Unwrap() before calling this method if this ERPModuleRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ERPModuleRecord) Update() *ERPModuleRecordUpdateOne {
	return NewERPModuleRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ERPModuleRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ERPModuleRecord) Unwrap() *ERPModuleRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ERPModuleRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ERPModuleRecord) String() string {
	var builder strings.Builder
	builder.WriteString("ERPModuleRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("module_key=")
	builder.WriteString(_m.ModuleKey)
	builder.WriteString(", ")
	if v := _m.Code; v != nil {
		builder.WriteString("code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Box; v != nil {
		builder.WriteString("box=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(_m.Payload)
	builder.WriteString(", ")
	if v := _m.CreatedByAdminID; v != nil {
		builder.WriteString("created_by_admin_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedByAdminID; v != nil {
		builder.WriteString("updated_by_admin_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ERPModuleRecords is a parsable slice of ERPModuleRecord.
type ERPModuleRecords []*ERPModuleRecord
