// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"server/internal/data/model/ent/erpoutboundorderitem"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ERPOutboundOrderItem is the model entity for the ERPOutboundOrderItem schema.
type ERPOutboundOrderItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// OutboundOrderID holds the value of the "outbound_order_id" field.
	OutboundOrderID int `json:"outbound_order_id,omitempty"`
	// LineNo holds the value of the "line_no" field.
	LineNo int `json:"line_no,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID *int `json:"product_id,omitempty"`
	// ProductCode holds the value of the "product_code" field.
	ProductCode *string `json:"product_code,omitempty"`
	// LotNo holds the value of the "lot_no" field.
	LotNo *string `json:"lot_no,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity float64 `json:"quantity,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ERPOutboundOrderItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case erpoutboundorderitem.FieldQuantity:
			values[i] = new(sql.NullFloat64)
		case erpoutboundorderitem.FieldID, erpoutboundorderitem.FieldOutboundOrderID, erpoutboundorderitem.FieldLineNo, erpoutboundorderitem.FieldProductID:
			values[i] = new(sql.NullInt64)
		case erpoutboundorderitem.FieldProductCode, erpoutboundorderitem.FieldLotNo:
			values[i] = new(sql.NullString)
		case erpoutboundorderitem.FieldCreatedAt, erpoutboundorderitem.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ERPOutboundOrderItem fields.
func (_m *ERPOutboundOrderItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case erpoutboundorderitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case erpoutboundorderitem.FieldOutboundOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field outbound_order_id", values[i])
			} else if value.Valid {
				_m.OutboundOrderID = int(value.Int64)
			}
		case erpoutboundorderitem.FieldLineNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field line_no", values[i])
			} else if value.Valid {
				_m.LineNo = int(value.Int64)
			}
		case erpoutboundorderitem.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = new(int)
				*_m.ProductID = int(value.Int64)
			}
		case erpoutboundorderitem.FieldProductCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_code", values[i])
			} else if value.Valid {
				_m.ProductCode = new(string)
				*_m.ProductCode = value.String
			}
		case erpoutboundorderitem.FieldLotNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lot_no", values[i])
			} else if value.Valid {
				_m.LotNo = new(string)
				*_m.LotNo = value.String
			}
		case erpoutboundorderitem.FieldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = value.Float64
			}
		case erpoutboundorderitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case erpoutboundorderitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ERPOutboundOrderItem.
// This includes values selected through modifiers, order, etc.
func (_m *ERPOutboundOrderItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ERPOutboundOrderItem.
// Note that you need to call ERPOutboundOrderItem.Unwrap() before calling this method if this ERPOutboundOrderItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ERPOutboundOrderItem) Update() *ERPOutboundOrderItemUpdateOne {
	return NewERPOutboundOrderItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ERPOutboundOrderItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ERPOutboundOrderItem) Unwrap() *ERPOutboundOrderItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ERPOutboundOrderItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ERPOutboundOrderItem) String() string {
	var builder strings.Builder
	builder.WriteString("ERPOutboundOrderItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("outbound_order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutboundOrderID))
	builder.WriteString(", ")
	builder.WriteString("line_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.LineNo))
	builder.WriteString(", ")
	if v := _m.ProductID; v != nil {
		builder.WriteString("product_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProductCode; v != nil {
		builder.WriteString("product_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LotNo; v != nil {
		builder.WriteString("lot_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ERPOutboundOrderItems is a parsable slice of ERPOutboundOrderItem.
type ERPOutboundOrderItems []*ERPOutboundOrderItem
