// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/erppurchasecontractitem"
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ERPPurchaseContractItemUpdate is the builder for updating ERPPurchaseContractItem entities.
type ERPPurchaseContractItemUpdate struct {
	config
	hooks    []Hook
	mutation *ERPPurchaseContractItemMutation
}

// Where appends a list predicates to the ERPPurchaseContractItemUpdate builder.
func (_u *ERPPurchaseContractItemUpdate) Where(ps ...predicate.ERPPurchaseContractItem) *ERPPurchaseContractItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPurchaseContractID sets the "purchase_contract_id" field.
func (_u *ERPPurchaseContractItemUpdate) SetPurchaseContractID(v int) *ERPPurchaseContractItemUpdate {
	_u.mutation.ResetPurchaseContractID()
	_u.mutation.SetPurchaseContractID(v)
	return _u
}

// SetNillablePurchaseContractID sets the "purchase_contract_id" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdate) SetNillablePurchaseContractID(v *int) *ERPPurchaseContractItemUpdate {
	if v != nil {
		_u.SetPurchaseContractID(*v)
	}
	return _u
}

// AddPurchaseContractID adds value to the "purchase_contract_id" field.
func (_u *ERPPurchaseContractItemUpdate) AddPurchaseContractID(v int) *ERPPurchaseContractItemUpdate {
	_u.mutation.AddPurchaseContractID(v)
	return _u
}

// SetLineNo sets the "line_no" field.
func (_u *ERPPurchaseContractItemUpdate) SetLineNo(v int) *ERPPurchaseContractItemUpdate {
	_u.mutation.ResetLineNo()
	_u.mutation.SetLineNo(v)
	return _u
}

// SetNillableLineNo sets the "line_no" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdate) SetNillableLineNo(v *int) *ERPPurchaseContractItemUpdate {
	if v != nil {
		_u.SetLineNo(*v)
	}
	return _u
}

// AddLineNo adds value to the "line_no" field.
func (_u *ERPPurchaseContractItemUpdate) AddLineNo(v int) *ERPPurchaseContractItemUpdate {
	_u.mutation.AddLineNo(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ERPPurchaseContractItemUpdate) SetProductID(v int) *ERPPurchaseContractItemUpdate {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdate) SetNillableProductID(v *int) *ERPPurchaseContractItemUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *ERPPurchaseContractItemUpdate) AddProductID(v int) *ERPPurchaseContractItemUpdate {
	_u.mutation.AddProductID(v)
	return _u
}

// ClearProductID clears the value of the "product_id" field.
func (_u *ERPPurchaseContractItemUpdate) ClearProductID() *ERPPurchaseContractItemUpdate {
	_u.mutation.ClearProductID()
	return _u
}

// SetProductCode sets the "product_code" field.
func (_u *ERPPurchaseContractItemUpdate) SetProductCode(v string) *ERPPurchaseContractItemUpdate {
	_u.mutation.SetProductCode(v)
	return _u
}

// SetNillableProductCode sets the "product_code" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdate) SetNillableProductCode(v *string) *ERPPurchaseContractItemUpdate {
	if v != nil {
		_u.SetProductCode(*v)
	}
	return _u
}

// ClearProductCode clears the value of the "product_code" field.
func (_u *ERPPurchaseContractItemUpdate) ClearProductCode() *ERPPurchaseContractItemUpdate {
	_u.mutation.ClearProductCode()
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *ERPPurchaseContractItemUpdate) SetProductName(v string) *ERPPurchaseContractItemUpdate {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdate) SetNillableProductName(v *string) *ERPPurchaseContractItemUpdate {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// ClearProductName clears the value of the "product_name" field.
func (_u *ERPPurchaseContractItemUpdate) ClearProductName() *ERPPurchaseContractItemUpdate {
	_u.mutation.ClearProductName()
	return _u
}

// SetSpecCode sets the "spec_code" field.
func (_u *ERPPurchaseContractItemUpdate) SetSpecCode(v string) *ERPPurchaseContractItemUpdate {
	_u.mutation.SetSpecCode(v)
	return _u
}

// SetNillableSpecCode sets the "spec_code" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdate) SetNillableSpecCode(v *string) *ERPPurchaseContractItemUpdate {
	if v != nil {
		_u.SetSpecCode(*v)
	}
	return _u
}

// ClearSpecCode clears the value of the "spec_code" field.
func (_u *ERPPurchaseContractItemUpdate) ClearSpecCode() *ERPPurchaseContractItemUpdate {
	_u.mutation.ClearSpecCode()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *ERPPurchaseContractItemUpdate) SetQuantity(v float64) *ERPPurchaseContractItemUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdate) SetNillableQuantity(v *float64) *ERPPurchaseContractItemUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *ERPPurchaseContractItemUpdate) AddQuantity(v float64) *ERPPurchaseContractItemUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *ERPPurchaseContractItemUpdate) SetUnitPrice(v float64) *ERPPurchaseContractItemUpdate {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdate) SetNillableUnitPrice(v *float64) *ERPPurchaseContractItemUpdate {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *ERPPurchaseContractItemUpdate) AddUnitPrice(v float64) *ERPPurchaseContractItemUpdate {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetTotalPrice sets the "total_price" field.
func (_u *ERPPurchaseContractItemUpdate) SetTotalPrice(v float64) *ERPPurchaseContractItemUpdate {
	_u.mutation.ResetTotalPrice()
	_u.mutation.SetTotalPrice(v)
	return _u
}

// SetNillableTotalPrice sets the "total_price" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdate) SetNillableTotalPrice(v *float64) *ERPPurchaseContractItemUpdate {
	if v != nil {
		_u.SetTotalPrice(*v)
	}
	return _u
}

// AddTotalPrice adds value to the "total_price" field.
func (_u *ERPPurchaseContractItemUpdate) AddTotalPrice(v float64) *ERPPurchaseContractItemUpdate {
	_u.mutation.AddTotalPrice(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ERPPurchaseContractItemUpdate) SetUpdatedAt(v time.Time) *ERPPurchaseContractItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ERPPurchaseContractItemMutation object of the builder.
func (_u *ERPPurchaseContractItemUpdate) Mutation() *ERPPurchaseContractItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ERPPurchaseContractItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ERPPurchaseContractItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ERPPurchaseContractItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ERPPurchaseContractItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ERPPurchaseContractItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := erppurchasecontractitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ERPPurchaseContractItemUpdate) check() error {
	if v, ok := _u.mutation.PurchaseContractID(); ok {
		if err := erppurchasecontractitem.PurchaseContractIDValidator(v); err != nil {
			return &ValidationError{Name: "purchase_contract_id", err: fmt.Errorf(`ent: validator failed for field "ERPPurchaseContractItem.purchase_contract_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LineNo(); ok {
		if err := erppurchasecontractitem.LineNoValidator(v); err != nil {
			return &ValidationError{Name: "line_no", err: fmt.Errorf(`ent: validator failed for field "ERPPurchaseContractItem.line_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductCode(); ok {
		if err := erppurchasecontractitem.ProductCodeValidator(v); err != nil {
			return &ValidationError{Name: "product_code", err: fmt.Errorf(`ent: validator failed for field "ERPPurchaseContractItem.product_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := erppurchasecontractitem.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "ERPPurchaseContractItem.product_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SpecCode(); ok {
		if err := erppurchasecontractitem.SpecCodeValidator(v); err != nil {
			return &ValidationError{Name: "spec_code", err: fmt.Errorf(`ent: validator failed for field "ERPPurchaseContractItem.spec_code": %w`, err)}
		}
	}
	return nil
}

func (_u *ERPPurchaseContractItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(erppurchasecontractitem.Table, erppurchasecontractitem.Columns, sqlgraph.NewFieldSpec(erppurchasecontractitem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PurchaseContractID(); ok {
		_spec.SetField(erppurchasecontractitem.FieldPurchaseContractID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPurchaseContractID(); ok {
		_spec.AddField(erppurchasecontractitem.FieldPurchaseContractID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LineNo(); ok {
		_spec.SetField(erppurchasecontractitem.FieldLineNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLineNo(); ok {
		_spec.AddField(erppurchasecontractitem.FieldLineNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(erppurchasecontractitem.FieldProductID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(erppurchasecontractitem.FieldProductID, field.TypeInt, value)
	}
	if _u.mutation.ProductIDCleared() {
		_spec.ClearField(erppurchasecontractitem.FieldProductID, field.TypeInt)
	}
	if value, ok := _u.mutation.ProductCode(); ok {
		_spec.SetField(erppurchasecontractitem.FieldProductCode, field.TypeString, value)
	}
	if _u.mutation.ProductCodeCleared() {
		_spec.ClearField(erppurchasecontractitem.FieldProductCode, field.TypeString)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(erppurchasecontractitem.FieldProductName, field.TypeString, value)
	}
	if _u.mutation.ProductNameCleared() {
		_spec.ClearField(erppurchasecontractitem.FieldProductName, field.TypeString)
	}
	if value, ok := _u.mutation.SpecCode(); ok {
		_spec.SetField(erppurchasecontractitem.FieldSpecCode, field.TypeString, value)
	}
	if _u.mutation.SpecCodeCleared() {
		_spec.ClearField(erppurchasecontractitem.FieldSpecCode, field.TypeString)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(erppurchasecontractitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(erppurchasecontractitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(erppurchasecontractitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(erppurchasecontractitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalPrice(); ok {
		_spec.SetField(erppurchasecontractitem.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalPrice(); ok {
		_spec.AddField(erppurchasecontractitem.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(erppurchasecontractitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{erppurchasecontractitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ERPPurchaseContractItemUpdateOne is the builder for updating a single ERPPurchaseContractItem entity.
type ERPPurchaseContractItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ERPPurchaseContractItemMutation
}

// SetPurchaseContractID sets the "purchase_contract_id" field.
func (_u *ERPPurchaseContractItemUpdateOne) SetPurchaseContractID(v int) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.ResetPurchaseContractID()
	_u.mutation.SetPurchaseContractID(v)
	return _u
}

// SetNillablePurchaseContractID sets the "purchase_contract_id" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdateOne) SetNillablePurchaseContractID(v *int) *ERPPurchaseContractItemUpdateOne {
	if v != nil {
		_u.SetPurchaseContractID(*v)
	}
	return _u
}

// AddPurchaseContractID adds value to the "purchase_contract_id" field.
func (_u *ERPPurchaseContractItemUpdateOne) AddPurchaseContractID(v int) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.AddPurchaseContractID(v)
	return _u
}

// SetLineNo sets the "line_no" field.
func (_u *ERPPurchaseContractItemUpdateOne) SetLineNo(v int) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.ResetLineNo()
	_u.mutation.SetLineNo(v)
	return _u
}

// SetNillableLineNo sets the "line_no" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdateOne) SetNillableLineNo(v *int) *ERPPurchaseContractItemUpdateOne {
	if v != nil {
		_u.SetLineNo(*v)
	}
	return _u
}

// AddLineNo adds value to the "line_no" field.
func (_u *ERPPurchaseContractItemUpdateOne) AddLineNo(v int) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.AddLineNo(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ERPPurchaseContractItemUpdateOne) SetProductID(v int) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdateOne) SetNillableProductID(v *int) *ERPPurchaseContractItemUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *ERPPurchaseContractItemUpdateOne) AddProductID(v int) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.AddProductID(v)
	return _u
}

// ClearProductID clears the value of the "product_id" field.
func (_u *ERPPurchaseContractItemUpdateOne) ClearProductID() *ERPPurchaseContractItemUpdateOne {
	_u.mutation.ClearProductID()
	return _u
}

// SetProductCode sets the "product_code" field.
func (_u *ERPPurchaseContractItemUpdateOne) SetProductCode(v string) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.SetProductCode(v)
	return _u
}

// SetNillableProductCode sets the "product_code" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdateOne) SetNillableProductCode(v *string) *ERPPurchaseContractItemUpdateOne {
	if v != nil {
		_u.SetProductCode(*v)
	}
	return _u
}

// ClearProductCode clears the value of the "product_code" field.
func (_u *ERPPurchaseContractItemUpdateOne) ClearProductCode() *ERPPurchaseContractItemUpdateOne {
	_u.mutation.ClearProductCode()
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *ERPPurchaseContractItemUpdateOne) SetProductName(v string) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdateOne) SetNillableProductName(v *string) *ERPPurchaseContractItemUpdateOne {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// ClearProductName clears the value of the "product_name" field.
func (_u *ERPPurchaseContractItemUpdateOne) ClearProductName() *ERPPurchaseContractItemUpdateOne {
	_u.mutation.ClearProductName()
	return _u
}

// SetSpecCode sets the "spec_code" field.
func (_u *ERPPurchaseContractItemUpdateOne) SetSpecCode(v string) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.SetSpecCode(v)
	return _u
}

// SetNillableSpecCode sets the "spec_code" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdateOne) SetNillableSpecCode(v *string) *ERPPurchaseContractItemUpdateOne {
	if v != nil {
		_u.SetSpecCode(*v)
	}
	return _u
}

// ClearSpecCode clears the value of the "spec_code" field.
func (_u *ERPPurchaseContractItemUpdateOne) ClearSpecCode() *ERPPurchaseContractItemUpdateOne {
	_u.mutation.ClearSpecCode()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *ERPPurchaseContractItemUpdateOne) SetQuantity(v float64) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdateOne) SetNillableQuantity(v *float64) *ERPPurchaseContractItemUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *ERPPurchaseContractItemUpdateOne) AddQuantity(v float64) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *ERPPurchaseContractItemUpdateOne) SetUnitPrice(v float64) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdateOne) SetNillableUnitPrice(v *float64) *ERPPurchaseContractItemUpdateOne {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *ERPPurchaseContractItemUpdateOne) AddUnitPrice(v float64) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetTotalPrice sets the "total_price" field.
func (_u *ERPPurchaseContractItemUpdateOne) SetTotalPrice(v float64) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.ResetTotalPrice()
	_u.mutation.SetTotalPrice(v)
	return _u
}

// SetNillableTotalPrice sets the "total_price" field if the given value is not nil.
func (_u *ERPPurchaseContractItemUpdateOne) SetNillableTotalPrice(v *float64) *ERPPurchaseContractItemUpdateOne {
	if v != nil {
		_u.SetTotalPrice(*v)
	}
	return _u
}

// AddTotalPrice adds value to the "total_price" field.
func (_u *ERPPurchaseContractItemUpdateOne) AddTotalPrice(v float64) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.AddTotalPrice(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ERPPurchaseContractItemUpdateOne) SetUpdatedAt(v time.Time) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ERPPurchaseContractItemMutation object of the builder.
func (_u *ERPPurchaseContractItemUpdateOne) Mutation() *ERPPurchaseContractItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the ERPPurchaseContractItemUpdate builder.
func (_u *ERPPurchaseContractItemUpdateOne) Where(ps ...predicate.ERPPurchaseContractItem) *ERPPurchaseContractItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ERPPurchaseContractItemUpdateOne) Select(field string, fields ...string) *ERPPurchaseContractItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ERPPurchaseContractItem entity.
func (_u *ERPPurchaseContractItemUpdateOne) Save(ctx context.Context) (*ERPPurchaseContractItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ERPPurchaseContractItemUpdateOne) SaveX(ctx context.Context) *ERPPurchaseContractItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ERPPurchaseContractItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ERPPurchaseContractItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ERPPurchaseContractItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := erppurchasecontractitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ERPPurchaseContractItemUpdateOne) check() error {
	if v, ok := _u.mutation.PurchaseContractID(); ok {
		if err := erppurchasecontractitem.PurchaseContractIDValidator(v); err != nil {
			return &ValidationError{Name: "purchase_contract_id", err: fmt.Errorf(`ent: validator failed for field "ERPPurchaseContractItem.purchase_contract_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LineNo(); ok {
		if err := erppurchasecontractitem.LineNoValidator(v); err != nil {
			return &ValidationError{Name: "line_no", err: fmt.Errorf(`ent: validator failed for field "ERPPurchaseContractItem.line_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductCode(); ok {
		if err := erppurchasecontractitem.ProductCodeValidator(v); err != nil {
			return &ValidationError{Name: "product_code", err: fmt.Errorf(`ent: validator failed for field "ERPPurchaseContractItem.product_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := erppurchasecontractitem.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "ERPPurchaseContractItem.product_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SpecCode(); ok {
		if err := erppurchasecontractitem.SpecCodeValidator(v); err != nil {
			return &ValidationError{Name: "spec_code", err: fmt.Errorf(`ent: validator failed for field "ERPPurchaseContractItem.spec_code": %w`, err)}
		}
	}
	return nil
}

func (_u *ERPPurchaseContractItemUpdateOne) sqlSave(ctx context.Context) (_node *ERPPurchaseContractItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(erppurchasecontractitem.Table, erppurchasecontractitem.Columns, sqlgraph.NewFieldSpec(erppurchasecontractitem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ERPPurchaseContractItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, erppurchasecontractitem.FieldID)
		for _, f := range fields {
			if !erppurchasecontractitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != erppurchasecontractitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PurchaseContractID(); ok {
		_spec.SetField(erppurchasecontractitem.FieldPurchaseContractID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPurchaseContractID(); ok {
		_spec.AddField(erppurchasecontractitem.FieldPurchaseContractID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LineNo(); ok {
		_spec.SetField(erppurchasecontractitem.FieldLineNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLineNo(); ok {
		_spec.AddField(erppurchasecontractitem.FieldLineNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(erppurchasecontractitem.FieldProductID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(erppurchasecontractitem.FieldProductID, field.TypeInt, value)
	}
	if _u.mutation.ProductIDCleared() {
		_spec.ClearField(erppurchasecontractitem.FieldProductID, field.TypeInt)
	}
	if value, ok := _u.mutation.ProductCode(); ok {
		_spec.SetField(erppurchasecontractitem.FieldProductCode, field.TypeString, value)
	}
	if _u.mutation.ProductCodeCleared() {
		_spec.ClearField(erppurchasecontractitem.FieldProductCode, field.TypeString)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(erppurchasecontractitem.FieldProductName, field.TypeString, value)
	}
	if _u.mutation.ProductNameCleared() {
		_spec.ClearField(erppurchasecontractitem.FieldProductName, field.TypeString)
	}
	if value, ok := _u.mutation.SpecCode(); ok {
		_spec.SetField(erppurchasecontractitem.FieldSpecCode, field.TypeString, value)
	}
	if _u.mutation.SpecCodeCleared() {
		_spec.ClearField(erppurchasecontractitem.FieldSpecCode, field.TypeString)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(erppurchasecontractitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(erppurchasecontractitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(erppurchasecontractitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(erppurchasecontractitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalPrice(); ok {
		_spec.SetField(erppurchasecontractitem.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalPrice(); ok {
		_spec.AddField(erppurchasecontractitem.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(erppurchasecontractitem.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ERPPurchaseContractItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{erppurchasecontractitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
