// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/erpquotationitem"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ERPQuotationItemCreate is the builder for creating a ERPQuotationItem entity.
type ERPQuotationItemCreate struct {
	config
	mutation *ERPQuotationItemMutation
	hooks    []Hook
}

// SetQuotationID sets the "quotation_id" field.
func (_c *ERPQuotationItemCreate) SetQuotationID(v int) *ERPQuotationItemCreate {
	_c.mutation.SetQuotationID(v)
	return _c
}

// SetLineNo sets the "line_no" field.
func (_c *ERPQuotationItemCreate) SetLineNo(v int) *ERPQuotationItemCreate {
	_c.mutation.SetLineNo(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *ERPQuotationItemCreate) SetProductID(v int) *ERPQuotationItemCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_c *ERPQuotationItemCreate) SetNillableProductID(v *int) *ERPQuotationItemCreate {
	if v != nil {
		_c.SetProductID(*v)
	}
	return _c
}

// SetProductCode sets the "product_code" field.
func (_c *ERPQuotationItemCreate) SetProductCode(v string) *ERPQuotationItemCreate {
	_c.mutation.SetProductCode(v)
	return _c
}

// SetNillableProductCode sets the "product_code" field if the given value is not nil.
func (_c *ERPQuotationItemCreate) SetNillableProductCode(v *string) *ERPQuotationItemCreate {
	if v != nil {
		_c.SetProductCode(*v)
	}
	return _c
}

// SetProductName sets the "product_name" field.
func (_c *ERPQuotationItemCreate) SetProductName(v string) *ERPQuotationItemCreate {
	_c.mutation.SetProductName(v)
	return _c
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_c *ERPQuotationItemCreate) SetNillableProductName(v *string) *ERPQuotationItemCreate {
	if v != nil {
		_c.SetProductName(*v)
	}
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *ERPQuotationItemCreate) SetQuantity(v float64) *ERPQuotationItemCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_c *ERPQuotationItemCreate) SetNillableQuantity(v *float64) *ERPQuotationItemCreate {
	if v != nil {
		_c.SetQuantity(*v)
	}
	return _c
}

// SetUnitPrice sets the "unit_price" field.
func (_c *ERPQuotationItemCreate) SetUnitPrice(v float64) *ERPQuotationItemCreate {
	_c.mutation.SetUnitPrice(v)
	return _c
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_c *ERPQuotationItemCreate) SetNillableUnitPrice(v *float64) *ERPQuotationItemCreate {
	if v != nil {
		_c.SetUnitPrice(*v)
	}
	return _c
}

// SetTotalPrice sets the "total_price" field.
func (_c *ERPQuotationItemCreate) SetTotalPrice(v float64) *ERPQuotationItemCreate {
	_c.mutation.SetTotalPrice(v)
	return _c
}

// SetNillableTotalPrice sets the "total_price" field if the given value is not nil.
func (_c *ERPQuotationItemCreate) SetNillableTotalPrice(v *float64) *ERPQuotationItemCreate {
	if v != nil {
		_c.SetTotalPrice(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *ERPQuotationItemCreate) SetRemark(v string) *ERPQuotationItemCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *ERPQuotationItemCreate) SetNillableRemark(v *string) *ERPQuotationItemCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ERPQuotationItemCreate) SetCreatedAt(v time.Time) *ERPQuotationItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ERPQuotationItemCreate) SetNillableCreatedAt(v *time.Time) *ERPQuotationItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ERPQuotationItemCreate) SetUpdatedAt(v time.Time) *ERPQuotationItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ERPQuotationItemCreate) SetNillableUpdatedAt(v *time.Time) *ERPQuotationItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ERPQuotationItemMutation object of the builder.
func (_c *ERPQuotationItemCreate) Mutation() *ERPQuotationItemMutation {
	return _c.mutation
}

// Save creates the ERPQuotationItem in the database.
func (_c *ERPQuotationItemCreate) Save(ctx context.Context) (*ERPQuotationItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ERPQuotationItemCreate) SaveX(ctx context.Context) *ERPQuotationItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ERPQuotationItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ERPQuotationItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ERPQuotationItemCreate) defaults() {
	if _, ok := _c.mutation.Quantity(); !ok {
		v := erpquotationitem.DefaultQuantity
		_c.mutation.SetQuantity(v)
	}
	if _, ok := _c.mutation.UnitPrice(); !ok {
		v := erpquotationitem.DefaultUnitPrice
		_c.mutation.SetUnitPrice(v)
	}
	if _, ok := _c.mutation.TotalPrice(); !ok {
		v := erpquotationitem.DefaultTotalPrice
		_c.mutation.SetTotalPrice(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := erpquotationitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := erpquotationitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ERPQuotationItemCreate) check() error {
	if _, ok := _c.mutation.QuotationID(); !ok {
		return &ValidationError{Name: "quotation_id", err: errors.New(`ent: missing required field "ERPQuotationItem.quotation_id"`)}
	}
	if v, ok := _c.mutation.QuotationID(); ok {
		if err := erpquotationitem.QuotationIDValidator(v); err != nil {
			return &ValidationError{Name: "quotation_id", err: fmt.Errorf(`ent: validator failed for field "ERPQuotationItem.quotation_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LineNo(); !ok {
		return &ValidationError{Name: "line_no", err: errors.New(`ent: missing required field "ERPQuotationItem.line_no"`)}
	}
	if v, ok := _c.mutation.LineNo(); ok {
		if err := erpquotationitem.LineNoValidator(v); err != nil {
			return &ValidationError{Name: "line_no", err: fmt.Errorf(`ent: validator failed for field "ERPQuotationItem.line_no": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProductCode(); ok {
		if err := erpquotationitem.ProductCodeValidator(v); err != nil {
			return &ValidationError{Name: "product_code", err: fmt.Errorf(`ent: validator failed for field "ERPQuotationItem.product_code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProductName(); ok {
		if err := erpquotationitem.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "ERPQuotationItem.product_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "ERPQuotationItem.quantity"`)}
	}
	if _, ok := _c.mutation.UnitPrice(); !ok {
		return &ValidationError{Name: "unit_price", err: errors.New(`ent: missing required field "ERPQuotationItem.unit_price"`)}
	}
	if _, ok := _c.mutation.TotalPrice(); !ok {
		return &ValidationError{Name: "total_price", err: errors.New(`ent: missing required field "ERPQuotationItem.total_price"`)}
	}
	if v, ok := _c.mutation.Remark(); ok {
		if err := erpquotationitem.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "ERPQuotationItem.remark": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ERPQuotationItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ERPQuotationItem.updated_at"`)}
	}
	return nil
}

func (_c *ERPQuotationItemCreate) sqlSave(ctx context.Context) (*ERPQuotationItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ERPQuotationItemCreate) createSpec() (*ERPQuotationItem, *sqlgraph.CreateSpec) {
	var (
		_node = &ERPQuotationItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(erpquotationitem.Table, sqlgraph.NewFieldSpec(erpquotationitem.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.QuotationID(); ok {
		_spec.SetField(erpquotationitem.FieldQuotationID, field.TypeInt, value)
		_node.QuotationID = value
	}
	if value, ok := _c.mutation.LineNo(); ok {
		_spec.SetField(erpquotationitem.FieldLineNo, field.TypeInt, value)
		_node.LineNo = value
	}
	if value, ok := _c.mutation.ProductID(); ok {
		_spec.SetField(erpquotationitem.FieldProductID, field.TypeInt, value)
		_node.ProductID = &value
	}
	if value, ok := _c.mutation.ProductCode(); ok {
		_spec.SetField(erpquotationitem.FieldProductCode, field.TypeString, value)
		_node.ProductCode = &value
	}
	if value, ok := _c.mutation.ProductName(); ok {
		_spec.SetField(erpquotationitem.FieldProductName, field.TypeString, value)
		_node.ProductName = &value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(erpquotationitem.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.UnitPrice(); ok {
		_spec.SetField(erpquotationitem.FieldUnitPrice, field.TypeFloat64, value)
		_node.UnitPrice = value
	}
	if value, ok := _c.mutation.TotalPrice(); ok {
		_spec.SetField(erpquotationitem.FieldTotalPrice, field.TypeFloat64, value)
		_node.TotalPrice = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(erpquotationitem.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(erpquotationitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(erpquotationitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ERPQuotationItemCreateBulk is the builder for creating many ERPQuotationItem entities in bulk.
type ERPQuotationItemCreateBulk struct {
	config
	err      error
	builders []*ERPQuotationItemCreate
}

// Save creates the ERPQuotationItem entities in the database.
func (_c *ERPQuotationItemCreateBulk) Save(ctx context.Context) ([]*ERPQuotationItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ERPQuotationItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ERPQuotationItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ERPQuotationItemCreateBulk) SaveX(ctx context.Context) []*ERPQuotationItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ERPQuotationItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ERPQuotationItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
