// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/erpsequence"
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ERPSequenceUpdate is the builder for updating ERPSequence entities.
type ERPSequenceUpdate struct {
	config
	hooks    []Hook
	mutation *ERPSequenceMutation
}

// Where appends a list predicates to the ERPSequenceUpdate builder.
func (_u *ERPSequenceUpdate) Where(ps ...predicate.ERPSequence) *ERPSequenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBizType sets the "biz_type" field.
func (_u *ERPSequenceUpdate) SetBizType(v string) *ERPSequenceUpdate {
	_u.mutation.SetBizType(v)
	return _u
}

// SetNillableBizType sets the "biz_type" field if the given value is not nil.
func (_u *ERPSequenceUpdate) SetNillableBizType(v *string) *ERPSequenceUpdate {
	if v != nil {
		_u.SetBizType(*v)
	}
	return _u
}

// SetCurrentValue sets the "current_value" field.
func (_u *ERPSequenceUpdate) SetCurrentValue(v int64) *ERPSequenceUpdate {
	_u.mutation.ResetCurrentValue()
	_u.mutation.SetCurrentValue(v)
	return _u
}

// SetNillableCurrentValue sets the "current_value" field if the given value is not nil.
func (_u *ERPSequenceUpdate) SetNillableCurrentValue(v *int64) *ERPSequenceUpdate {
	if v != nil {
		_u.SetCurrentValue(*v)
	}
	return _u
}

// AddCurrentValue adds value to the "current_value" field.
func (_u *ERPSequenceUpdate) AddCurrentValue(v int64) *ERPSequenceUpdate {
	_u.mutation.AddCurrentValue(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ERPSequenceUpdate) SetUpdatedAt(v time.Time) *ERPSequenceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ERPSequenceMutation object of the builder.
func (_u *ERPSequenceUpdate) Mutation() *ERPSequenceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ERPSequenceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ERPSequenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ERPSequenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ERPSequenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ERPSequenceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := erpsequence.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ERPSequenceUpdate) check() error {
	if v, ok := _u.mutation.BizType(); ok {
		if err := erpsequence.BizTypeValidator(v); err != nil {
			return &ValidationError{Name: "biz_type", err: fmt.Errorf(`ent: validator failed for field "ERPSequence.biz_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ERPSequenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(erpsequence.Table, erpsequence.Columns, sqlgraph.NewFieldSpec(erpsequence.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BizType(); ok {
		_spec.SetField(erpsequence.FieldBizType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentValue(); ok {
		_spec.SetField(erpsequence.FieldCurrentValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCurrentValue(); ok {
		_spec.AddField(erpsequence.FieldCurrentValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(erpsequence.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{erpsequence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ERPSequenceUpdateOne is the builder for updating a single ERPSequence entity.
type ERPSequenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ERPSequenceMutation
}

// SetBizType sets the "biz_type" field.
func (_u *ERPSequenceUpdateOne) SetBizType(v string) *ERPSequenceUpdateOne {
	_u.mutation.SetBizType(v)
	return _u
}

// SetNillableBizType sets the "biz_type" field if the given value is not nil.
func (_u *ERPSequenceUpdateOne) SetNillableBizType(v *string) *ERPSequenceUpdateOne {
	if v != nil {
		_u.SetBizType(*v)
	}
	return _u
}

// SetCurrentValue sets the "current_value" field.
func (_u *ERPSequenceUpdateOne) SetCurrentValue(v int64) *ERPSequenceUpdateOne {
	_u.mutation.ResetCurrentValue()
	_u.mutation.SetCurrentValue(v)
	return _u
}

// SetNillableCurrentValue sets the "current_value" field if the given value is not nil.
func (_u *ERPSequenceUpdateOne) SetNillableCurrentValue(v *int64) *ERPSequenceUpdateOne {
	if v != nil {
		_u.SetCurrentValue(*v)
	}
	return _u
}

// AddCurrentValue adds value to the "current_value" field.
func (_u *ERPSequenceUpdateOne) AddCurrentValue(v int64) *ERPSequenceUpdateOne {
	_u.mutation.AddCurrentValue(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ERPSequenceUpdateOne) SetUpdatedAt(v time.Time) *ERPSequenceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ERPSequenceMutation object of the builder.
func (_u *ERPSequenceUpdateOne) Mutation() *ERPSequenceMutation {
	return _u.mutation
}

// Where appends a list predicates to the ERPSequenceUpdate builder.
func (_u *ERPSequenceUpdateOne) Where(ps ...predicate.ERPSequence) *ERPSequenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ERPSequenceUpdateOne) Select(field string, fields ...string) *ERPSequenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ERPSequence entity.
func (_u *ERPSequenceUpdateOne) Save(ctx context.Context) (*ERPSequence, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ERPSequenceUpdateOne) SaveX(ctx context.Context) *ERPSequence {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ERPSequenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ERPSequenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ERPSequenceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := erpsequence.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ERPSequenceUpdateOne) check() error {
	if v, ok := _u.mutation.BizType(); ok {
		if err := erpsequence.BizTypeValidator(v); err != nil {
			return &ValidationError{Name: "biz_type", err: fmt.Errorf(`ent: validator failed for field "ERPSequence.biz_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ERPSequenceUpdateOne) sqlSave(ctx context.Context) (_node *ERPSequence, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(erpsequence.Table, erpsequence.Columns, sqlgraph.NewFieldSpec(erpsequence.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ERPSequence.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, erpsequence.FieldID)
		for _, f := range fields {
			if !erpsequence.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != erpsequence.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BizType(); ok {
		_spec.SetField(erpsequence.FieldBizType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentValue(); ok {
		_spec.SetField(erpsequence.FieldCurrentValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCurrentValue(); ok {
		_spec.AddField(erpsequence.FieldCurrentValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(erpsequence.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ERPSequence{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{erpsequence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
