// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/erpshipmentdetailitem"
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ERPShipmentDetailItemUpdate is the builder for updating ERPShipmentDetailItem entities.
type ERPShipmentDetailItemUpdate struct {
	config
	hooks    []Hook
	mutation *ERPShipmentDetailItemMutation
}

// Where appends a list predicates to the ERPShipmentDetailItemUpdate builder.
func (_u *ERPShipmentDetailItemUpdate) Where(ps ...predicate.ERPShipmentDetailItem) *ERPShipmentDetailItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetShipmentDetailID sets the "shipment_detail_id" field.
func (_u *ERPShipmentDetailItemUpdate) SetShipmentDetailID(v int) *ERPShipmentDetailItemUpdate {
	_u.mutation.ResetShipmentDetailID()
	_u.mutation.SetShipmentDetailID(v)
	return _u
}

// SetNillableShipmentDetailID sets the "shipment_detail_id" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdate) SetNillableShipmentDetailID(v *int) *ERPShipmentDetailItemUpdate {
	if v != nil {
		_u.SetShipmentDetailID(*v)
	}
	return _u
}

// AddShipmentDetailID adds value to the "shipment_detail_id" field.
func (_u *ERPShipmentDetailItemUpdate) AddShipmentDetailID(v int) *ERPShipmentDetailItemUpdate {
	_u.mutation.AddShipmentDetailID(v)
	return _u
}

// SetLineNo sets the "line_no" field.
func (_u *ERPShipmentDetailItemUpdate) SetLineNo(v int) *ERPShipmentDetailItemUpdate {
	_u.mutation.ResetLineNo()
	_u.mutation.SetLineNo(v)
	return _u
}

// SetNillableLineNo sets the "line_no" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdate) SetNillableLineNo(v *int) *ERPShipmentDetailItemUpdate {
	if v != nil {
		_u.SetLineNo(*v)
	}
	return _u
}

// AddLineNo adds value to the "line_no" field.
func (_u *ERPShipmentDetailItemUpdate) AddLineNo(v int) *ERPShipmentDetailItemUpdate {
	_u.mutation.AddLineNo(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ERPShipmentDetailItemUpdate) SetProductID(v int) *ERPShipmentDetailItemUpdate {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdate) SetNillableProductID(v *int) *ERPShipmentDetailItemUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *ERPShipmentDetailItemUpdate) AddProductID(v int) *ERPShipmentDetailItemUpdate {
	_u.mutation.AddProductID(v)
	return _u
}

// ClearProductID clears the value of the "product_id" field.
func (_u *ERPShipmentDetailItemUpdate) ClearProductID() *ERPShipmentDetailItemUpdate {
	_u.mutation.ClearProductID()
	return _u
}

// SetProductCode sets the "product_code" field.
func (_u *ERPShipmentDetailItemUpdate) SetProductCode(v string) *ERPShipmentDetailItemUpdate {
	_u.mutation.SetProductCode(v)
	return _u
}

// SetNillableProductCode sets the "product_code" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdate) SetNillableProductCode(v *string) *ERPShipmentDetailItemUpdate {
	if v != nil {
		_u.SetProductCode(*v)
	}
	return _u
}

// ClearProductCode clears the value of the "product_code" field.
func (_u *ERPShipmentDetailItemUpdate) ClearProductCode() *ERPShipmentDetailItemUpdate {
	_u.mutation.ClearProductCode()
	return _u
}

// SetProductModel sets the "product_model" field.
func (_u *ERPShipmentDetailItemUpdate) SetProductModel(v string) *ERPShipmentDetailItemUpdate {
	_u.mutation.SetProductModel(v)
	return _u
}

// SetNillableProductModel sets the "product_model" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdate) SetNillableProductModel(v *string) *ERPShipmentDetailItemUpdate {
	if v != nil {
		_u.SetProductModel(*v)
	}
	return _u
}

// ClearProductModel clears the value of the "product_model" field.
func (_u *ERPShipmentDetailItemUpdate) ClearProductModel() *ERPShipmentDetailItemUpdate {
	_u.mutation.ClearProductModel()
	return _u
}

// SetPackDetail sets the "pack_detail" field.
func (_u *ERPShipmentDetailItemUpdate) SetPackDetail(v string) *ERPShipmentDetailItemUpdate {
	_u.mutation.SetPackDetail(v)
	return _u
}

// SetNillablePackDetail sets the "pack_detail" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdate) SetNillablePackDetail(v *string) *ERPShipmentDetailItemUpdate {
	if v != nil {
		_u.SetPackDetail(*v)
	}
	return _u
}

// ClearPackDetail clears the value of the "pack_detail" field.
func (_u *ERPShipmentDetailItemUpdate) ClearPackDetail() *ERPShipmentDetailItemUpdate {
	_u.mutation.ClearPackDetail()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *ERPShipmentDetailItemUpdate) SetQuantity(v float64) *ERPShipmentDetailItemUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdate) SetNillableQuantity(v *float64) *ERPShipmentDetailItemUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *ERPShipmentDetailItemUpdate) AddQuantity(v float64) *ERPShipmentDetailItemUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *ERPShipmentDetailItemUpdate) SetUnitPrice(v float64) *ERPShipmentDetailItemUpdate {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdate) SetNillableUnitPrice(v *float64) *ERPShipmentDetailItemUpdate {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *ERPShipmentDetailItemUpdate) AddUnitPrice(v float64) *ERPShipmentDetailItemUpdate {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetTotalPrice sets the "total_price" field.
func (_u *ERPShipmentDetailItemUpdate) SetTotalPrice(v float64) *ERPShipmentDetailItemUpdate {
	_u.mutation.ResetTotalPrice()
	_u.mutation.SetTotalPrice(v)
	return _u
}

// SetNillableTotalPrice sets the "total_price" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdate) SetNillableTotalPrice(v *float64) *ERPShipmentDetailItemUpdate {
	if v != nil {
		_u.SetTotalPrice(*v)
	}
	return _u
}

// AddTotalPrice adds value to the "total_price" field.
func (_u *ERPShipmentDetailItemUpdate) AddTotalPrice(v float64) *ERPShipmentDetailItemUpdate {
	_u.mutation.AddTotalPrice(v)
	return _u
}

// SetNetWeight sets the "net_weight" field.
func (_u *ERPShipmentDetailItemUpdate) SetNetWeight(v float64) *ERPShipmentDetailItemUpdate {
	_u.mutation.ResetNetWeight()
	_u.mutation.SetNetWeight(v)
	return _u
}

// SetNillableNetWeight sets the "net_weight" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdate) SetNillableNetWeight(v *float64) *ERPShipmentDetailItemUpdate {
	if v != nil {
		_u.SetNetWeight(*v)
	}
	return _u
}

// AddNetWeight adds value to the "net_weight" field.
func (_u *ERPShipmentDetailItemUpdate) AddNetWeight(v float64) *ERPShipmentDetailItemUpdate {
	_u.mutation.AddNetWeight(v)
	return _u
}

// SetGrossWeight sets the "gross_weight" field.
func (_u *ERPShipmentDetailItemUpdate) SetGrossWeight(v float64) *ERPShipmentDetailItemUpdate {
	_u.mutation.ResetGrossWeight()
	_u.mutation.SetGrossWeight(v)
	return _u
}

// SetNillableGrossWeight sets the "gross_weight" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdate) SetNillableGrossWeight(v *float64) *ERPShipmentDetailItemUpdate {
	if v != nil {
		_u.SetGrossWeight(*v)
	}
	return _u
}

// AddGrossWeight adds value to the "gross_weight" field.
func (_u *ERPShipmentDetailItemUpdate) AddGrossWeight(v float64) *ERPShipmentDetailItemUpdate {
	_u.mutation.AddGrossWeight(v)
	return _u
}

// SetVolume sets the "volume" field.
func (_u *ERPShipmentDetailItemUpdate) SetVolume(v float64) *ERPShipmentDetailItemUpdate {
	_u.mutation.ResetVolume()
	_u.mutation.SetVolume(v)
	return _u
}

// SetNillableVolume sets the "volume" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdate) SetNillableVolume(v *float64) *ERPShipmentDetailItemUpdate {
	if v != nil {
		_u.SetVolume(*v)
	}
	return _u
}

// AddVolume adds value to the "volume" field.
func (_u *ERPShipmentDetailItemUpdate) AddVolume(v float64) *ERPShipmentDetailItemUpdate {
	_u.mutation.AddVolume(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ERPShipmentDetailItemUpdate) SetUpdatedAt(v time.Time) *ERPShipmentDetailItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ERPShipmentDetailItemMutation object of the builder.
func (_u *ERPShipmentDetailItemUpdate) Mutation() *ERPShipmentDetailItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ERPShipmentDetailItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ERPShipmentDetailItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ERPShipmentDetailItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ERPShipmentDetailItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ERPShipmentDetailItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := erpshipmentdetailitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ERPShipmentDetailItemUpdate) check() error {
	if v, ok := _u.mutation.ShipmentDetailID(); ok {
		if err := erpshipmentdetailitem.ShipmentDetailIDValidator(v); err != nil {
			return &ValidationError{Name: "shipment_detail_id", err: fmt.Errorf(`ent: validator failed for field "ERPShipmentDetailItem.shipment_detail_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LineNo(); ok {
		if err := erpshipmentdetailitem.LineNoValidator(v); err != nil {
			return &ValidationError{Name: "line_no", err: fmt.Errorf(`ent: validator failed for field "ERPShipmentDetailItem.line_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductCode(); ok {
		if err := erpshipmentdetailitem.ProductCodeValidator(v); err != nil {
			return &ValidationError{Name: "product_code", err: fmt.Errorf(`ent: validator failed for field "ERPShipmentDetailItem.product_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductModel(); ok {
		if err := erpshipmentdetailitem.ProductModelValidator(v); err != nil {
			return &ValidationError{Name: "product_model", err: fmt.Errorf(`ent: validator failed for field "ERPShipmentDetailItem.product_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PackDetail(); ok {
		if err := erpshipmentdetailitem.PackDetailValidator(v); err != nil {
			return &ValidationError{Name: "pack_detail", err: fmt.Errorf(`ent: validator failed for field "ERPShipmentDetailItem.pack_detail": %w`, err)}
		}
	}
	return nil
}

func (_u *ERPShipmentDetailItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(erpshipmentdetailitem.Table, erpshipmentdetailitem.Columns, sqlgraph.NewFieldSpec(erpshipmentdetailitem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ShipmentDetailID(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldShipmentDetailID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedShipmentDetailID(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldShipmentDetailID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LineNo(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldLineNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLineNo(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldLineNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldProductID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldProductID, field.TypeInt, value)
	}
	if _u.mutation.ProductIDCleared() {
		_spec.ClearField(erpshipmentdetailitem.FieldProductID, field.TypeInt)
	}
	if value, ok := _u.mutation.ProductCode(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldProductCode, field.TypeString, value)
	}
	if _u.mutation.ProductCodeCleared() {
		_spec.ClearField(erpshipmentdetailitem.FieldProductCode, field.TypeString)
	}
	if value, ok := _u.mutation.ProductModel(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldProductModel, field.TypeString, value)
	}
	if _u.mutation.ProductModelCleared() {
		_spec.ClearField(erpshipmentdetailitem.FieldProductModel, field.TypeString)
	}
	if value, ok := _u.mutation.PackDetail(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldPackDetail, field.TypeString, value)
	}
	if _u.mutation.PackDetailCleared() {
		_spec.ClearField(erpshipmentdetailitem.FieldPackDetail, field.TypeString)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalPrice(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalPrice(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.NetWeight(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldNetWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedNetWeight(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldNetWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GrossWeight(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldGrossWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrossWeight(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldGrossWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Volume(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldVolume, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedVolume(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldVolume, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{erpshipmentdetailitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ERPShipmentDetailItemUpdateOne is the builder for updating a single ERPShipmentDetailItem entity.
type ERPShipmentDetailItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ERPShipmentDetailItemMutation
}

// SetShipmentDetailID sets the "shipment_detail_id" field.
func (_u *ERPShipmentDetailItemUpdateOne) SetShipmentDetailID(v int) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.ResetShipmentDetailID()
	_u.mutation.SetShipmentDetailID(v)
	return _u
}

// SetNillableShipmentDetailID sets the "shipment_detail_id" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdateOne) SetNillableShipmentDetailID(v *int) *ERPShipmentDetailItemUpdateOne {
	if v != nil {
		_u.SetShipmentDetailID(*v)
	}
	return _u
}

// AddShipmentDetailID adds value to the "shipment_detail_id" field.
func (_u *ERPShipmentDetailItemUpdateOne) AddShipmentDetailID(v int) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.AddShipmentDetailID(v)
	return _u
}

// SetLineNo sets the "line_no" field.
func (_u *ERPShipmentDetailItemUpdateOne) SetLineNo(v int) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.ResetLineNo()
	_u.mutation.SetLineNo(v)
	return _u
}

// SetNillableLineNo sets the "line_no" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdateOne) SetNillableLineNo(v *int) *ERPShipmentDetailItemUpdateOne {
	if v != nil {
		_u.SetLineNo(*v)
	}
	return _u
}

// AddLineNo adds value to the "line_no" field.
func (_u *ERPShipmentDetailItemUpdateOne) AddLineNo(v int) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.AddLineNo(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ERPShipmentDetailItemUpdateOne) SetProductID(v int) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdateOne) SetNillableProductID(v *int) *ERPShipmentDetailItemUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *ERPShipmentDetailItemUpdateOne) AddProductID(v int) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.AddProductID(v)
	return _u
}

// ClearProductID clears the value of the "product_id" field.
func (_u *ERPShipmentDetailItemUpdateOne) ClearProductID() *ERPShipmentDetailItemUpdateOne {
	_u.mutation.ClearProductID()
	return _u
}

// SetProductCode sets the "product_code" field.
func (_u *ERPShipmentDetailItemUpdateOne) SetProductCode(v string) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.SetProductCode(v)
	return _u
}

// SetNillableProductCode sets the "product_code" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdateOne) SetNillableProductCode(v *string) *ERPShipmentDetailItemUpdateOne {
	if v != nil {
		_u.SetProductCode(*v)
	}
	return _u
}

// ClearProductCode clears the value of the "product_code" field.
func (_u *ERPShipmentDetailItemUpdateOne) ClearProductCode() *ERPShipmentDetailItemUpdateOne {
	_u.mutation.ClearProductCode()
	return _u
}

// SetProductModel sets the "product_model" field.
func (_u *ERPShipmentDetailItemUpdateOne) SetProductModel(v string) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.SetProductModel(v)
	return _u
}

// SetNillableProductModel sets the "product_model" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdateOne) SetNillableProductModel(v *string) *ERPShipmentDetailItemUpdateOne {
	if v != nil {
		_u.SetProductModel(*v)
	}
	return _u
}

// ClearProductModel clears the value of the "product_model" field.
func (_u *ERPShipmentDetailItemUpdateOne) ClearProductModel() *ERPShipmentDetailItemUpdateOne {
	_u.mutation.ClearProductModel()
	return _u
}

// SetPackDetail sets the "pack_detail" field.
func (_u *ERPShipmentDetailItemUpdateOne) SetPackDetail(v string) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.SetPackDetail(v)
	return _u
}

// SetNillablePackDetail sets the "pack_detail" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdateOne) SetNillablePackDetail(v *string) *ERPShipmentDetailItemUpdateOne {
	if v != nil {
		_u.SetPackDetail(*v)
	}
	return _u
}

// ClearPackDetail clears the value of the "pack_detail" field.
func (_u *ERPShipmentDetailItemUpdateOne) ClearPackDetail() *ERPShipmentDetailItemUpdateOne {
	_u.mutation.ClearPackDetail()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *ERPShipmentDetailItemUpdateOne) SetQuantity(v float64) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdateOne) SetNillableQuantity(v *float64) *ERPShipmentDetailItemUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *ERPShipmentDetailItemUpdateOne) AddQuantity(v float64) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *ERPShipmentDetailItemUpdateOne) SetUnitPrice(v float64) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdateOne) SetNillableUnitPrice(v *float64) *ERPShipmentDetailItemUpdateOne {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *ERPShipmentDetailItemUpdateOne) AddUnitPrice(v float64) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetTotalPrice sets the "total_price" field.
func (_u *ERPShipmentDetailItemUpdateOne) SetTotalPrice(v float64) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.ResetTotalPrice()
	_u.mutation.SetTotalPrice(v)
	return _u
}

// SetNillableTotalPrice sets the "total_price" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdateOne) SetNillableTotalPrice(v *float64) *ERPShipmentDetailItemUpdateOne {
	if v != nil {
		_u.SetTotalPrice(*v)
	}
	return _u
}

// AddTotalPrice adds value to the "total_price" field.
func (_u *ERPShipmentDetailItemUpdateOne) AddTotalPrice(v float64) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.AddTotalPrice(v)
	return _u
}

// SetNetWeight sets the "net_weight" field.
func (_u *ERPShipmentDetailItemUpdateOne) SetNetWeight(v float64) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.ResetNetWeight()
	_u.mutation.SetNetWeight(v)
	return _u
}

// SetNillableNetWeight sets the "net_weight" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdateOne) SetNillableNetWeight(v *float64) *ERPShipmentDetailItemUpdateOne {
	if v != nil {
		_u.SetNetWeight(*v)
	}
	return _u
}

// AddNetWeight adds value to the "net_weight" field.
func (_u *ERPShipmentDetailItemUpdateOne) AddNetWeight(v float64) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.AddNetWeight(v)
	return _u
}

// SetGrossWeight sets the "gross_weight" field.
func (_u *ERPShipmentDetailItemUpdateOne) SetGrossWeight(v float64) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.ResetGrossWeight()
	_u.mutation.SetGrossWeight(v)
	return _u
}

// SetNillableGrossWeight sets the "gross_weight" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdateOne) SetNillableGrossWeight(v *float64) *ERPShipmentDetailItemUpdateOne {
	if v != nil {
		_u.SetGrossWeight(*v)
	}
	return _u
}

// AddGrossWeight adds value to the "gross_weight" field.
func (_u *ERPShipmentDetailItemUpdateOne) AddGrossWeight(v float64) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.AddGrossWeight(v)
	return _u
}

// SetVolume sets the "volume" field.
func (_u *ERPShipmentDetailItemUpdateOne) SetVolume(v float64) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.ResetVolume()
	_u.mutation.SetVolume(v)
	return _u
}

// SetNillableVolume sets the "volume" field if the given value is not nil.
func (_u *ERPShipmentDetailItemUpdateOne) SetNillableVolume(v *float64) *ERPShipmentDetailItemUpdateOne {
	if v != nil {
		_u.SetVolume(*v)
	}
	return _u
}

// AddVolume adds value to the "volume" field.
func (_u *ERPShipmentDetailItemUpdateOne) AddVolume(v float64) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.AddVolume(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ERPShipmentDetailItemUpdateOne) SetUpdatedAt(v time.Time) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ERPShipmentDetailItemMutation object of the builder.
func (_u *ERPShipmentDetailItemUpdateOne) Mutation() *ERPShipmentDetailItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the ERPShipmentDetailItemUpdate builder.
func (_u *ERPShipmentDetailItemUpdateOne) Where(ps ...predicate.ERPShipmentDetailItem) *ERPShipmentDetailItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ERPShipmentDetailItemUpdateOne) Select(field string, fields ...string) *ERPShipmentDetailItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ERPShipmentDetailItem entity.
func (_u *ERPShipmentDetailItemUpdateOne) Save(ctx context.Context) (*ERPShipmentDetailItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ERPShipmentDetailItemUpdateOne) SaveX(ctx context.Context) *ERPShipmentDetailItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ERPShipmentDetailItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ERPShipmentDetailItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ERPShipmentDetailItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := erpshipmentdetailitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ERPShipmentDetailItemUpdateOne) check() error {
	if v, ok := _u.mutation.ShipmentDetailID(); ok {
		if err := erpshipmentdetailitem.ShipmentDetailIDValidator(v); err != nil {
			return &ValidationError{Name: "shipment_detail_id", err: fmt.Errorf(`ent: validator failed for field "ERPShipmentDetailItem.shipment_detail_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LineNo(); ok {
		if err := erpshipmentdetailitem.LineNoValidator(v); err != nil {
			return &ValidationError{Name: "line_no", err: fmt.Errorf(`ent: validator failed for field "ERPShipmentDetailItem.line_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductCode(); ok {
		if err := erpshipmentdetailitem.ProductCodeValidator(v); err != nil {
			return &ValidationError{Name: "product_code", err: fmt.Errorf(`ent: validator failed for field "ERPShipmentDetailItem.product_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductModel(); ok {
		if err := erpshipmentdetailitem.ProductModelValidator(v); err != nil {
			return &ValidationError{Name: "product_model", err: fmt.Errorf(`ent: validator failed for field "ERPShipmentDetailItem.product_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PackDetail(); ok {
		if err := erpshipmentdetailitem.PackDetailValidator(v); err != nil {
			return &ValidationError{Name: "pack_detail", err: fmt.Errorf(`ent: validator failed for field "ERPShipmentDetailItem.pack_detail": %w`, err)}
		}
	}
	return nil
}

func (_u *ERPShipmentDetailItemUpdateOne) sqlSave(ctx context.Context) (_node *ERPShipmentDetailItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(erpshipmentdetailitem.Table, erpshipmentdetailitem.Columns, sqlgraph.NewFieldSpec(erpshipmentdetailitem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ERPShipmentDetailItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, erpshipmentdetailitem.FieldID)
		for _, f := range fields {
			if !erpshipmentdetailitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != erpshipmentdetailitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ShipmentDetailID(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldShipmentDetailID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedShipmentDetailID(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldShipmentDetailID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LineNo(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldLineNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLineNo(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldLineNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldProductID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldProductID, field.TypeInt, value)
	}
	if _u.mutation.ProductIDCleared() {
		_spec.ClearField(erpshipmentdetailitem.FieldProductID, field.TypeInt)
	}
	if value, ok := _u.mutation.ProductCode(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldProductCode, field.TypeString, value)
	}
	if _u.mutation.ProductCodeCleared() {
		_spec.ClearField(erpshipmentdetailitem.FieldProductCode, field.TypeString)
	}
	if value, ok := _u.mutation.ProductModel(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldProductModel, field.TypeString, value)
	}
	if _u.mutation.ProductModelCleared() {
		_spec.ClearField(erpshipmentdetailitem.FieldProductModel, field.TypeString)
	}
	if value, ok := _u.mutation.PackDetail(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldPackDetail, field.TypeString, value)
	}
	if _u.mutation.PackDetailCleared() {
		_spec.ClearField(erpshipmentdetailitem.FieldPackDetail, field.TypeString)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalPrice(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalPrice(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.NetWeight(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldNetWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedNetWeight(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldNetWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GrossWeight(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldGrossWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrossWeight(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldGrossWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Volume(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldVolume, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedVolume(); ok {
		_spec.AddField(erpshipmentdetailitem.FieldVolume, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(erpshipmentdetailitem.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ERPShipmentDetailItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{erpshipmentdetailitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
