// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"server/internal/data/model/ent/erpstockbalance"
	"server/internal/data/model/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ERPStockBalanceDelete is the builder for deleting a ERPStockBalance entity.
type ERPStockBalanceDelete struct {
	config
	hooks    []Hook
	mutation *ERPStockBalanceMutation
}

// Where appends a list predicates to the ERPStockBalanceDelete builder.
func (_d *ERPStockBalanceDelete) Where(ps ...predicate.ERPStockBalance) *ERPStockBalanceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ERPStockBalanceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ERPStockBalanceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ERPStockBalanceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(erpstockbalance.Table, sqlgraph.NewFieldSpec(erpstockbalance.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ERPStockBalanceDeleteOne is the builder for deleting a single ERPStockBalance entity.
type ERPStockBalanceDeleteOne struct {
	_d *ERPStockBalanceDelete
}

// Where appends a list predicates to the ERPStockBalanceDelete builder.
func (_d *ERPStockBalanceDeleteOne) Where(ps ...predicate.ERPStockBalance) *ERPStockBalanceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ERPStockBalanceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{erpstockbalance.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ERPStockBalanceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
