// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"server/internal/data/model/ent/erpshipmentdetailitem"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ERPShipmentDetailItem is the model entity for the ERPShipmentDetailItem schema.
type ERPShipmentDetailItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ShipmentDetailID holds the value of the "shipment_detail_id" field.
	ShipmentDetailID int `json:"shipment_detail_id,omitempty"`
	// LineNo holds the value of the "line_no" field.
	LineNo int `json:"line_no,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID *int `json:"product_id,omitempty"`
	// ProductCode holds the value of the "product_code" field.
	ProductCode *string `json:"product_code,omitempty"`
	// ProductModel holds the value of the "product_model" field.
	ProductModel *string `json:"product_model,omitempty"`
	// PackDetail holds the value of the "pack_detail" field.
	PackDetail *string `json:"pack_detail,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity float64 `json:"quantity,omitempty"`
	// UnitPrice holds the value of the "unit_price" field.
	UnitPrice float64 `json:"unit_price,omitempty"`
	// TotalPrice holds the value of the "total_price" field.
	TotalPrice float64 `json:"total_price,omitempty"`
	// NetWeight holds the value of the "net_weight" field.
	NetWeight float64 `json:"net_weight,omitempty"`
	// GrossWeight holds the value of the "gross_weight" field.
	GrossWeight float64 `json:"gross_weight,omitempty"`
	// Volume holds the value of the "volume" field.
	Volume float64 `json:"volume,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ERPShipmentDetailItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case erpshipmentdetailitem.FieldQuantity, erpshipmentdetailitem.FieldUnitPrice, erpshipmentdetailitem.FieldTotalPrice, erpshipmentdetailitem.FieldNetWeight, erpshipmentdetailitem.FieldGrossWeight, erpshipmentdetailitem.FieldVolume:
			values[i] = new(sql.NullFloat64)
		case erpshipmentdetailitem.FieldID, erpshipmentdetailitem.FieldShipmentDetailID, erpshipmentdetailitem.FieldLineNo, erpshipmentdetailitem.FieldProductID:
			values[i] = new(sql.NullInt64)
		case erpshipmentdetailitem.FieldProductCode, erpshipmentdetailitem.FieldProductModel, erpshipmentdetailitem.FieldPackDetail:
			values[i] = new(sql.NullString)
		case erpshipmentdetailitem.FieldCreatedAt, erpshipmentdetailitem.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ERPShipmentDetailItem fields.
func (_m *ERPShipmentDetailItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case erpshipmentdetailitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case erpshipmentdetailitem.FieldShipmentDetailID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field shipment_detail_id", values[i])
			} else if value.Valid {
				_m.ShipmentDetailID = int(value.Int64)
			}
		case erpshipmentdetailitem.FieldLineNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field line_no", values[i])
			} else if value.Valid {
				_m.LineNo = int(value.Int64)
			}
		case erpshipmentdetailitem.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = new(int)
				*_m.ProductID = int(value.Int64)
			}
		case erpshipmentdetailitem.FieldProductCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_code", values[i])
			} else if value.Valid {
				_m.ProductCode = new(string)
				*_m.ProductCode = value.String
			}
		case erpshipmentdetailitem.FieldProductModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_model", values[i])
			} else if value.Valid {
				_m.ProductModel = new(string)
				*_m.ProductModel = value.String
			}
		case erpshipmentdetailitem.FieldPackDetail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pack_detail", values[i])
			} else if value.Valid {
				_m.PackDetail = new(string)
				*_m.PackDetail = value.String
			}
		case erpshipmentdetailitem.FieldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = value.Float64
			}
		case erpshipmentdetailitem.FieldUnitPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field unit_price", values[i])
			} else if value.Valid {
				_m.UnitPrice = value.Float64
			}
		case erpshipmentdetailitem.FieldTotalPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_price", values[i])
			} else if value.Valid {
				_m.TotalPrice = value.Float64
			}
		case erpshipmentdetailitem.FieldNetWeight:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field net_weight", values[i])
			} else if value.Valid {
				_m.NetWeight = value.Float64
			}
		case erpshipmentdetailitem.FieldGrossWeight:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field gross_weight", values[i])
			} else if value.Valid {
				_m.GrossWeight = value.Float64
			}
		case erpshipmentdetailitem.FieldVolume:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field volume", values[i])
			} else if value.Valid {
				_m.Volume = value.Float64
			}
		case erpshipmentdetailitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case erpshipmentdetailitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ERPShipmentDetailItem.
// This includes values selected through modifiers, order, etc.
func (_m *ERPShipmentDetailItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ERPShipmentDetailItem.
// Note that you need to call ERPShipmentDetailItem.Unwrap() before calling this method if this ERPShipmentDetailItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ERPShipmentDetailItem) Update() *ERPShipmentDetailItemUpdateOne {
	return NewERPShipmentDetailItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ERPShipmentDetailItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ERPShipmentDetailItem) Unwrap() *ERPShipmentDetailItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ERPShipmentDetailItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ERPShipmentDetailItem) String() string {
	var builder strings.Builder
	builder.WriteString("ERPShipmentDetailItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("shipment_detail_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShipmentDetailID))
	builder.WriteString(", ")
	builder.WriteString("line_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.LineNo))
	builder.WriteString(", ")
	if v := _m.ProductID; v != nil {
		builder.WriteString("product_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProductCode; v != nil {
		builder.WriteString("product_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProductModel; v != nil {
		builder.WriteString("product_model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PackDetail; v != nil {
		builder.WriteString("pack_detail=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("unit_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnitPrice))
	builder.WriteString(", ")
	builder.WriteString("total_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalPrice))
	builder.WriteString(", ")
	builder.WriteString("net_weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.NetWeight))
	builder.WriteString(", ")
	builder.WriteString("gross_weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrossWeight))
	builder.WriteString(", ")
	builder.WriteString("volume=")
	builder.WriteString(fmt.Sprintf("%v", _m.Volume))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ERPShipmentDetailItems is a parsable slice of ERPShipmentDetailItem.
type ERPShipmentDetailItems []*ERPShipmentDetailItem
