// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/erpworkflowinstance"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ERPWorkflowInstanceCreate is the builder for creating a ERPWorkflowInstance entity.
type ERPWorkflowInstanceCreate struct {
	config
	mutation *ERPWorkflowInstanceMutation
	hooks    []Hook
}

// SetBizModule sets the "biz_module" field.
func (_c *ERPWorkflowInstanceCreate) SetBizModule(v string) *ERPWorkflowInstanceCreate {
	_c.mutation.SetBizModule(v)
	return _c
}

// SetBizCode sets the "biz_code" field.
func (_c *ERPWorkflowInstanceCreate) SetBizCode(v string) *ERPWorkflowInstanceCreate {
	_c.mutation.SetBizCode(v)
	return _c
}

// SetCurrentStatus sets the "current_status" field.
func (_c *ERPWorkflowInstanceCreate) SetCurrentStatus(v string) *ERPWorkflowInstanceCreate {
	_c.mutation.SetCurrentStatus(v)
	return _c
}

// SetNillableCurrentStatus sets the "current_status" field if the given value is not nil.
func (_c *ERPWorkflowInstanceCreate) SetNillableCurrentStatus(v *string) *ERPWorkflowInstanceCreate {
	if v != nil {
		_c.SetCurrentStatus(*v)
	}
	return _c
}

// SetStarterAdminID sets the "starter_admin_id" field.
func (_c *ERPWorkflowInstanceCreate) SetStarterAdminID(v int) *ERPWorkflowInstanceCreate {
	_c.mutation.SetStarterAdminID(v)
	return _c
}

// SetNillableStarterAdminID sets the "starter_admin_id" field if the given value is not nil.
func (_c *ERPWorkflowInstanceCreate) SetNillableStarterAdminID(v *int) *ERPWorkflowInstanceCreate {
	if v != nil {
		_c.SetStarterAdminID(*v)
	}
	return _c
}

// SetSubmittedAt sets the "submitted_at" field.
func (_c *ERPWorkflowInstanceCreate) SetSubmittedAt(v time.Time) *ERPWorkflowInstanceCreate {
	_c.mutation.SetSubmittedAt(v)
	return _c
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_c *ERPWorkflowInstanceCreate) SetNillableSubmittedAt(v *time.Time) *ERPWorkflowInstanceCreate {
	if v != nil {
		_c.SetSubmittedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *ERPWorkflowInstanceCreate) SetFinishedAt(v time.Time) *ERPWorkflowInstanceCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *ERPWorkflowInstanceCreate) SetNillableFinishedAt(v *time.Time) *ERPWorkflowInstanceCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ERPWorkflowInstanceCreate) SetCreatedAt(v time.Time) *ERPWorkflowInstanceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ERPWorkflowInstanceCreate) SetNillableCreatedAt(v *time.Time) *ERPWorkflowInstanceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ERPWorkflowInstanceCreate) SetUpdatedAt(v time.Time) *ERPWorkflowInstanceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ERPWorkflowInstanceCreate) SetNillableUpdatedAt(v *time.Time) *ERPWorkflowInstanceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ERPWorkflowInstanceMutation object of the builder.
func (_c *ERPWorkflowInstanceCreate) Mutation() *ERPWorkflowInstanceMutation {
	return _c.mutation
}

// Save creates the ERPWorkflowInstance in the database.
func (_c *ERPWorkflowInstanceCreate) Save(ctx context.Context) (*ERPWorkflowInstance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ERPWorkflowInstanceCreate) SaveX(ctx context.Context) *ERPWorkflowInstance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ERPWorkflowInstanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ERPWorkflowInstanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ERPWorkflowInstanceCreate) defaults() {
	if _, ok := _c.mutation.CurrentStatus(); !ok {
		v := erpworkflowinstance.DefaultCurrentStatus
		_c.mutation.SetCurrentStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := erpworkflowinstance.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := erpworkflowinstance.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ERPWorkflowInstanceCreate) check() error {
	if _, ok := _c.mutation.BizModule(); !ok {
		return &ValidationError{Name: "biz_module", err: errors.New(`ent: missing required field "ERPWorkflowInstance.biz_module"`)}
	}
	if v, ok := _c.mutation.BizModule(); ok {
		if err := erpworkflowinstance.BizModuleValidator(v); err != nil {
			return &ValidationError{Name: "biz_module", err: fmt.Errorf(`ent: validator failed for field "ERPWorkflowInstance.biz_module": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BizCode(); !ok {
		return &ValidationError{Name: "biz_code", err: errors.New(`ent: missing required field "ERPWorkflowInstance.biz_code"`)}
	}
	if v, ok := _c.mutation.BizCode(); ok {
		if err := erpworkflowinstance.BizCodeValidator(v); err != nil {
			return &ValidationError{Name: "biz_code", err: fmt.Errorf(`ent: validator failed for field "ERPWorkflowInstance.biz_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CurrentStatus(); !ok {
		return &ValidationError{Name: "current_status", err: errors.New(`ent: missing required field "ERPWorkflowInstance.current_status"`)}
	}
	if v, ok := _c.mutation.CurrentStatus(); ok {
		if err := erpworkflowinstance.CurrentStatusValidator(v); err != nil {
			return &ValidationError{Name: "current_status", err: fmt.Errorf(`ent: validator failed for field "ERPWorkflowInstance.current_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ERPWorkflowInstance.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ERPWorkflowInstance.updated_at"`)}
	}
	return nil
}

func (_c *ERPWorkflowInstanceCreate) sqlSave(ctx context.Context) (*ERPWorkflowInstance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ERPWorkflowInstanceCreate) createSpec() (*ERPWorkflowInstance, *sqlgraph.CreateSpec) {
	var (
		_node = &ERPWorkflowInstance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(erpworkflowinstance.Table, sqlgraph.NewFieldSpec(erpworkflowinstance.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.BizModule(); ok {
		_spec.SetField(erpworkflowinstance.FieldBizModule, field.TypeString, value)
		_node.BizModule = value
	}
	if value, ok := _c.mutation.BizCode(); ok {
		_spec.SetField(erpworkflowinstance.FieldBizCode, field.TypeString, value)
		_node.BizCode = value
	}
	if value, ok := _c.mutation.CurrentStatus(); ok {
		_spec.SetField(erpworkflowinstance.FieldCurrentStatus, field.TypeString, value)
		_node.CurrentStatus = value
	}
	if value, ok := _c.mutation.StarterAdminID(); ok {
		_spec.SetField(erpworkflowinstance.FieldStarterAdminID, field.TypeInt, value)
		_node.StarterAdminID = &value
	}
	if value, ok := _c.mutation.SubmittedAt(); ok {
		_spec.SetField(erpworkflowinstance.FieldSubmittedAt, field.TypeTime, value)
		_node.SubmittedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(erpworkflowinstance.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(erpworkflowinstance.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(erpworkflowinstance.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ERPWorkflowInstanceCreateBulk is the builder for creating many ERPWorkflowInstance entities in bulk.
type ERPWorkflowInstanceCreateBulk struct {
	config
	err      error
	builders []*ERPWorkflowInstanceCreate
}

// Save creates the ERPWorkflowInstance entities in the database.
func (_c *ERPWorkflowInstanceCreateBulk) Save(ctx context.Context) ([]*ERPWorkflowInstance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ERPWorkflowInstance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ERPWorkflowInstanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ERPWorkflowInstanceCreateBulk) SaveX(ctx context.Context) []*ERPWorkflowInstance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ERPWorkflowInstanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ERPWorkflowInstanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
