// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/erpwarehouse"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ERPWarehouseCreate is the builder for creating a ERPWarehouse entity.
type ERPWarehouseCreate struct {
	config
	mutation *ERPWarehouseMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *ERPWarehouseCreate) SetCode(v string) *ERPWarehouseCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ERPWarehouseCreate) SetName(v string) *ERPWarehouseCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *ERPWarehouseCreate) SetDisabled(v bool) *ERPWarehouseCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *ERPWarehouseCreate) SetNillableDisabled(v *bool) *ERPWarehouseCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ERPWarehouseCreate) SetCreatedAt(v time.Time) *ERPWarehouseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ERPWarehouseCreate) SetNillableCreatedAt(v *time.Time) *ERPWarehouseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ERPWarehouseCreate) SetUpdatedAt(v time.Time) *ERPWarehouseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ERPWarehouseCreate) SetNillableUpdatedAt(v *time.Time) *ERPWarehouseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ERPWarehouseMutation object of the builder.
func (_c *ERPWarehouseCreate) Mutation() *ERPWarehouseMutation {
	return _c.mutation
}

// Save creates the ERPWarehouse in the database.
func (_c *ERPWarehouseCreate) Save(ctx context.Context) (*ERPWarehouse, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ERPWarehouseCreate) SaveX(ctx context.Context) *ERPWarehouse {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ERPWarehouseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ERPWarehouseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ERPWarehouseCreate) defaults() {
	if _, ok := _c.mutation.Disabled(); !ok {
		v := erpwarehouse.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := erpwarehouse.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := erpwarehouse.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ERPWarehouseCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "ERPWarehouse.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := erpwarehouse.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ERPWarehouse.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ERPWarehouse.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := erpwarehouse.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ERPWarehouse.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		return &ValidationError{Name: "disabled", err: errors.New(`ent: missing required field "ERPWarehouse.disabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ERPWarehouse.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ERPWarehouse.updated_at"`)}
	}
	return nil
}

func (_c *ERPWarehouseCreate) sqlSave(ctx context.Context) (*ERPWarehouse, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ERPWarehouseCreate) createSpec() (*ERPWarehouse, *sqlgraph.CreateSpec) {
	var (
		_node = &ERPWarehouse{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(erpwarehouse.Table, sqlgraph.NewFieldSpec(erpwarehouse.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(erpwarehouse.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(erpwarehouse.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(erpwarehouse.FieldDisabled, field.TypeBool, value)
		_node.Disabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(erpwarehouse.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(erpwarehouse.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ERPWarehouseCreateBulk is the builder for creating many ERPWarehouse entities in bulk.
type ERPWarehouseCreateBulk struct {
	config
	err      error
	builders []*ERPWarehouseCreate
}

// Save creates the ERPWarehouse entities in the database.
func (_c *ERPWarehouseCreateBulk) Save(ctx context.Context) ([]*ERPWarehouse, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ERPWarehouse, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ERPWarehouseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ERPWarehouseCreateBulk) SaveX(ctx context.Context) []*ERPWarehouse {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ERPWarehouseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ERPWarehouseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
