// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/erpworkflowactionlog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ERPWorkflowActionLogCreate is the builder for creating a ERPWorkflowActionLog entity.
type ERPWorkflowActionLogCreate struct {
	config
	mutation *ERPWorkflowActionLogMutation
	hooks    []Hook
}

// SetWorkflowInstanceID sets the "workflow_instance_id" field.
func (_c *ERPWorkflowActionLogCreate) SetWorkflowInstanceID(v int) *ERPWorkflowActionLogCreate {
	_c.mutation.SetWorkflowInstanceID(v)
	return _c
}

// SetWorkflowTaskID sets the "workflow_task_id" field.
func (_c *ERPWorkflowActionLogCreate) SetWorkflowTaskID(v int) *ERPWorkflowActionLogCreate {
	_c.mutation.SetWorkflowTaskID(v)
	return _c
}

// SetNillableWorkflowTaskID sets the "workflow_task_id" field if the given value is not nil.
func (_c *ERPWorkflowActionLogCreate) SetNillableWorkflowTaskID(v *int) *ERPWorkflowActionLogCreate {
	if v != nil {
		_c.SetWorkflowTaskID(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *ERPWorkflowActionLogCreate) SetAction(v string) *ERPWorkflowActionLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetFromStatus sets the "from_status" field.
func (_c *ERPWorkflowActionLogCreate) SetFromStatus(v string) *ERPWorkflowActionLogCreate {
	_c.mutation.SetFromStatus(v)
	return _c
}

// SetNillableFromStatus sets the "from_status" field if the given value is not nil.
func (_c *ERPWorkflowActionLogCreate) SetNillableFromStatus(v *string) *ERPWorkflowActionLogCreate {
	if v != nil {
		_c.SetFromStatus(*v)
	}
	return _c
}

// SetToStatus sets the "to_status" field.
func (_c *ERPWorkflowActionLogCreate) SetToStatus(v string) *ERPWorkflowActionLogCreate {
	_c.mutation.SetToStatus(v)
	return _c
}

// SetNillableToStatus sets the "to_status" field if the given value is not nil.
func (_c *ERPWorkflowActionLogCreate) SetNillableToStatus(v *string) *ERPWorkflowActionLogCreate {
	if v != nil {
		_c.SetToStatus(*v)
	}
	return _c
}

// SetOperatorAdminID sets the "operator_admin_id" field.
func (_c *ERPWorkflowActionLogCreate) SetOperatorAdminID(v int) *ERPWorkflowActionLogCreate {
	_c.mutation.SetOperatorAdminID(v)
	return _c
}

// SetNillableOperatorAdminID sets the "operator_admin_id" field if the given value is not nil.
func (_c *ERPWorkflowActionLogCreate) SetNillableOperatorAdminID(v *int) *ERPWorkflowActionLogCreate {
	if v != nil {
		_c.SetOperatorAdminID(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *ERPWorkflowActionLogCreate) SetRemark(v string) *ERPWorkflowActionLogCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *ERPWorkflowActionLogCreate) SetNillableRemark(v *string) *ERPWorkflowActionLogCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ERPWorkflowActionLogCreate) SetCreatedAt(v time.Time) *ERPWorkflowActionLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ERPWorkflowActionLogCreate) SetNillableCreatedAt(v *time.Time) *ERPWorkflowActionLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ERPWorkflowActionLogMutation object of the builder.
func (_c *ERPWorkflowActionLogCreate) Mutation() *ERPWorkflowActionLogMutation {
	return _c.mutation
}

// Save creates the ERPWorkflowActionLog in the database.
func (_c *ERPWorkflowActionLogCreate) Save(ctx context.Context) (*ERPWorkflowActionLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ERPWorkflowActionLogCreate) SaveX(ctx context.Context) *ERPWorkflowActionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ERPWorkflowActionLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ERPWorkflowActionLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ERPWorkflowActionLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := erpworkflowactionlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ERPWorkflowActionLogCreate) check() error {
	if _, ok := _c.mutation.WorkflowInstanceID(); !ok {
		return &ValidationError{Name: "workflow_instance_id", err: errors.New(`ent: missing required field "ERPWorkflowActionLog.workflow_instance_id"`)}
	}
	if v, ok := _c.mutation.WorkflowInstanceID(); ok {
		if err := erpworkflowactionlog.WorkflowInstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "workflow_instance_id", err: fmt.Errorf(`ent: validator failed for field "ERPWorkflowActionLog.workflow_instance_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "ERPWorkflowActionLog.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := erpworkflowactionlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "ERPWorkflowActionLog.action": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FromStatus(); ok {
		if err := erpworkflowactionlog.FromStatusValidator(v); err != nil {
			return &ValidationError{Name: "from_status", err: fmt.Errorf(`ent: validator failed for field "ERPWorkflowActionLog.from_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ToStatus(); ok {
		if err := erpworkflowactionlog.ToStatusValidator(v); err != nil {
			return &ValidationError{Name: "to_status", err: fmt.Errorf(`ent: validator failed for field "ERPWorkflowActionLog.to_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Remark(); ok {
		if err := erpworkflowactionlog.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "ERPWorkflowActionLog.remark": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ERPWorkflowActionLog.created_at"`)}
	}
	return nil
}

func (_c *ERPWorkflowActionLogCreate) sqlSave(ctx context.Context) (*ERPWorkflowActionLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ERPWorkflowActionLogCreate) createSpec() (*ERPWorkflowActionLog, *sqlgraph.CreateSpec) {
	var (
		_node = &ERPWorkflowActionLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(erpworkflowactionlog.Table, sqlgraph.NewFieldSpec(erpworkflowactionlog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.WorkflowInstanceID(); ok {
		_spec.SetField(erpworkflowactionlog.FieldWorkflowInstanceID, field.TypeInt, value)
		_node.WorkflowInstanceID = value
	}
	if value, ok := _c.mutation.WorkflowTaskID(); ok {
		_spec.SetField(erpworkflowactionlog.FieldWorkflowTaskID, field.TypeInt, value)
		_node.WorkflowTaskID = &value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(erpworkflowactionlog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.FromStatus(); ok {
		_spec.SetField(erpworkflowactionlog.FieldFromStatus, field.TypeString, value)
		_node.FromStatus = &value
	}
	if value, ok := _c.mutation.ToStatus(); ok {
		_spec.SetField(erpworkflowactionlog.FieldToStatus, field.TypeString, value)
		_node.ToStatus = &value
	}
	if value, ok := _c.mutation.OperatorAdminID(); ok {
		_spec.SetField(erpworkflowactionlog.FieldOperatorAdminID, field.TypeInt, value)
		_node.OperatorAdminID = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(erpworkflowactionlog.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(erpworkflowactionlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ERPWorkflowActionLogCreateBulk is the builder for creating many ERPWorkflowActionLog entities in bulk.
type ERPWorkflowActionLogCreateBulk struct {
	config
	err      error
	builders []*ERPWorkflowActionLogCreate
}

// Save creates the ERPWorkflowActionLog entities in the database.
func (_c *ERPWorkflowActionLogCreateBulk) Save(ctx context.Context) ([]*ERPWorkflowActionLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ERPWorkflowActionLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ERPWorkflowActionLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ERPWorkflowActionLogCreateBulk) SaveX(ctx context.Context) []*ERPWorkflowActionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ERPWorkflowActionLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ERPWorkflowActionLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
